<script setup>
import {computed,onBeforeUnmount,onMounted,reactive,ref,watch} from 'vue'
import {CalendarDays,Plus,RefreshCw,Upload} from '@lucide/vue'
import {dutyAll,dutyRead,dutySave,dutyWrite} from '../../duty/api.js'
import {dutyTime,localDate,rosterCalendar,rosterPayload,statusText} from '../../duty/state.js'
import {can} from '../../permissions.js'
import {notifyError} from '../../api.js'
import {UiMessage,UiMessageBox} from '../../ui/feedback.js'
import {createClientId} from '../../clientId.js'
import DutyUserSelect from './DutyUserSelect.vue'
import DataTableCard from '../layout/DataTableCard.vue'
const props=defineProps({catalog:Object})
const month=ref(localDate().slice(0,7)),stationId=ref(''),rows=ref([]),total=ref(0),page=ref(1),pageSize=ref(20),loading=ref(false),error=ref(''),dialog=ref(''),saving=ref(false),form=reactive({}),validation=ref(null),importCSV=ref(''),preview=ref(null),history=ref(null)
let generation=0
const pagedRows=computed(()=>rows.value.slice((page.value-1)*pageSize.value,page.value*pageSize.value))
const calendar=computed(()=>rosterCalendar(rows.value,month.value)),manage=computed(()=>can('action:duty:roster'))
async function load(){const token=++generation;loading.value=true;error.value='';try{const [year,num]=month.value.split('-').map(Number);const value=await dutyAll('rosters',{stationId:stationId.value,start:new Date(year,num-1,1).getTime(),end:new Date(year,num,1).getTime()});if(token!==generation)return;rows.value=value.items || [];total.value=value.total || 0}catch(exception){if(token===generation)error.value=exception.message}finally{if(token===generation)loading.value=false}}
watch([month,stationId],()=>{page.value=1;load()});watch(pageSize,()=>{page.value=1})
function setForm(kind,row){dialog.value=kind;validation.value=null;preview.value=null;for(const key of Object.keys(form))delete form[key];Object.assign(form,{stationId:stationId.value || props.catalog.stations[0]?.id || '',templateId:'',teamId:'',memberIds:[],leaderId:'',reason:'',startAt:Date.now(),endAt:Date.now()+12*3600e3,from:localDate(),to:localDate()},row || {},{idempotencyKey:createClientId()})}
function selectTeam(){const team=props.catalog.teams.find(value=>value.id===form.teamId);if(team){form.memberIds=[...team.memberIds];form.leaderId=team.leaderId}}
function setTemplate(){const template=props.catalog.templates.find(value=>value.id===form.templateId);if(!template)return;const date=localDate(form.startAt);form.startAt=new Date(`${date}T${template.startTime}:00`).getTime();const next=new Date(form.startAt);next.setDate(next.getDate()+template.endDayOffset);form.endAt=new Date(`${localDate(next)}T${template.endTime}:00`).getTime()}
async function save(){if(saving.value)return;saving.value=true;try{if(dialog.value==='generate'){if(!form.from || !form.to || form.to<form.from)throw Error('请选择有效日期范围');await dutyWrite('rosters','','generate',form)}else{const body={...rosterPayload(form),id:form.id,teamId:form.teamId,idempotencyKey:form.idempotencyKey};await dutySave('rosters',body)}dialog.value='';await load();UiMessage.success('排班已保存')}catch(exception){notifyError(exception)}finally{saving.value=false}}
async function validate(row){try{validation.value=await dutyWrite('rosters',row.id,'validate',{version:row.version});history.value=row;dialog.value='validate'}catch(exception){notifyError(exception)}}
async function publish(row){if(saving.value)return;saving.value=true;try{const result=await dutyWrite('rosters',row.id,'validate',{version:row.version});if(result.problems?.length || result.valid===false){validation.value=result;history.value=row;dialog.value='validate';return}await UiMessageBox.confirm(`发布 ${props.catalog.stationName(row.stationId)} ${dutyTime(row.startAt)} 的排班？${result.gaps?.length?'该岗位还有 '+result.gaps.length+' 个时间缺口，请安排其余班次。':''}`,'发布排班');await dutyWrite('rosters',row.id,'publish',{version:row.version});await load();UiMessage.success('排班已发布')}catch(exception){if(exception!=='cancel' && exception!=='close')notifyError(exception)}finally{saving.value=false}}
function cancel(row){setForm('cancel',row)}
async function applyCancel(){saving.value=true;try{if(!form.reason?.trim())throw Error('请填写取消原因');await dutyWrite('rosters',form.id,'cancel',form);dialog.value='';await load()}catch(exception){notifyError(exception)}finally{saving.value=false}}
async function fileCSV(event){const file=event.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){notifyError(Error('CSV 文件请控制在 2 MiB 内'));return}importCSV.value=await file.text();preview.value=null;event.target.value=''}
async function importPreview(){saving.value=true;try{if(!importCSV.value.trim())throw Error('请上传或粘贴 CSV');preview.value=await dutyWrite('rosters','','import-preview',{csv:importCSV.value})}catch(exception){notifyError(exception)}finally{saving.value=false}}
async function importRows(){saving.value=true;try{if(!preview.value?.digest || preview.value.problems?.length)throw Error('请先通过导入检查');await dutyWrite('rosters','','import',{csv:importCSV.value,digest:preview.value.digest});dialog.value='';await load();UiMessage.success('排班已导入')}catch(exception){notifyError(exception)}finally{saving.value=false}}
onMounted(load);onBeforeUnmount(()=>generation++)
</script>
<template>
 <section class="duty-panel">
  <div class="duty-toolbar"><div class="roster-filters"><input v-model="month" class="duty-native" type="month" aria-label="排班月份"/><ui-select v-model="stationId" filterable clearable placeholder="全部岗位"><ui-option v-for="station in catalog.stations" :key="station.id" :value="station.id" :label="station.name"/></ui-select></div><div class="duty-actions"><ui-button :loading="loading" @click="load"><RefreshCw/>刷新</ui-button><template v-if="manage"><ui-button @click="dialog='import';preview=null"><Upload/>导入</ui-button><ui-button @click="setForm('generate')"><CalendarDays/>批量生成</ui-button><ui-button type="primary" @click="setForm('edit')"><Plus/>添加排班</ui-button></template></div></div>
  <p class="duty-hint">计划时间与实际到岗分别保存。日历显示整月排班，共 {{total}} 条；通过下方分页浏览。发布前核对人员、时间冲突、岗位覆盖及设备授权。</p>
  <div v-if="error" class="duty-card" role="alert">{{error}} <ui-button @click="load">重试</ui-button></div>
  <div class="roster-calendar" aria-label="排班日历"><div v-for="weekday in ['一','二','三','四','五','六','日']" :key="weekday" class="roster-week">{{weekday}}</div><div v-for="(day,index) in calendar" :key="day.date || index" class="roster-day" :class="{'is-empty':!day.date,'is-today':day.date===localDate()}"><span v-if="day.date">{{Number(day.date.slice(-2))}}</span><button v-for="row in day.items" :key="row.id" type="button" class="roster-chip" @click="history=row;dialog='history'"><strong>{{catalog.stationName(row.stationId)}}</strong><small>{{new Date(row.startAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}} · {{statusText(row.status)}}</small></button></div></div>
  <DataTableCard :title="`排班 · ${total} 条`" :total="total" :page="page" :page-size="pageSize" @update:page="page=$event" @update:page-size="pageSize=$event">
   <div class="roster-mobile-list" v-loading="loading"><article v-for="row in pagedRows" :key="row.id" class="roster-mobile-card"><div class="duty-row"><strong>{{catalog.stationName(row.stationId)}}</strong><ui-tag>{{statusText(row.status)}}</ui-tag></div><p>{{dutyTime(row.startAt)}}<br/>至 {{dutyTime(row.endAt)}}</p><p class="duty-meta">{{(row.memberIds || []).map(catalog.userName).join('、')}}<br/>负责人：{{catalog.userName(row.leaderId)}}</p><div class="duty-actions"><ui-button size="small" @click="history=row;dialog='history'">详情</ui-button><template v-if="manage && row.status!=='CANCELLED'"><ui-button size="small" @click="setForm('edit',row)">调整</ui-button><ui-button size="small" @click="validate(row)">检查</ui-button><ui-button v-if="row.status==='DRAFT'" size="small" type="primary" :disabled="saving" @click="publish(row)">发布</ui-button><ui-button size="small" type="danger" plain @click="cancel(row)">取消</ui-button></template></div></article><ui-empty v-if="!loading && !pagedRows.length" description="本月暂无排班"/></div>
   <ui-table class="roster-desktop-table" v-loading="loading" :data="pagedRows" empty-text="本月暂无排班">
    <ui-table-column label="岗位" min-width="130"><template #default="{row}">{{catalog.stationName(row.stationId)}}</template></ui-table-column>
    <ui-table-column label="完整起止时间" min-width="230"><template #default="{row}">{{dutyTime(row.startAt)}}<br/>{{dutyTime(row.endAt)}}</template></ui-table-column>
    <ui-table-column label="当班人员" min-width="140"><template #default="{row}">{{(row.memberIds || []).map(catalog.userName).join('、')}}<small class="duty-label">负责人：{{catalog.userName(row.leaderId)}}</small></template></ui-table-column>
    <ui-table-column label="状态" width="100"><template #default="{row}"><ui-tag>{{statusText(row.status)}}</ui-tag></template></ui-table-column>
    <ui-table-column label="操作" min-width="240" fixed="right"><template #default="{row}"><ui-button text size="small" @click="history=row;dialog='history'">详情</ui-button><template v-if="manage && row.status!=='CANCELLED'"><ui-button text size="small" @click="setForm('edit',row)">调整</ui-button><ui-button text size="small" @click="validate(row)">检查</ui-button><ui-button v-if="row.status==='DRAFT'" text type="primary" size="small" :disabled="saving" @click="publish(row)">发布</ui-button><ui-button text type="danger" size="small" @click="cancel(row)">取消</ui-button></template></template></ui-table-column>
   </ui-table>
  </DataTableCard>
 </section>
 <ui-dialog :model-value="['edit','generate','cancel'].includes(dialog)" :title="dialog==='generate'?'批量生成排班':dialog==='cancel'?'取消排班':form.id?'调整排班':'添加排班'" :close-on-click-modal="false" @close="dialog=''">
  <ui-form class="duty-form" label-position="top" :disabled="saving"><template v-if="dialog!=='cancel'">
   <ui-form-item label="值班岗位" required><ui-select v-model="form.stationId" filterable><ui-option v-for="station in catalog.stations.filter(s=>s.enabled)" :key="station.id" :value="station.id" :label="station.name"/></ui-select></ui-form-item>
   <div class="duty-grid"><ui-form-item label="班次模板"><ui-select v-model="form.templateId" clearable @change="setTemplate"><ui-option v-for="template in catalog.templates" :key="template.id" :value="template.id" :label="template.name"/></ui-select></ui-form-item><ui-form-item label="班组"><ui-select v-model="form.teamId" clearable @change="selectTeam"><ui-option v-for="team in catalog.teams" :key="team.id" :value="team.id" :label="team.name"/></ui-select></ui-form-item></div>
   <div v-if="dialog==='generate'" class="duty-grid"><ui-form-item label="起始日期"><input v-model="form.from" class="duty-native" type="date"/></ui-form-item><ui-form-item label="结束日期（包含）"><input v-model="form.to" class="duty-native" type="date"/></ui-form-item></div>
   <div v-else class="duty-grid"><ui-form-item label="计划开始时间"><ui-date-time v-model="form.startAt"/></ui-form-item><ui-form-item label="计划结束时间"><ui-date-time v-model="form.endAt"/></ui-form-item></div>
   <ui-form-item label="当班人员" required><DutyUserSelect v-model="form.memberIds" :users="catalog.users" multiple/></ui-form-item><ui-form-item label="交接负责人" required><DutyUserSelect v-model="form.leaderId" :users="catalog.users.filter(user=>form.memberIds.includes(user.username))"/></ui-form-item>
  </template><ui-form-item v-if="form.id || dialog==='cancel'" label="调整 / 取消原因" required><ui-input v-model="form.reason" type="textarea" :rows="3"/></ui-form-item></ui-form>
  <template #footer><ui-button :disabled="saving" @click="dialog=''">关闭</ui-button><ui-button type="primary" :loading="saving" @click="dialog==='cancel'?applyCancel():save()">{{dialog==='generate'?'生成草稿':dialog==='cancel'?'确认取消':'保存'}}</ui-button></template>
 </ui-dialog>
 <ui-dialog :model-value="dialog==='import'" title="导入老系统排班" width="min(850px,94vw)" :close-on-click-modal="false" @close="dialog=''">
  <div class="duty-details"><p class="duty-hint">CSV 表头：stationId,startAt,endAt,memberIds,leaderId,sourceId。时间使用带时区 ISO 日期时间或毫秒时间戳；成员以分号分隔。导入只保存计划，不生成到岗或签收。</p><details class="duty-import-map"><summary>查看导入标识对照</summary><p v-for="station in catalog.stations" :key="station.id">岗位：{{station.name}} · {{station.id}}</p><p v-for="user in catalog.users" :key="user.username">人员：{{user.displayName || user.username}} · {{user.username}}</p></details><input type="file" accept=".csv,text/csv" aria-label="上传排班CSV" @change="fileCSV"/><ui-input v-model="importCSV" type="textarea" :rows="6" placeholder="粘贴 CSV 内容" @input="preview=null"/><ui-button :loading="saving" @click="importPreview">预览并检查</ui-button><template v-if="preview"><ui-alert v-if="preview.problems?.length" type="error" :closable="false" title="发现问题，请修正后重新预览"><p v-for="(problem,index) in preview.problems" :key="index">第 {{problem.row}} 行：{{problem.message}}</p></ui-alert><ui-alert v-else type="success" :closable="false" :title="`检查通过，将导入 ${preview.rows?.length || 0} 条排班`"/><ui-table :data="preview.rows || []"><ui-table-column label="岗位"><template #default="{row}">{{catalog.stationName(row.stationId)}}</template></ui-table-column><ui-table-column label="时间"><template #default="{row}">{{dutyTime(row.startAt)}} — {{dutyTime(row.endAt)}}</template></ui-table-column><ui-table-column prop="leaderId" label="负责人"/></ui-table></template></div>
  <template #footer><ui-button @click="dialog=''">关闭</ui-button><ui-button type="primary" :loading="saving" :disabled="!preview?.digest || !!preview?.problems?.length" @click="importRows">确认导入</ui-button></template>
 </ui-dialog>
 <ui-dialog :model-value="dialog==='validate'||dialog==='history'" :title="dialog==='validate'?'发布检查':'排班详情及变更历史'" @close="dialog=''">
  <div v-if="history" class="duty-details"><div>{{catalog.stationName(history.stationId)}} · {{statusText(history.status)}}<p>{{dutyTime(history.startAt)}} — {{dutyTime(history.endAt)}}</p><p>负责人：{{catalog.userName(history.leaderId)}}；版本 {{history.version}}</p></div><template v-if="dialog==='validate'"><ui-alert v-if="validation?.problems?.length" type="error" :closable="false" title="需要处理的问题"><p v-for="(problem,index) in validation.problems" :key="index">{{problem.message || problem}}</p></ui-alert><ui-alert v-else type="success" :closable="false" title="人员与时间冲突检查通过"/><ui-alert v-if="validation?.gaps?.length" type="warning" :closable="false" title="岗位责任时间存在缺口"><p v-for="(gap,index) in validation.gaps" :key="index">{{dutyTime(gap.startAt)}} — {{dutyTime(gap.endAt)}}</p></ui-alert></template><div v-for="(change,index) in history.history || []" :key="index" class="duty-card"><span class="duty-meta">{{dutyTime(change.at)}} · {{catalog.userName(change.actorId)}}</span><p>{{change.reason}}</p><p v-if="change.previous">原安排：{{dutyTime(change.previous.startAt)}} — {{dutyTime(change.previous.endAt)}} · {{(change.previous.memberIds || []).map(catalog.userName).join('、')}}</p></div><p v-if="history.source" class="duty-meta">来源：{{history.source}} · {{history.sourceId}} · 导入批次 {{history.importBatchId || '—'}}</p></div>
 </ui-dialog>
</template>
<style scoped>
.roster-filters{display:flex;gap:8px;flex:1;min-width:260px}.roster-filters input{width:150px}.roster-filters .ui-select{max-width:250px}.roster-calendar{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:1px;background:var(--border);border:1px solid var(--border);border-radius:8px;overflow:hidden}.roster-week{background:var(--surface-muted);padding:8px;text-align:center;font-size:12px;color:var(--text-muted)}.roster-day{background:var(--surface);min-height:90px;padding:8px;min-width:0}.roster-day>span{font-size:12px;color:var(--text-muted)}.roster-day.is-today>span{color:var(--primary);font-weight:600}.roster-day.is-empty{background:var(--surface-muted)}.roster-chip{width:100%;text-align:left;display:grid;gap:3px;border:0;border-left:2px solid var(--primary);padding:5px;margin-top:5px;border-radius:4px;background:var(--surface-muted);color:var(--text);cursor:pointer;overflow:hidden}.roster-chip strong,.roster-chip small{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:11px;font-weight:400}.roster-mobile-list{display:none}.roster-mobile-card{padding:14px;min-width:0;border-bottom:1px solid var(--border)}.roster-mobile-card strong,.roster-mobile-card p{overflow-wrap:anywhere}.roster-mobile-card p{font-size:13px;line-height:1.6;margin:8px 0}.roster-mobile-card:last-child{border:0}@media(max-width:640px){.roster-calendar,.roster-desktop-table{display:none}.roster-mobile-list{display:grid}.roster-filters{min-width:0;flex-basis:100%;flex-wrap:wrap}.roster-filters .ui-select{max-width:none;flex:1}.roster-filters input{width:130px}}
</style>
