<script setup>
import {computed,onBeforeUnmount,onMounted,reactive,ref,watch} from 'vue'
import {Download,RefreshCw,Sparkles} from '@lucide/vue'
import {dutyDoc,dutyPDF,dutyEventsCSV,dutyRead,dutyWrite} from '../../duty/api.js'
import {dutyTime,handoverActionPayload,isAIRunning,statusText,dutyActionKey,clearDutyActionKey} from '../../duty/state.js'
import {notifyError,session} from '../../api.js'
import {can} from '../../permissions.js'
import {UiMessage} from '../../ui/feedback.js'
import {alarmLevel,alarmType,alarmStatuses,label} from '../../labels.js'
import DataTableCard from '../layout/DataTableCard.vue'
import DutyItems from './DutyItems.vue'
const props=defineProps({catalog:Object,openId:String})
const emit=defineEmits(['clear-open','navigate'])
const outgoingRun=ref(null),outgoingRoster=ref(null),incomingRoster=ref(null),incomingRun=ref(null),basicError=ref('')
const status=ref(''),station=ref(''),rows=ref([]),total=ref(0),page=ref(1),pageSize=ref(20),loading=ref(false),error=ref(''),detail=ref(null),revisions=ref([]),selectedRevision=ref(''),revision=ref(null),delta=ref(null),job=ref(null),detailLoading=ref(false),saving=ref(false),humanNotes=ref(''),edited=ref(false),acknowledged=ref(false),action=ref(''),actionForm=reactive({reason:'',note:'',content:''}),eventPage=ref(1),eventItems=ref([]),eventTotal=ref(0),useKnowledge=ref(false),suggestionItems=ref(null)
let generation=0,detailGeneration=0,pollTimer=0,eventGeneration=0
const latest=computed(()=>selectedRevision.value===detail.value?.currentRevisionId),editable=computed(()=>latest.value && ['DRAFT','RETURNED'].includes(detail.value?.status)),running=computed(()=>isAIRunning(job.value)),cutoff=computed(()=>revision.value?.snapshot?.cutoffAt),deltaChanged=computed(()=>Boolean(delta.value?.changed || delta.value?.events?.length)),statsLabels={newAlarms:'新增告警',reports:'上报次数',acknowledged:'确认',recovered:'恢复',closed:'关闭',offline:'离线',online:'上线'}
async function load(){const token=++generation;loading.value=true;error.value='';try{const value=await dutyRead('handovers','','',{stationId:station.value,status:status.value,limit:pageSize.value,offset:(page.value-1)*pageSize.value});if(token!==generation)return;rows.value=value.items || [];total.value=value.total || 0}catch(exception){if(token===generation)error.value=exception.message}finally{if(token===generation)loading.value=false}}
watch([status,station,pageSize],()=>{page.value=1;load()});watch(page,load)
async function open(id){const token=++detailGeneration;detailLoading.value=true;detail.value=null;revision.value=null;job.value=null;delta.value=null;edited.value=false;acknowledged.value=false;clearTimeout(pollTimer);try{const [value,versions,jobs]=await Promise.all([dutyRead('handovers',id),dutyRead('revisions','','',{handoverId:id,limit:100}),can('action:duty:ai')?dutyRead('ai-jobs','','',{handoverId:id,limit:100}):Promise.resolve({items:[]})]);if(token!==detailGeneration)return;detail.value=value;revisions.value=versions.items || [];selectedRevision.value=value.currentRevisionId;job.value=(jobs.items || []).sort((a,b)=>b.createdAt-a.createdAt)[0] || null;await loadBasic(value,token);await loadRevision();await loadDelta();schedulePoll()}catch(exception){if(token===detailGeneration)notifyError(exception)}finally{if(token===detailGeneration)detailLoading.value=false}}
async function loadBasic(value,token){const canReadOutgoing=can(['action:duty:history','action:duty:settings','action:duty:roster']) || value.submission?.userId===session.user || ['DRAFT','RETURNED'].includes(value.status);const results=await Promise.allSettled([canReadOutgoing?dutyRead('runs',value.runId):Promise.resolve(null),dutyRead('rosters',value.nextRosterId),value.nextRunId?dutyRead('runs',value.nextRunId):Promise.resolve(null)]);if(token!==detailGeneration)return;const [run,next,received]=results.map(result=>result.status==='fulfilled'?result.value:null);outgoingRun.value=run;outgoingRoster.value=null;incomingRoster.value=next;incomingRun.value=received;basicError.value=results.some(result=>result.status==='rejected' && result.reason?.status!==403)?'补充班次资料加载失败，可关闭详情后重新打开。已冻结的交接事实仍可核对。':'';if(run?.rosterId){try{const previous=await dutyRead('rosters',run.rosterId);if(token===detailGeneration)outgoingRoster.value=previous}catch{/* A historical roster has its own authorization boundary. */}}}
function historicalDeviceName(id){const device=revision.value?.snapshot?.devices?.find(value=>(value.id || value.deviceId)===id);return device?.name || device?.deviceName || props.catalog.deviceName(id)}
async function loadRevision(){if(!selectedRevision.value)return;const id=selectedRevision.value;const token=detailGeneration;try{const value=await dutyRead('revisions',id);if(token!==detailGeneration || id!==selectedRevision.value)return;revision.value={...value,records:dutyDoc(value.records || []),items:dutyDoc(value.items || [])};humanNotes.value=value.humanNotes || '';edited.value=false;eventPage.value=1;await loadEvents()}catch(exception){notifyError(exception)}}
async function loadEvents(){if(!revision.value)return;const token=++eventGeneration;const id=revision.value.id;try{const value=await dutyRead('revisions',id,'events',{limit:20,offset:(eventPage.value-1)*20});if(token!==eventGeneration)return;eventItems.value=value.items || [];eventTotal.value=value.total || 0}catch(exception){if(token===eventGeneration)notifyError(exception)}}
watch(eventPage,loadEvents)
async function loadDelta(){if(!detail.value || detail.value.status==='ACCEPTED')return;const id=detail.value.id;const token=detailGeneration;try{const value=await dutyRead('handovers',id,'delta');if(token===detailGeneration && id===detail.value?.id){delta.value=value;acknowledged.value=false}}catch(exception){notifyError(exception)}}
function close(){detailGeneration++;eventGeneration++;clearTimeout(pollTimer);detail.value=null;revision.value=null;action.value='';emit('clear-open')}
function schedulePoll(){clearTimeout(pollTimer);if(!running.value || !detail.value)return;const token=detailGeneration;pollTimer=setTimeout(async()=>{if(token!==detailGeneration || !detail.value)return;try{const result=await dutyRead('ai-jobs',job.value.id);if(token!==detailGeneration)return;job.value=result;if(!isAIRunning(result)){const id=detail.value.id;const value=await dutyRead('handovers',id);if(token!==detailGeneration)return;detail.value=value;selectedRevision.value=value.currentRevisionId;const versions=await dutyRead('revisions','','',{handoverId:id,limit:100});if(token!==detailGeneration)return;revisions.value=versions.items || [];if(!edited.value)await loadRevision();await load();if(result.status==='SUCCEEDED')UiMessage.success('AI草稿已完成')}schedulePoll()}catch(exception){if(token===detailGeneration){job.value={...job.value,error:exception.message};schedulePoll()}}},1500)}
async function saveRevision(){if(saving.value || !detail.value)return;saving.value=true;try{const result=await dutyWrite('handovers',detail.value.id,'',{version:detail.value.version,humanNotes:humanNotes.value},'PUT');await open(result.id || detail.value.id);UiMessage.success('已保存新版本')}catch(exception){notifyError(exception)}finally{saving.value=false}}
async function startAI(){if(saving.value || !detail.value || running.value)return;saving.value=true;try{if(edited.value)throw Error('请先保存人工补充，再整理AI草稿');job.value=await dutyWrite('handovers',detail.value.id,'start-ai',{version:detail.value.version,revisionId:revision.value?.id,useKnowledge:useKnowledge.value});schedulePoll()}catch(exception){notifyError(exception)}finally{saving.value=false}}
async function stopAI(){if(!job.value || saving.value)return;saving.value=true;try{job.value=await dutyWrite('ai-jobs',job.value.id,'stop',{version:job.value.version});clearTimeout(pollTimer)}catch(exception){notifyError(exception)}finally{saving.value=false}}
function prepareAction(kind){action.value=kind;Object.assign(actionForm,{reason:'',note:'',content:'',idempotencyKey:dutyActionKey(globalThis.sessionStorage,session,detail.value.id,kind,detail.value.version)})}
async function completeAction(){if(saving.value || !detail.value)return;saving.value=true;try{if(edited.value)throw Error('人工补充尚未保存，请先保存版本');if(['return','void'].includes(action.value) && !actionForm.reason.trim())throw Error('请填写原因');if(action.value==='amend' && !actionForm.content.trim())throw Error('请填写补充内容');if(['submit','accept'].includes(action.value) && deltaChanged.value && !acknowledged.value)throw Error('请先核对并勾选最新变化');const id=detail.value.id;await dutyWrite('handovers',id,action.value,handoverActionPayload(detail.value,revision.value,delta.value,{...actionForm,humanNotes:humanNotes.value,acknowledgedChanges:acknowledged.value}));clearDutyActionKey(globalThis.sessionStorage,session,id,action.value,detail.value.version);action.value='';await open(id);await load();UiMessage.success('交接状态已更新')}catch(exception){notifyError(exception);if(exception.status===409 && detail.value){await open(detail.value.id)}}finally{saving.value=false}}
async function downloadPDF(){try{await dutyPDF(detail.value.id,revision.value.id)}catch(exception){notifyError(exception)}}
function navigateEvidence(evidence){if(evidence.type?.includes('alarm'))emit('navigate','alarms',{alarmId:evidence.id,deviceId:evidence.deviceId});else if(evidence.deviceId)emit('navigate','devices',{deviceId:evidence.deviceId})}
watch(()=>props.openId,value=>{if(value)open(value)})
onMounted(()=>{load();if(props.openId)open(props.openId)});onBeforeUnmount(()=>{generation++;detailGeneration++;eventGeneration++;clearTimeout(pollTimer)})
</script>
<template>
 <section class="duty-panel">
  <div class="duty-toolbar"><div class="handover-filters"><ui-select v-model="station" clearable filterable placeholder="全部岗位"><ui-option v-for="value in catalog.stations" :key="value.id" :value="value.id" :label="value.name"/></ui-select><ui-select v-model="status" clearable placeholder="全部状态"><ui-option v-for="value in ['DRAFT','SUBMITTED','RETURNED','ACCEPTED','VOID']" :key="value" :value="value" :label="statusText(value)"/></ui-select></div><ui-button :loading="loading" @click="load"><RefreshCw/>刷新</ui-button></div>
  <DataTableCard :title="`交接记录 · ${total} 条`" :total="total" :page="page" :page-size="pageSize" :error="error" @retry="load" @update:page="page=$event" @update:page-size="pageSize=$event">
   <ui-table v-loading="loading" :data="rows" empty-text="暂无交接。在我的值班中准备交接草稿。"><ui-table-column label="岗位" min-width="140"><template #default="{row}">{{catalog.stationName(row.stationId)}}</template></ui-table-column><ui-table-column label="状态 / 版本" min-width="140"><template #default="{row}"><ui-tag>{{statusText(row.status)}}</ui-tag> · 第 {{row.revisionNumber}} 版</template></ui-table-column><ui-table-column label="交班" min-width="190"><template #default="{row}">{{catalog.userName(row.submission?.userId)}}<br/>{{dutyTime(row.submission?.at)}}</template></ui-table-column><ui-table-column label="接班" min-width="190"><template #default="{row}">{{catalog.userName(row.acceptance?.userId)}}<br/>{{dutyTime(row.acceptance?.at)}}</template></ui-table-column><ui-table-column label="操作" width="100" fixed="right"><template #default="{row}"><ui-button text type="primary" @click="open(row.id)">查看详情</ui-button></template></ui-table-column></ui-table>
  </DataTableCard>
 </section>
 <ui-dialog :model-value="!!detail || detailLoading" title="值班交接" width="min(1120px,94vw)" :close-on-click-modal="false" @close="close">
  <ui-skeleton v-if="detailLoading" :rows="6" animated/>
  <div v-else-if="detail && revision" class="duty-details">
   <div class="duty-toolbar"><div><strong>{{catalog.stationName(detail.stationId)}}</strong> <ui-tag>{{statusText(detail.status)}}</ui-tag><p class="duty-meta">本班 {{dutyTime(revision.startAt)}}；数据截止 {{dutyTime(cutoff)}}（截至该时已入库的数据）</p></div><ui-select v-model="selectedRevision" class="revision-select" @change="loadRevision"><ui-option v-for="value in revisions" :key="value.id" :value="value.id" :label="`第 ${value.number} 版 · ${dutyTime(value.createdAt)}`"/></ui-select></div>
   <ui-alert v-if="!latest" type="info" :closable="false" title="正在查看历史版本，签收和编辑仅作用于当前版本。"/>
   <ui-alert v-if="basicError" type="warning" :closable="false" :title="basicError"/><section class="duty-card"><h3>班次与实际值班</h3><div class="duty-grid"><div><span class="duty-label">交班安排</span><p v-if="outgoingRoster">{{dutyTime(outgoingRoster.startAt)}} — {{dutyTime(outgoingRoster.endAt)}}</p><p v-else>冻结事实中的实际开始：{{dutyTime(revision.startAt)}}</p><p v-if="outgoingRun">负责人：{{catalog.userName(outgoingRun.leaderId)}}；当班 {{(outgoingRun.memberIds || []).map(catalog.userName).join('、')}}</p><p v-else>交班确认人：{{catalog.userName(detail.submission?.userId)}}</p><p v-if="outgoingRun" class="duty-meta">实际责任：{{dutyTime(outgoingRun?.startedAt)}} — {{outgoingRun?.endedAt?dutyTime(outgoingRun.endedAt):'仍在当班'}}</p></div><div><span class="duty-label">接班安排</span><p>{{dutyTime(incomingRoster?.startAt)}} — {{dutyTime(incomingRoster?.endAt)}}</p><p>负责人：{{catalog.userName(incomingRoster?.leaderId)}}；计划 {{(incomingRoster?.memberIds || []).map(catalog.userName).join('、')}}</p><p v-if="incomingRun" class="duty-meta">实际接班 {{dutyTime(incomingRun.startedAt)}}</p></div></div><details><summary>实际到岗与离岗记录</summary><p v-for="(attendance,index) in [...(outgoingRun?.attendance || []),...(incomingRun?.attendance || [])]" :key="index" class="duty-meta">{{catalog.userName(attendance.userId)}} · 到岗 {{dutyTime(attendance.arrivedAt)}} · 离岗 {{dutyTime(attendance.leftAt)}} {{attendance.reason || ''}}</p></details></section>
   <section v-if="detail.acceptanceRevisionId" class="duty-card"><div class="duty-toolbar"><div><h3>接收时事实补充</h3><p class="duty-hint">接收时的新事件与未完成事项另行冻结，原交班版本继续保留。</p></div><ui-button size="small" @click="selectedRevision=detail.acceptanceRevisionId;loadRevision()">查看接收事实版本</ui-button></div></section>
   <section class="duty-card"><h3>本班事实概况</h3><div class="handover-stats"><div v-for="(name,key) in statsLabels" :key="key"><strong>{{revision.statistics?.[key] || 0}}</strong><span>{{name}}</span></div></div><p class="duty-hint">新增告警条数和上报次数分别统计。以下结构化清单始终保留，不受AI摘要影响。</p></section>
   <section class="duty-card"><h3>截止时未解除的告警</h3><div class="duty-table-scroll"><table class="duty-snapshot-table"><thead><tr><th>设备</th><th>内容 / 类型</th><th>等级 / 状态</th><th>最近触发</th><th>证据</th></tr></thead><tbody><tr v-for="alarm in revision.snapshot?.alarms || []" :key="alarm.id || alarm.alarmId"><td>{{alarm.deviceName || historicalDeviceName(alarm.deviceId)}}</td><td>{{alarm.details?.description || alarm.details?.content || alarm.description || alarm.message || alarm.content || alarmType(alarm.alarmType)}}</td><td>{{alarmLevel(alarm.alarmLevel || alarm.level)}} · {{label(alarmStatuses,alarm.status)}}</td><td>{{dutyTime(alarm.lastTriggeredAt || alarm.triggeredAt)}}</td><td><ui-button text size="small" @click="emit('navigate','alarms',{alarmId:alarm.id || alarm.alarmId,deviceId:alarm.deviceId})">查看告警</ui-button></td></tr><tr v-if="!revision.snapshot?.alarms?.length"><td colspan="5">暂无未解除告警</td></tr></tbody></table></div></section>
   <section class="duty-card"><h3>设备状态快照</h3><div class="duty-table-scroll"><table class="duty-snapshot-table"><thead><tr><th>设备</th><th>状态</th><th>最近上报</th></tr></thead><tbody><tr v-for="state in revision.snapshot?.states || []" :key="state.deviceId"><td>{{historicalDeviceName(state.deviceId)}}</td><td>{{statusText(state.connectionStatus || state.onlineStatus || state.status)}} · {{statusText(state.businessStatus)}}</td><td>{{dutyTime(state.lastSeenAt || state.updatedAt)}}</td></tr><tr v-if="!revision.snapshot?.states?.length"><td colspan="3">暂无状态记录</td></tr></tbody></table></div></section>
   <section class="duty-card"><h3>未完成事项 · {{revision.items?.length || 0}} 条</h3><div class="duty-table-scroll"><table class="duty-snapshot-table"><thead><tr><th>事项</th><th>当前进展 / 下一步</th><th>主责人</th><th>期限</th></tr></thead><tbody><tr v-for="item in revision.items || []" :key="item.id"><td>{{item.title}}<small class="duty-label">{{statusText(item.status)}}</small></td><td>{{item.nextAction}}</td><td>{{catalog.userName(item.ownerId)}}</td><td>{{dutyTime(item.dueAt)}}</td></tr><tr v-if="!revision.items?.length"><td colspan="4">暂无未完成事项</td></tr></tbody></table></div></section>
   <section class="duty-card"><h3>当班人工处置记录</h3><article v-for="record in revision.records || []" :key="record.id" class="handover-record"><span class="duty-meta">{{dutyTime(record.occurredAt)}} · {{catalog.userName(record.authorId)}}</span><p>{{record.content}}</p><p v-if="record.correctionReason" class="duty-meta">更正说明：{{record.correctionReason}}</p></article><p v-if="!revision.records?.length" class="duty-hint">暂无人工处置记录。</p></section>
   <section class="duty-card"><div class="duty-toolbar"><h3>人工补充</h3><ui-button v-if="editable && can('action:duty:handover')" type="primary" size="small" :loading="saving" :disabled="running" @click="saveRevision">{{deltaChanged?'更新事实并保存新版本':'保存新版本'}}</ui-button></div><ui-input v-model="humanNotes" type="textarea" :rows="4" :disabled="!editable || !can('action:duty:handover') || running" placeholder="补充现场情况、联系结果和临时注意事项" @input="edited=true"/><p v-if="edited" class="duty-hint">有未保存的人工补充。</p></section>
   <section class="duty-card"><div class="duty-toolbar"><h3>AI整理</h3><div class="duty-actions"><ui-button v-if="editable && can('action:duty:ai') && !running" size="small" :loading="saving" @click="startAI"><Sparkles/>{{job?.status==='FAILED'?'重试整理':'AI整理交接'}}</ui-button><ui-button v-if="running && can('action:duty:ai')" size="small" :loading="saving" @click="stopAI">停止</ui-button></div></div><ui-checkbox v-if="editable && can('action:duty:ai')" v-model="useKnowledge" :disabled="running">结合已授权的值班规范与设备手册</ui-checkbox><p v-if="job" class="duty-meta">{{statusText(job.status)}} · {{statusText(job.stage)}}<span v-if="job.model"> · {{job.model}}</span></p><ui-alert v-if="job?.error" type="warning" :closable="false" :title="job.error"/><p v-if="!revision.ai" class="duty-hint">AI草稿尚未生成。可以直接核对事实并手工交接。</p><template v-else><p class="handover-summary">{{revision.ai.summary}}</p><ui-alert v-if="revision.ai.truncated" type="info" :closable="false" :title="`AI本次阅读 ${revision.ai.inputCount} / ${revision.ai.totalCount} 条证据，完整事实以结构化清单及事件明细为准。`"/><section v-for="section in [{key:'highlights',name:'重点说明'},{key:'suggestions',name:'后续建议'},{key:'missing',name:'缺项提示'}]" :key="section.key" class="ai-section"><h4>{{section.name}}</h4><article v-for="(statement,index) in revision.ai[section.key] || []" :key="index"><p>{{statement.text}}</p><ui-button v-if="section.key==='suggestions' && can('action:duty:item') && latest && !['VOID','SUBMITTED'].includes(detail.status)" size="small" @click="suggestionItems?.edit({title:statement.text.slice(0,80),nextAction:statement.text,ownerId:''},'edit')">核对并创建跟进事项</ui-button><div class="duty-tags"><ui-button v-for="evidenceId in statement.evidenceIds || []" :key="evidenceId" text size="small" @click="navigateEvidence(revision.evidence?.find(value=>value.id===evidenceId) || {})">{{revision.evidence?.find(value=>value.id===evidenceId)?.label || '证据'}}</ui-button></div></article></section></template></section>
   <section v-if="delta && detail.status!=='ACCEPTED' && latest" class="duty-card"><div class="duty-toolbar"><h3>草稿生成后的变化</h3><ui-button size="small" @click="loadDelta"><RefreshCw/>核对最新</ui-button></div><p v-if="!deltaChanged" class="duty-hint">本次核对没有新增变化。</p><template v-else><p class="duty-hint">请核对新增事件及事项变化。提交和接收将绑定本次核对的事实版本。</p><div v-for="event in delta.events || []" :key="event.id" class="handover-record"><span class="duty-meta">{{dutyTime(event.occurredAt)}} · {{statusText(event.type)}} · {{historicalDeviceName(event.deviceId)}}</span><p>{{event.body?.content || event.body?.description || event.body?.title || event.type}}</p></div><p v-if="editable" class="duty-hint">提交前请点击“更新事实并保存新版本”，将最新变化纳入交班版本。</p><ui-checkbox v-model="acknowledged">已核对最新变化</ui-checkbox></template></section>
   <div class="duty-actions"><ui-button v-if="can('action:duty:export')" size="small" @click="dutyEventsCSV(revision.id).catch(notifyError)"><Download/>导出完整事件 CSV</ui-button></div><DataTableCard title="完整事件明细" :total="eventTotal" :page="eventPage" :page-size="20" :page-sizes="[]" @update:page="eventPage=$event"><ui-table :data="eventItems"><ui-table-column label="发生 / 入库" min-width="200"><template #default="{row}">{{dutyTime(row.occurredAt)}}<br/><small>{{dutyTime(row.recordedAt)}}</small></template></ui-table-column><ui-table-column label="事件" min-width="150"><template #default="{row}">{{statusText(row.type)}}<br/>{{historicalDeviceName(row.deviceId)}}</template></ui-table-column><ui-table-column label="内容" min-width="230"><template #default="{row}">{{row.body?.content || row.body?.description || row.body?.title || row.body?.alarmType || '系统状态变化'}}</template></ui-table-column></ui-table></DataTableCard>
   <section class="duty-card"><h3>双方确认</h3><p>交班：{{catalog.userName(detail.submission?.userId)}} · {{dutyTime(detail.submission?.at)}}</p><p>接班：{{catalog.userName(detail.acceptance?.userId)}} · {{dutyTime(detail.acceptance?.at)}}</p><p v-if="detail.returnReason">退回原因：{{detail.returnReason}}</p><p v-if="detail.voidReason">作废原因：{{detail.voidReason}}</p><p class="duty-hint">每次确认固定精确版本和截止事实。后续变化通过补充记录保存。</p></section>
   <section v-if="detail.amendments?.length" class="duty-card"><h3>后续补充及更正</h3><article v-for="amendment in detail.amendments" :key="amendment.id" class="handover-record"><span class="duty-meta">{{dutyTime(amendment.at)}} · {{catalog.userName(amendment.actorId)}}</span><p>{{amendment.content}}</p></article></section>
  </div>
  <template #footer><div class="duty-actions"><ui-button @click="close">关闭</ui-button><ui-button v-if="revision && can('action:duty:export')" @click="downloadPDF"><Download/>PDF</ui-button><template v-if="detail && latest"><ui-button v-if="detail.status==='ACCEPTED' && can('action:duty:handover')" @click="prepareAction('amend')">补充记录</ui-button><ui-button v-if="editable && can('action:duty:handover')" type="primary" :disabled="edited || running" @click="prepareAction('submit')">核对并提交交班</ui-button><ui-button v-if="detail.status==='SUBMITTED' && can('action:duty:accept')" @click="prepareAction('return')">退回修改</ui-button><ui-button v-if="detail.status==='SUBMITTED' && can('action:duty:accept')" type="primary" @click="prepareAction('accept')">确认接收并接班</ui-button><ui-button v-if="['DRAFT','RETURNED','SUBMITTED'].includes(detail.status) && can('action:duty:handover')" type="danger" plain @click="prepareAction('void')">作废</ui-button></template></div></template>
 </ui-dialog>
 <DutyItems v-if="detail" ref="suggestionItems" :catalog="catalog" :run-id="detail.status==='ACCEPTED'?detail.nextRunId:detail.runId" :station-id="detail.stationId" dialog-only/>
 <ui-dialog :model-value="!!action" :title="({submit:'提交交班确认',accept:'接班确认',return:'退回修改',void:'作废交接',amend:'追加补充记录'})[action] || ''" width="min(550px,94vw)" :close-on-click-modal="false" @close="action=''">
  <ui-form label-position="top" :disabled="saving"><ui-form-item v-if="action==='return'||action==='void'" label="原因" required><ui-input v-model="actionForm.reason" type="textarea" :rows="3"/></ui-form-item><ui-form-item v-else-if="action==='amend'" label="补充内容 / 更正说明" required><ui-input v-model="actionForm.content" type="textarea" :rows="4"/></ui-form-item><template v-else><p>确认第 {{revision?.number}} 版。数据截止 {{dutyTime(cutoff)}}。</p><p v-if="action==='accept'" class="duty-hint">确认后结束旧班，开始接班排班并接续未完成事项。</p><ui-form-item label="确认备注（选填）"><ui-input v-model="actionForm.note" type="textarea" :rows="3"/></ui-form-item></template></ui-form>
  <template #footer><ui-button :disabled="saving" @click="action=''">取消</ui-button><ui-button type="primary" :loading="saving" @click="completeAction">确认</ui-button></template>
 </ui-dialog>
</template>
<style scoped>.handover-filters{display:flex;gap:8px;flex:1;min-width:0}.handover-filters>*{max-width:260px;min-width:150px}.revision-select{width:280px}.handover-stats{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:12px}.handover-stats>div{display:grid;gap:5px;text-align:center}.handover-stats strong{font-size:21px;font-weight:600}.handover-stats span{font-size:12px;color:var(--text-muted)}.handover-record{padding:10px 0;border-bottom:1px solid var(--border)}.handover-record:last-child{border:0}.handover-record p,.handover-summary,.ai-section p{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px;line-height:1.7}.ai-section h4{font-size:13px;margin:14px 0 7px}.ai-section article{padding:6px 0;border-bottom:1px solid var(--border)}@media(max-width:640px){.handover-filters{flex-basis:100%;flex-wrap:wrap}.handover-filters>*{flex:1;min-width:120px;max-width:none}.revision-select{width:100%}.handover-stats{grid-template-columns:repeat(4,minmax(0,1fr))}}</style>
