<script setup>
import {computed,onBeforeUnmount,onMounted,reactive,ref,watch} from 'vue'
import {Plus,RefreshCw,Download,ClipboardCheck} from '@lucide/vue'
import {dutyRead,dutyWrite,dutyAttachment,uploadDutyAttachments} from '../../duty/api.js'
import {dutyTime,statusText} from '../../duty/state.js'
import {notifyError,session} from '../../api.js'
import {can} from '../../permissions.js'
import {UiMessage} from '../../ui/feedback.js'
import {createClientId} from '../../clientId.js'
import DutyUserSelect from './DutyUserSelect.vue'
import DutyItems from './DutyItems.vue'
const props=defineProps({catalog:Object})
const emit=defineEmits(['handover'])
const runs=ref([]),rosters=ref([]),records=ref([]),notices=ref([]),handoverQueue=ref([]),runId=ref(''),loading=ref(false),error=ref(''),dialog=ref(''),saving=ref(false),form=reactive({}),files=ref([])
let generation=0,pollTimer=0,recordGeneration=0
const current=computed(()=>runs.value.find(run=>run.id===runId.value)),planned=computed(()=>rosters.value.filter(row=>row.status==='PUBLISHED' && row.memberIds?.includes(session.user)))
async function load(silent=false){const token=++generation;if(!silent)loading.value=true;error.value='';try{const [active,plans,notifications,queue]=await Promise.all([dutyRead('runs','','',{status:'ACTIVE',limit:100,userId:session.user}),dutyRead('rosters','','',{status:'PUBLISHED',start:Date.now()-86400e3,end:Date.now()+3*86400e3,limit:100}),dutyRead('notifications','','',{limit:20,userId:session.user}),dutyRead('handovers','','',{status:'SUBMITTED',limit:100})]);if(token!==generation)return;runs.value=active.items || [];rosters.value=plans.items || [];notices.value=notifications.items || [];handoverQueue.value=queue.items || [];if(!runs.value.some(run=>run.id===runId.value))runId.value=runs.value[0]?.id || '';await loadRecords(token)}catch(exception){if(token===generation)error.value=exception.message}finally{if(token===generation){loading.value=false;clearTimeout(pollTimer);pollTimer=setTimeout(()=>load(true),30000)}}}
async function loadRecords(token=generation){const request=++recordGeneration;if(!runId.value){records.value=[];return}try{const value=await dutyRead('records','','',{runId:runId.value,limit:100});if(token===generation && request===recordGeneration)records.value=value.items || []}catch(exception){if(token===generation)error.value=exception.message}}
watch(runId,()=>loadRecords())
function open(kind,value){dialog.value=kind;files.value=[];for(const key of Object.keys(form))delete form[key];Object.assign(form,{idempotencyKey:createClientId(),rosterId:'',runId:current.value?.id || '',stationId:current.value?.stationId || '',content:'',deviceId:'',alarmId:'',itemId:'',occurredAt:Date.now(),attachments:[],reason:'',correctionReason:'',userId:session.user,replacementId:'',nextRosterId:''},value || {})}
async function perform(){if(saving.value)return;saving.value=true;try{if(['record','correct'].includes(dialog.value)){if(!form.content.trim())throw Error('请填写处置内容');if(dialog.value==='correct' && !form.correctionReason.trim())throw Error('请填写更正原因');const uploaded=await uploadDutyAttachments(files.value,form.runId);form.attachments=[...(form.attachments || []),...uploaded];files.value=[];await dutyWrite('records',dialog.value==='correct'?form.id:'',dialog.value==='correct'?'correct':'',{...form,attachments:form.attachments})}else if(dialog.value==='handover'){if(!form.nextRosterId)throw Error('请选择接班排班');const result=await dutyWrite('handovers','','',{runId:current.value.id,nextRosterId:form.nextRosterId,idempotencyKey:form.idempotencyKey});dialog.value='';emit('handover',result.id);return}else{if(['open','end','substitute'].includes(dialog.value) && !form.reason.trim())throw Error('请填写原因');const operation=dialog.value;const value={...form,version:current.value?.version};await dutyWrite('runs',['arrive','open'].includes(operation)?'':current.value?.id,operation,value)}dialog.value='';await load();UiMessage.success('已保存')}catch(exception){notifyError(exception)}finally{saving.value=false}}
function pickFiles(event){files.value=Array.from(event.target.files || []);event.target.value=''}
async function markRead(notice){try{await dutyWrite('notifications',notice.id,'read',{version:notice.version});await load(true)}catch(exception){notifyError(exception)}}
onMounted(load);onBeforeUnmount(()=>{generation++;recordGeneration++;clearTimeout(pollTimer)})
</script>
<template>
 <section class="duty-panel">
  <div class="duty-toolbar"><h2 class="current-title">当前与即将开始的值班</h2><div class="duty-actions"><ui-button :loading="loading" @click="load"><RefreshCw/>刷新</ui-button><ui-button v-if="can('action:duty:participate')" @click="open('arrive')">到岗记录</ui-button><ui-button v-if="can('action:duty:participate')" @click="open('open')">首次开班</ui-button></div></div>
  <ui-alert v-if="error" type="error" :closable="false" :title="error"/>
  <div v-if="notices.some(notice=>!notice.readAt)" class="duty-card"><h3>值班提醒</h3><div v-for="notice in notices.filter(notice=>!notice.readAt)" :key="notice.id" class="duty-row"><div><strong>{{notice.title}}</strong><p>{{notice.content}}</p></div><div class="duty-actions"><ui-button v-if="['HANDOVER_PENDING','HANDOVER_RETURNED','HANDOVER_ACCEPTED'].includes(notice.type)" size="small" @click="emit('handover',notice.resourceId)">查看交接</ui-button><ui-button size="small" @click="markRead(notice)">已读</ui-button></div></div></div>
  <div v-if="handoverQueue.length" class="duty-card"><h3>待确认交接</h3><div v-for="handover in handoverQueue" :key="handover.id" class="duty-row"><div>{{catalog.stationName(handover.stationId)}} · 交班时间 {{dutyTime(handover.submission?.at)}}</div><ui-button size="small" type="primary" @click="emit('handover',handover.id)">核对并接班</ui-button></div></div>
  <div v-if="planned.length" class="duty-card"><h3>我的计划班次</h3><div v-for="row in planned" :key="row.id" class="duty-row"><div><strong>{{catalog.stationName(row.stationId)}}</strong><p>{{dutyTime(row.startAt)}} — {{dutyTime(row.endAt)}}</p><span class="duty-meta">负责人 {{catalog.userName(row.leaderId)}} · {{(row.memberIds || []).map(catalog.userName).join('、')}}</span></div><ui-button v-if="can('action:duty:participate')" size="small" @click="open('arrive',{rosterId:row.id})">记录到岗</ui-button></div></div>
  <template v-if="runs.length">
   <ui-select v-if="runs.length>1" v-model="runId" placeholder="选择实际值班"><ui-option v-for="run in runs" :key="run.id" :value="run.id" :label="`${catalog.stationName(run.stationId)} · ${dutyTime(run.startedAt)}`"/></ui-select>
   <div v-if="current" class="duty-card"><div class="duty-row"><div><h3>{{catalog.stationName(current.stationId)}} <ui-tag type="success">{{statusText(current.status)}}</ui-tag></h3><p>实际接班 {{dutyTime(current.startedAt)}}；交接负责人 {{catalog.userName(current.leaderId)}}</p><p>当班成员 {{(current.memberIds || []).map(catalog.userName).join('、')}}</p><p v-for="arrival in current.attendance || []" :key="arrival.userId" class="duty-meta">{{catalog.userName(arrival.userId)}} · 到岗 {{dutyTime(arrival.arrivedAt)}}<span v-if="arrival.leftAt"> · 离岗 {{dutyTime(arrival.leftAt)}}</span></p></div><div class="duty-actions"><ui-button v-if="can('action:duty:participate')" @click="open('substitute')">代班 / 替补</ui-button><ui-button v-if="can('action:duty:participate')" type="danger" plain @click="open('end')">异常结束</ui-button><ui-button v-if="can('action:duty:handover')" type="primary" @click="open('handover')"><ClipboardCheck/>准备交接</ui-button></div></div></div>
   <div class="duty-card"><div class="duty-toolbar"><h3>当班处置记录</h3><ui-button v-if="can('action:duty:record')" type="primary" size="small" @click="open('record')"><Plus/>追加记录</ui-button></div><p v-if="!records.length" class="duty-hint">暂无人工记录。电话沟通、现场核实和维修反馈请及时补充。</p><article v-for="record in records" :key="record.id" class="record-entry"><div class="duty-row"><span class="duty-meta">{{dutyTime(record.occurredAt)}} · {{catalog.userName(record.authorId)}}<span v-if="record.deviceId"> · {{catalog.deviceName(record.deviceId)}}</span></span><ui-button v-if="can('action:duty:record')" text size="small" @click="open('correct',record)">更正留痕</ui-button></div><p>{{record.content}}</p><p v-if="record.correctsId" class="duty-meta">更正记录：{{record.correctionReason}}</p><div class="duty-tags"><ui-button v-for="attachment in record.attachments || []" :key="attachment.id" size="small" text @click="dutyAttachment(attachment.id,attachment.name).catch(notifyError)"><Download/>{{attachment.name}}</ui-button></div></article></div>
   <DutyItems :catalog="catalog" :run-id="runId" :station-id="current?.stationId || ''" embedded/>
  </template>
  <ui-empty v-else-if="!loading" description="尚未接班。先记录到岗，再确认上一班交接；首次启用岗位由主管开班。"/>
 </section>
 <ui-dialog :model-value="!!dialog" :title="({arrive:'记录到岗',open:'首次开班',substitute:'代班 / 替补',end:'异常结束值班',record:'追加处置记录',correct:'更正处置记录',handover:'准备交接'})[dialog] || ''" :close-on-click-modal="false" @close="dialog=''">
  <ui-form class="duty-form" label-position="top" :disabled="saving">
   <template v-if="dialog==='arrive'||dialog==='open'"><ui-form-item label="计划班次" required><ui-select v-model="form.rosterId" filterable><ui-option v-for="row in planned" :key="row.id" :value="row.id" :label="`${catalog.stationName(row.stationId)} · ${dutyTime(row.startAt)} · ${catalog.userName(row.leaderId)}`"/></ui-select></ui-form-item><p class="duty-hint">到岗表示人员已到场，接班签收后才转移岗位责任。首次开班仅用于没有前班的岗位，当班人员及交接负责人需要先记录到岗。</p></template>
   <template v-if="dialog==='substitute'"><ui-form-item label="被替换人员"><DutyUserSelect v-model="form.userId" :users="catalog.users.filter(user=>current?.memberIds?.includes(user.username))"/></ui-form-item><ui-form-item label="替补人员" required><DutyUserSelect v-model="form.replacementId" :users="catalog.users"/></ui-form-item></template>
   <template v-if="dialog==='record'||dialog==='correct'"><ui-form-item label="记录时间" required><ui-date-time v-model="form.occurredAt"/></ui-form-item><ui-form-item label="关联设备"><ui-select v-model="form.deviceId" filterable clearable><ui-option v-for="device in catalog.devices.filter(device=>current?.deviceIds?.includes(device.id || device.deviceId))" :key="device.id || device.deviceId" :value="device.id || device.deviceId" :label="device.name || device.id || device.deviceId"/></ui-select></ui-form-item><div class="duty-grid"><ui-form-item label="关联告警 ID（选填）"><ui-input v-model="form.alarmId"/></ui-form-item><ui-form-item label="关联事项 ID（选填）"><ui-input v-model="form.itemId"/></ui-form-item></div><ui-form-item label="现场情况 / 采取措施 / 后续约定" required><ui-input v-model="form.content" type="textarea" :rows="5"/></ui-form-item><ui-form-item label="附件"><input type="file" multiple aria-label="添加处置附件" @change="pickFiles"/><p class="duty-hint">{{files.map(file=>file.name).join('、') || '未选择新附件'}}</p><div class="duty-tags"><ui-tag v-for="attachment in form.attachments || []" :key="attachment.id">{{attachment.name}}</ui-tag></div></ui-form-item><ui-form-item v-if="dialog==='correct'" label="更正原因" required><ui-input v-model="form.correctionReason" type="textarea" :rows="2"/></ui-form-item></template>
   <ui-form-item v-if="dialog==='handover'" label="接班排班" required><ui-select v-model="form.nextRosterId" filterable><ui-option v-for="row in rosters.filter(row=>row.stationId===current?.stationId && row.id!==current?.rosterId)" :key="row.id" :value="row.id" :label="`${dutyTime(row.startAt)} · ${catalog.userName(row.leaderId)}`"/></ui-select></ui-form-item>
   <ui-form-item v-if="['open','substitute','end'].includes(dialog)" label="原因及安排" required><ui-input v-model="form.reason" type="textarea" :rows="3"/></ui-form-item>
   <ui-alert v-if="dialog==='end'" type="warning" :closable="false" title="将如实结束实际值班。没有接班人员时会形成空岗记录，系统不会自动指定接班人。"/>
  </ui-form><template #footer><ui-button :disabled="saving" @click="dialog=''">取消</ui-button><ui-button type="primary" :loading="saving" @click="perform">{{dialog==='handover'?'创建交接草稿':'确认保存'}}</ui-button></template>
 </ui-dialog>
</template>
<style scoped>.current-title{margin:0;font-size:15px}.record-entry{border-bottom:1px solid var(--border);padding:12px 0}.record-entry:last-child{border:0}.record-entry p{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}.duty-card>.duty-row{padding:9px 0;border-bottom:1px solid var(--border)}.duty-card>.duty-row:last-child{border:0}</style>
