<script setup>
import DeviceSelect from '../DeviceSelect.vue'
import { computed, onBeforeUnmount, reactive, ref } from 'vue'
import { Plus } from '@lucide/vue'
import { can } from '../../permissions.js'
import { createClientId } from '../../clientId.js'
import { notifyError } from '../../api.js'
import { ruleLabWrite } from '../../rulelab/api.js'
import { labelConclusions, recordBody, ruleLabTime } from '../../rulelab/helpers.js'
const props=defineProps({items:{type:Array,default:()=>[]},devices:{type:Array,default:()=>[]},deviceId:{type:String,default:''}})
const emit=defineEmits(['refresh'])
const rows=computed(()=>props.items.map(recordBody).filter(row=>!props.deviceId||row.deviceId===props.deviceId)),editable=computed(()=>can('menu:devices')&&can('POST /api/v1/rule-lab/labels'))
const dialog=ref(false),saving=ref(false),confirming=ref(''),error=ref(''),form=reactive({})
let generation=0,disposed=false,originalScope='personal',originalVersion=0
const deviceName=id=>props.devices.find(row=>row.id===id)?.name||id
function edit(row){const value=row||{};Object.assign(form,{resourceId:value.resourceId||createClientId(),expectedVersion:value.revisionVersion||0,scope:String(value.scope||'personal').toLowerCase(),deviceId:props.deviceId||value.deviceId||'',eventType:value.eventType||'',range:value.start?[value.start,value.end]:null,conclusion:value.conclusion||'UNKNOWN',basis:value.basis||''});originalScope=form.scope;originalVersion=form.expectedVersion;if(form.scope==='shared'&&!can('POST /api/v1/rule-lab/labels/publish')){form.scope='personal';form.expectedVersion=0}error.value='';dialog.value=true}
async function save(){if(saving.value)return;const token=generation;saving.value=true;error.value='';try{if(!form.deviceId||!form.eventType.trim()||!form.range?.[0]||!(form.range[1]>form.range[0])||!form.basis.trim())throw new Error('标签须填写设备、事件类型、真实核实区间与依据');await ruleLabWrite('labels','','',{resourceId:form.resourceId,expectedVersion:form.expectedVersion,scope:form.scope,deviceIds:[form.deviceId],body:{deviceId:form.deviceId,eventType:form.eventType.trim(),start:form.range[0],end:form.range[1],conclusion:form.conclusion,basis:form.basis.trim()}});if(token!==generation||disposed)return;dialog.value=false;emit('refresh')}catch(cause){if(token===generation&&!disposed){error.value=cause.status===409?'标签版本已变化，请刷新并基于新版本保存。':cause.message;notifyError(cause)}}finally{if(token===generation)saving.value=false}}
async function confirm(row){if(confirming.value)return;const token=generation;confirming.value=row.revisionId;try{await ruleLabWrite('labels',row.revisionId,'confirm',{expectedVersion:row.revisionVersion});if(token===generation&&!disposed)emit('refresh')}catch(cause){if(token===generation&&!disposed){notifyError(cause);if(cause.status===409)emit('refresh')}}finally{if(token===generation)confirming.value=''}}
onBeforeUnmount(()=>{disposed=true;generation++})
</script>
<template><section class="lab-stack"><div class="lab-toolbar"><p class="lab-hint">标签覆盖实际事件及明确负例区间。只标注已出现的告警不能评价总体召回；未知标签不作负例。</p><ui-button v-if="editable" type="primary" size="small" @click="edit()"><Plus/>新增真实标签</ui-button></div><div class="lab-table-scroll"><ui-table :data="rows" empty-text="暂无核实标签。实验仍可比较行为差异。"><ui-table-column label="设备 / 事件类型" min-width="190"><template #default="{row}">{{deviceName(row.deviceId)}}<p class="lab-meta">{{row.eventType}} · 版本 {{row.revisionVersion}}</p></template></ui-table-column><ui-table-column label="核实区间" min-width="210"><template #default="{row}">{{ruleLabTime(row.start)}}<p class="lab-meta">至 {{ruleLabTime(row.end)}}</p></template></ui-table-column><ui-table-column label="结论与依据" min-width="270"><template #default="{row}">{{labelConclusions[row.conclusion] || row.conclusion}}<p class="lab-meta">{{row.basis}}</p></template></ui-table-column><ui-table-column label="确认" min-width="160"><template #default="{row}"><ui-tag :type="row.status==='CONFIRMED'?'success':'warning'">{{row.status==='CONFIRMED'?'已确认':'草稿'}}</ui-tag><p v-if="row.confirmedBy" class="lab-meta">{{row.confirmedBy}} · {{ruleLabTime(row.confirmedAt)}}</p></template></ui-table-column><ui-table-column v-if="editable||can('POST /api/v1/rule-lab/labels/:id/confirm')" label="操作" width="160"><template #default="{row}"><ui-button v-if="row.status==='DRAFT'&&can('POST /api/v1/rule-lab/labels/:id/confirm')" :data-lab-label="row.revisionId" text size="small" :loading="confirming===row.revisionId" @click="confirm(row)">确认核实依据</ui-button><ui-button v-if="editable" text size="small" @click="edit(row)">保存新版本</ui-button></template></ui-table-column></ui-table></div></section>
 <ui-dialog v-model="dialog" title="保存真实标签草稿" width="min(760px,94vw)" :close-on-click-modal="false" @close="dialog=false"><div class="lab-dialog-body"><ui-alert v-if="error" :title="error" type="error" :closable="false"/><ui-form label-position="top" :disabled="saving"><div class="lab-grid"><ui-form-item label="设备" required><DeviceSelect v-model="form.deviceId" :disabled="!!deviceId"/></ui-form-item><ui-form-item label="事件类型" required><ui-input v-model="form.eventType" placeholder="填写对应告警或核实事件类型"/></ui-form-item><ui-form-item label="标签用途"><ui-select v-model="form.scope" @change="form.expectedVersion=form.scope===originalScope?originalVersion:0"><ui-option value="personal" label="个人核实标签"/><ui-option v-if="can('POST /api/v1/rule-lab/labels/publish')" value="shared" label="受权共享标签"/></ui-select></ui-form-item><ui-form-item label="核实结论"><ui-select v-model="form.conclusion"><ui-option v-for="[value,label] in Object.entries(labelConclusions)" :key="value" :value="value" :label="label"/></ui-select></ui-form-item></div><ui-form-item label="实际核实区间" required><ui-date-range v-model="form.range"/></ui-form-item><ui-form-item label="真实核实依据" required><ui-input v-model="form.basis" type="textarea" :rows="4" placeholder="记录真实事件、现场核实或明确负例范围的依据"/></ui-form-item><p class="lab-hint">保存草稿后需要另行人工确认。既有实验保留运行前固定的标签版本。</p></ui-form></div><template #footer><ui-button :disabled="saving" @click="dialog=false">取消</ui-button><ui-button type="primary" :loading="saving" @click="save">保存标签草稿</ui-button></template></ui-dialog>

</template>
