<script setup>
import { computed, onBeforeUnmount, reactive, ref, watch } from 'vue'
import { Download, RefreshCw, Sparkles } from '@lucide/vue'
import { can } from '../../permissions.js'
import { createClientId } from '../../clientId.js'
import { UiMessage } from '../../ui/feedback.js'
import { responseAll, responseAttachment, responseExport, responseRead, responseWrite } from '../../response/api.js'
import { confirmationPayload, correctivePayload, evidenceKinds, evaluationRatio, formalConfirmation, hasNewEvidence, responseTime, sourceLabels, stateLabel, stateTone, stepDuration, durationLabel } from '../../response/helpers.js'
const props=defineProps({run:Object,execution:Object,devices:{type:Array,default:()=>[]}})
const emit=defineEmits(['navigate','refresh'])
const root=ref(null),loading=ref(false),error=ref(''),snapshot=ref(null),fixed=ref(null),metrics=ref([]),findings=ref([]),evidence=ref([]),downloading=ref(false)
const confirming=ref(false),confirmationError=ref(''),conclusion=ref(''),confirmationKey=ref('')
const dialog=ref(false),detail=ref(null),createDialog=ref(false),saving=ref(false),saveError=ref(''),staff=ref([]),staffLoading=ref(false)
const form=reactive({resourceId:'',findingId:'',title:'',owner:'',dueAt:null,requiredVerification:[''],idempotencyKey:''})
const aiJobs=ref([]),aiId=ref(''),aiError=ref(''),aiBusy=ref(false),useKnowledge=ref(false),aiKey=ref('')
let generation=0,detailGeneration=0,aiTimer=0,disposed=false
const evaluation=computed(()=>snapshot.value?.statistics?.evaluation||{}),confirmed=computed(()=>formalConfirmation(props.execution,props.run,snapshot.value)),newEvidence=computed(()=>fixed.value&&hasNewEvidence(fixed.value.body,props.execution?.body))
const activeAI=computed(()=>aiJobs.value.find(row=>row.id===aiId.value)||aiJobs.value[0]),interpretation=computed(()=>activeAI.value?.interpretation||{})
const aiSections=[['observedBottlenecks','观察到的瓶颈'],['evidenceGaps','证据缺口'],['improvementSuggestions','改进建议'],['limitations','解读限制']]
const deviceName=id=>props.devices.find(row=>row.id===id)?.name||id
const unwrap=rows=>(rows||[]).map(row=>({...row.body,id:row.id,deviceId:row.deviceId}))
const detailEvidence=computed(()=>evidence.value.filter(row=>row.summary?.stepId===detail.value?.stepId))
const fixedMilestone=computed(()=>fixed.value?.body?.milestones?.find(row=>row.id===detail.value?.milestoneId))
function stopAI(){clearTimeout(aiTimer);aiTimer=0}
async function loadAI(){const token=generation,id=props.execution?.resourceId,runId=props.run?.id;if(!id||!snapshot.value)return;try{const value=await responseRead('response-runs',id,'ai-jobs',{runId});if(token!==generation||disposed)return;aiJobs.value=(value.items||[]).sort((a,b)=>b.createdAt-a.createdAt||String(b.id).localeCompare(String(a.id)));if(!aiJobs.value.some(row=>row.id===aiId.value))aiId.value=aiJobs.value[0]?.id||'';stopAI();if(aiJobs.value.some(row=>['QUEUED','RUNNING'].includes(row.status)))aiTimer=setTimeout(loadAI,2000)}catch(cause){if(token===generation&&!disposed){aiError.value=cause.message;stopAI()}}}
async function load(){const token=++generation;detailGeneration++;stopAI();loading.value=false;error.value='';snapshot.value=null;fixed.value=null;metrics.value=[];findings.value=[];evidence.value=[];dialog.value=false;createDialog.value=false;conclusion.value='';confirmationError.value='';confirming.value=false;confirmationKey.value=createClientId();aiJobs.value=[];aiId.value='';aiError.value='';aiBusy.value=false;aiKey.value=createClientId();if(!props.run?.snapshotId)return;loading.value=true;try{const id=props.run.id,values=await Promise.all([responseRead('response-evaluations',id,'snapshot'),responseRead('response-revisions',props.run.parameters.executionRevisionId),...['metrics','findings','evidence'].map(kind=>responseAll('response-evaluations',id,kind))]);if(token!==generation||disposed)return;[snapshot.value,fixed.value]=values;metrics.value=unwrap(values[2].items);findings.value=unwrap(values[3].items);evidence.value=values[4].items||[];await loadAI()}catch(cause){if(token===generation&&!disposed){error.value=cause.message;if([403,404].includes(cause.status)){snapshot.value=null;fixed.value=null;metrics.value=[];findings.value=[];evidence.value=[]}}}finally{if(token===generation)loading.value=false}}
async function confirm(){if(confirming.value)return;const token=generation;confirming.value=true;confirmationError.value='';try{const body=confirmationPayload(props.execution,props.run,snapshot.value,conclusion.value,confirmationKey.value);await responseWrite('response-runs',props.execution.resourceId,`reviews/${encodeURIComponent(props.run.id)}/confirm`,body);if(token!==generation||disposed)return;UiMessage.success('固定复盘已正式确认');emit('refresh')}catch(cause){if(token===generation&&!disposed)confirmationError.value=cause.status===409?'执行或复盘版本已变化，请刷新核对后再确认。':cause.message}finally{if(token===generation)confirming.value=false}}
function showDetail(row){detail.value=row;dialog.value=true}
function fact(id){const row=metrics.value.find(row=>row.id===id)||findings.value.find(row=>row.id===id);if(row)return showDetail(row);const ev=evidence.value.find(row=>row.id===id);if(ev)return showDetail(metrics.value.find(row=>row.stepId===ev.summary?.stepId));root.value?.querySelector('.response-snapshot')?.scrollIntoView({block:'start'})}
async function createCorrective(row){const token=++detailGeneration;Object.assign(form,{resourceId:createClientId(),findingId:row.id,title:'',owner:'',dueAt:null,requiredVerification:[''],idempotencyKey:createClientId()});createDialog.value=true;saving.value=false;saveError.value='';staff.value=[];staffLoading.value=true;try{const result=await responseRead('response-staff','','',{deviceIds:props.execution.deviceIds.join(',')});if(token===detailGeneration&&!disposed)staff.value=result.items||[]}catch(cause){if(token===detailGeneration&&!disposed)saveError.value=cause.message}finally{if(token===detailGeneration)staffLoading.value=false}}
async function saveCorrective(){if(saving.value)return;const token=detailGeneration;saving.value=true;saveError.value='';try{const body=correctivePayload(form,props.execution,props.run,snapshot.value,findings.value,form.idempotencyKey),value=await responseWrite('response-runs',props.execution.resourceId,'improvements',body);if(token!==detailGeneration||disposed)return;createDialog.value=false;UiMessage.success('整改事项已建立，完成需独立验收');emit('refresh');emit('navigate','response',{correctiveId:value.resourceId,deviceId:value.deviceIds[0]})}catch(cause){if(token===detailGeneration&&!disposed)saveError.value=cause.status===409?'固定复盘或整改版本冲突，请刷新后重试。':cause.message}finally{if(token===detailGeneration)saving.value=false}}
async function exportReport(){if(downloading.value)return;downloading.value=true;try{await responseExport(props.run.id)}catch(cause){error.value=cause.message}finally{downloading.value=false}}
async function download(ev){try{await responseAttachment(ev.sourceId,ev.summary?.description)}catch(cause){error.value=cause.message}}
async function runAI(){if(aiBusy.value)return;const token=generation;aiBusy.value=true;aiError.value='';try{const current=await responseRead('response-evaluations',props.run.id);if(token!==generation||disposed)return;const body={expectedVersion:current.version,idempotencyKey:aiKey.value,useKnowledge:useKnowledge.value,reinterpret:!!activeAI.value},value=await responseWrite('response-runs',props.execution.resourceId,`ai-jobs?runId=${encodeURIComponent(props.run.id)}`,body);if(token!==generation||disposed)return;aiId.value=value.id;aiKey.value=createClientId();await loadAI()}catch(cause){if(token===generation&&!disposed)aiError.value=cause.message}finally{if(token===generation)aiBusy.value=false}}
async function stopJob(){if(!activeAI.value||aiBusy.value)return;const token=generation;aiBusy.value=true;try{await responseWrite('response-runs',props.execution.resourceId,`ai-jobs/${encodeURIComponent(activeAI.value.id)}/stop`,{expectedVersion:activeAI.value.version});if(token===generation&&!disposed)await loadAI()}catch(cause){if(token===generation&&!disposed)aiError.value=cause.message}finally{if(token===generation)aiBusy.value=false}}
watch(()=>[props.run?.id,props.run?.snapshotId],load,{immediate:true})
onBeforeUnmount(()=>{disposed=true;generation++;detailGeneration++;stopAI()})
</script>
<template><section ref="root" class="response-stack response-results"><div class="response-toolbar"><h3>固定复盘事实</h3><div class="response-actions"><ui-button size="small" :loading="loading" @click="load"><RefreshCw/>刷新结果</ui-button><ui-button v-if="run.snapshotId&&can('GET /api/v1/response-evaluations/:id/export')" size="small" :loading="downloading" @click="exportReport"><Download/>导出固定报告</ui-button></div></div><ui-alert v-if="error" :title="error" type="error" :closable="false"/><ui-skeleton v-if="loading&&!snapshot" :rows="5"/><ui-empty v-else-if="!snapshot" description="此任务尚无可读取的固定事实，请检查实际任务状态。"/>
<template v-else><article class="response-card response-stack response-snapshot"><div class="response-toolbar"><strong>{{sourceLabels[evaluation.source]}} · 固定执行版本 {{fixed?.version}}</strong><ui-tag :type="stateTone(run.status)">{{stateLabel(run.status)}}</ui-tag></div><p class="response-meta">固定流程版本 {{evaluation.procedureRevisionId}}<br>事实截至 {{responseTime(evaluation.cutoff)}} · 算法 {{snapshot.statistics?.algorithmVersion}}<br>事实哈希 {{snapshot.factsHash}}</p><ui-alert v-if="newEvidence" title="有新证据待重算" type="warning" :closable="false">执行已追加登记、更正或单次样本关联。此固定版本与原有正式确认保留，另行生成新复盘核对。</ui-alert><div class="response-stats"><article><span>规定步骤完成率</span><strong data-response-ratio="completion">{{evaluationRatio(evaluation,'completionRate')}}</strong><p class="response-meta">已确认完成 {{evaluation.completedRequiredSteps}} / 规定步骤 {{evaluation.requiredSteps}}</p></article><article><span>规定证据覆盖率</span><strong data-response-ratio="evidence">{{evaluationRatio(evaluation,'evidenceCoverage')}}</strong><p class="response-meta">已确认资料 {{evaluation.confirmedEvidence}} / 规定证据 {{evaluation.requiredEvidence}}</p></article></div><p class="response-hint">比例只依据固定流程的规定项。未记录保留为证据缺口；平台告警确认不代表人员已到场。单位目标来自已发布流程，无外部达标结论。</p><p class="response-meta">代表证据 {{snapshot.statistics?.representativeEvidenceCount}} / 已登记证据 {{snapshot.statistics?.originalEvidenceCount}}；完整记录保留在固定执行版本。</p><ui-alert v-for="reason in snapshot.limitations||[]" :key="reason" :title="reason" type="warning" :closable="false"/><p v-if="!fixed?.body?.platformReceivedAt&&evaluation.source==='REAL_CASE'" class="response-hint">没有可关联单次报文的可信平台接收时间；从平台接收起计的时长保持未知。</p></article>
<article class="response-card response-stack"><h3>步骤时序与证据</h3><div class="response-table-scroll"><ui-table :data="metrics" empty-text="固定流程没有可展示步骤。"><ui-table-column label="步骤 / 固定状态" min-width="170"><template #default="{row}">{{row.name}}<p class="response-meta">{{row.required?'规定步骤':'可选步骤'}} · {{stateLabel(row.status)}}</p></template></ui-table-column><ui-table-column label="发生 / 平台登记" min-width="230"><template #default="{row}">{{responseTime(row.occurredAt)}}<p class="response-meta">登记 {{responseTime(row.recordedAt)}}<br>可信起点 {{responseTime(row.startAt)}}</p></template></ui-table-column><ui-table-column label="完成时长 / 等待 / 单位目标" min-width="210"><template #default="{row}"><span :data-response-step-duration="row.stepId">{{stepDuration(row)}}</span><p v-if="row.waitingMs!=null" class="response-meta">待完成等待 {{durationLabel(row.waitingMs)}}</p><p class="response-meta">{{row.targetMs?durationLabel(row.targetMs):'未设置单位目标'}} · {{stateLabel(row.targetResult)}}</p></template></ui-table-column><ui-table-column label="规定证据" min-width="170"><template #default="{row}">{{row.confirmedEvidence}} / {{row.requiredEvidence}}<p class="response-meta">{{(row.missingEvidence||[]).map(kind=>evidenceKinds[kind]||kind).join('、')}}</p></template></ui-table-column><ui-table-column label="依据" width="90"><template #default="{row}"><ui-button text size="small" @click="showDetail(row)">核对依据</ui-button></template></ui-table-column></ui-table></div></article>
<article class="response-card response-stack"><h3>正式人工复盘</h3><template v-if="confirmed"><ui-tag type="success">已正式确认此固定版本</ui-tag><p>{{confirmed.conclusion}}</p><p class="response-meta">{{confirmed.confirmer}} · {{responseTime(confirmed.confirmedAt)}}</p></template><template v-else><ui-alert v-if="confirmationError" :title="confirmationError" type="error" :closable="false"/><p v-if="!['ENDED','REVIEWED'].includes(execution.body.status)" class="response-hint">执行结束后可正式确认固定复盘；当前事实仍可读取。</p><ui-form v-else-if="can('POST /api/v1/response-runs/:id/reviews/:revisionId/confirm')" label-position="top" :disabled="confirming"><ui-form-item label="人工复盘结论与依据" required><ui-input v-model="conclusion" type="textarea" :rows="3" maxlength="4000" placeholder="核对固定步骤、缺失证据、时序与单位目标，记录实际结论"/></ui-form-item><ui-button type="primary" size="small" :loading="confirming" @click="confirm">正式确认此固定复盘</ui-button></ui-form></template></article>
<article class="response-card response-stack"><h3>固定发现与整改来源</h3><p v-if="!confirmed" class="response-hint">正式确认本版本后，可从实际发现建立整改事项。</p><article v-for="row in findings" :key="row.id" class="response-card"><div class="response-toolbar"><strong>{{row.name}} · {{stateLabel(row.status)}}</strong><div class="response-actions"><ui-button size="small" @click="showDetail(row)">核对依据</ui-button><ui-button v-if="confirmed&&can('POST /api/v1/response-runs/:id/improvements')" size="small" :data-response-improvement="row.stepId" @click="createCorrective(row)">建立整改</ui-button></div></div><p class="response-meta">{{stateLabel(row.targetResult)}} · {{(row.limitations||[]).join('；')}}</p></article><ui-empty v-if="!findings.length" description="本次固定事实没有生成整改来源发现。"/></article>
<article class="response-card response-stack"><div class="response-toolbar"><h3>AI 复盘解读</h3><div v-if="can('POST /api/v1/response-runs/:id/ai-jobs')" class="response-actions"><ui-checkbox v-model="useKnowledge" :disabled="aiBusy">使用已授权知识</ui-checkbox><ui-button size="small" :loading="aiBusy" :disabled="['QUEUED','RUNNING'].includes(activeAI?.status)" @click="runAI"><Sparkles/>{{activeAI?'重新解读':'开始解读'}}</ui-button><ui-button v-if="['QUEUED','RUNNING'].includes(activeAI?.status)" size="small" :loading="aiBusy" @click="stopJob">停止解读</ui-button></div></div><p class="response-hint">点击后才启动模型。AI 解读独立保存版本，正式人工结论与固定事实继续可用。</p><ui-alert v-if="aiError" :title="aiError" type="error" :closable="false"/><ui-select v-if="aiJobs.length" v-model="aiId"><ui-option v-for="job in aiJobs" :key="job.id" :value="job.id" :label="`${responseTime(job.createdAt)} · ${stateLabel(job.status)}`"/></ui-select><template v-if="activeAI"><p>解读状态 {{stateLabel(activeAI.status)}} · {{responseTime(activeAI.completedAt)}}</p><p class="response-meta">固定快照版本 {{activeAI.snapshotVersion}} · 模型 {{activeAI.model||'由工作流配置'}}<br>提供固定事实 {{activeAI.factIds?.length||0}} 条 · {{activeAI.coverage?.summary||activeAI.coverage?.description||'实际阅读范围以固定事实清单和受控工具记录为准'}}</p><ui-alert v-if="activeAI.error" :title="activeAI.error" type="warning" :closable="false"/><template v-if="activeAI.status==='SUCCEEDED'"><p>{{interpretation.summary}}</p><article v-for="[key,title] in aiSections" :key="key"><h4>{{title}}</h4><div v-for="(statement,index) in interpretation[key]||[]" :key="index"><p>{{statement.text}}</p><div class="response-actions"><ui-button v-for="id in statement.factIds||[]" :key="id" text size="small" @click="fact(id)">核对引用事实</ui-button></div></div></article></template></template><ui-empty v-else description="尚未主动生成 AI 解读。"/></article></template>
<ui-dialog v-model="dialog" title="固定步骤依据" width="min(850px,94vw)"><div class="response-dialog-body response-stack"><template v-if="detail"><h3>{{detail.name}} · {{stateLabel(detail.status)}}</h3><p v-for="reason in detail.limitations||[]" :key="reason" class="response-hint">{{reason}}</p><article v-if="fixedMilestone" class="response-card"><strong>{{sourceLabels[fixedMilestone.source]}} · {{stateLabel(fixedMilestone.status)}}</strong><p>{{fixedMilestone.explanation}}</p><p class="response-meta">执行 {{fixedMilestone.executor}} · 登记 {{fixedMilestone.recorder}}<br>发生 {{responseTime(fixedMilestone.occurredAt)}} · 登记 {{responseTime(fixedMilestone.recordedAt)}}{{fixedMilestone.correctsId?' · 更正前次记录':''}}</p></article><article v-for="ev in detailEvidence" :key="ev.id" class="response-card"><strong>{{evidenceKinds[ev.sourceKind]||ev.sourceKind}} · {{deviceName(ev.deviceId)}}</strong><p>{{ev.summary?.description}}</p><p class="response-meta">发生 {{responseTime(ev.occurredAt)}} · 登记 {{responseTime(ev.summary?.recordedAt)}}<br>来源 {{sourceLabels[ev.summary?.source]}} · {{stateLabel(ev.summary?.confirmation)}}<br>固定执行版本 {{ev.resourceVersion}}</p><ui-button v-if="ev.sourceKind==='ATTACHMENT'&&can('GET /api/v1/response-attachments/:id')" size="small" @click="download(ev)">受权下载原件</ui-button><ui-button v-if="ev.sourceKind==='RAW_MESSAGE'&&can('menu:raw')" size="small" @click="emit('navigate','raw',{deviceId:ev.deviceId,messageId:ev.sourceId})">读取具体原文</ui-button><ui-button v-if="ev.sourceKind==='ALARM_LIFECYCLE'&&can('menu:alarms')" size="small" @click="emit('navigate','alarms',{alarmId:fixed?.body?.alarmId,deviceId:ev.deviceId})">查看关联告警</ui-button></article><ui-empty v-if="!detailEvidence.length" description="此步骤没有保留代表资料；缺失或截断情况以固定步骤与完整执行版本为准。"/></template></div><template #footer><ui-button @click="dialog=false">关闭</ui-button></template></ui-dialog>
<ui-dialog v-model="createDialog" title="从固定发现建立整改" width="min(760px,94vw)" :close-on-click-modal="false"><div class="response-dialog-body response-stack"><ui-alert v-if="saveError" :title="saveError" type="error" :closable="false"/><p class="response-hint">来源为已人工确认的固定复盘与具体发现。验收项作为独立验收依据保存。</p><ui-form label-position="top" :disabled="saving"><ui-form-item label="整改名称" required><ui-input v-model="form.title" maxlength="300"/></ui-form-item><div class="response-grid"><ui-form-item label="实际负责人" required><ui-select v-model="form.owner" :loading="staffLoading"><ui-option v-for="person in staff" :key="person.username" :value="person.username" :label="person.displayName||person.username"/></ui-select></ui-form-item><ui-form-item label="整改期限" required><ui-date-time v-model="form.dueAt"/></ui-form-item></div><ui-form-item v-for="(_,index) in form.requiredVerification" :key="index" :label="`规定验收项 ${index+1}`" required><div class="response-actions"><ui-input v-model="form.requiredVerification[index]" maxlength="500"/><ui-button size="small" :disabled="form.requiredVerification.length===1" @click="form.requiredVerification.splice(index,1)">移除</ui-button></div></ui-form-item><ui-button size="small" :disabled="form.requiredVerification.length>=20" @click="form.requiredVerification.push('')">增加验收项</ui-button></ui-form></div><template #footer><ui-button :disabled="saving" @click="createDialog=false">取消</ui-button><ui-button type="primary" :loading="saving" @click="saveCorrective">保存整改事项</ui-button></template></ui-dialog>
</section></template>
