<script setup>
import DeviceSelect from '../DeviceSelect.vue'
import { computed, onBeforeUnmount, reactive, ref } from 'vue'
import { Plus, Trash2 } from '@lucide/vue'
import { can } from '../../permissions.js'
import { createClientId } from '../../clientId.js'
import { responseWrite } from '../../response/api.js'
import { evidenceKinds, procedureDraft, procedurePayload, responseTime, systemEvents } from '../../response/helpers.js'
const props=defineProps({items:{type:Array,default:()=>[]},devices:{type:Array,default:()=>[]},deviceId:String})
const emit=defineEmits(['refresh'])
const dialog=ref(false),busy=ref(false),error=ref(''),form=reactive(procedureDraft()),key=ref(''),publishing=ref('')
let generation=0,disposed=false
const rows=computed(()=>props.items.filter(row=>!props.deviceId||row.deviceIds.includes(props.deviceId))),deviceName=id=>props.devices.find(row=>row.id===id)?.name||id
function edit(row){Object.assign(form,procedureDraft(row));if(!row){form.resourceId=createClientId();form.deviceIds=props.deviceId?[props.deviceId]:[]}key.value=createClientId();error.value='';dialog.value=true}
function add(){form.steps.push({id:'',name:'',role:'',required:true,prerequisites:[],requiredEvidence:[],clockStart:'RUN_START',targetSeconds:null,systemEventType:''})}
async function save(){if(busy.value)return;const token=generation;busy.value=true;error.value='';try{await responseWrite('response-procedures','','',procedurePayload(form,key.value));if(token===generation&&!disposed){dialog.value=false;emit('refresh')}}catch(cause){if(token===generation&&!disposed)error.value=cause.status===409?'流程版本已变化，请重新读取后保存。':cause.message}finally{if(token===generation)busy.value=false}}
async function publish(row){if(publishing.value)return;const token=generation;publishing.value=row.id;try{await responseWrite('response-procedures',row.resourceId,'publish',{expectedVersion:row.version,idempotencyKey:createClientId(),action:'PUBLISH'});if(token===generation&&!disposed)emit('refresh')}catch(cause){if(token===generation&&!disposed)error.value=cause.message}finally{if(token===generation)publishing.value=''}}
onBeforeUnmount(()=>{disposed=true;generation++})
</script>
<template><section class="response-stack"><div class="response-toolbar"><p class="response-hint">流程明确责任岗位、前置步骤、计时依据及单位目标，发布后计划引用固定版本。</p><ui-button v-if="can('POST /api/v1/response-procedures')&&can('menu:devices')" type="primary" size="small" @click="edit()"><Plus/>新增处置流程</ui-button></div><ui-alert v-if="error&&!dialog" :title="error" type="error" :closable="false"/><div class="response-table-scroll"><ui-table :data="rows" empty-text="暂无流程版本。"><ui-table-column label="流程 / 场景" min-width="250"><template #default="{row}">{{row.body.name}}<p class="response-meta">{{row.body.scenario}} · 版本 {{row.version}}</p></template></ui-table-column><ui-table-column label="适用设备 / 状态" min-width="200"><template #default="{row}">{{row.deviceIds.map(deviceName).join('、')}}<p class="response-meta">{{row.body.published?'已发布':'草稿'}} · 步骤 {{row.body.steps.length}}<br>{{responseTime(row.body.publishedAt)}}</p></template></ui-table-column><ui-table-column label="操作" width="190"><template #default="{row}"><ui-button v-if="can('POST /api/v1/response-procedures')" :data-response-procedure="row.resourceId" text size="small" @click="edit(row)">编辑新版本</ui-button><ui-button v-if="!row.body.published&&can('POST /api/v1/response-procedures/:id/publish')" text size="small" :data-response-publish="row.resourceId" :loading="publishing===row.id" @click="publish(row)">发布固定流程</ui-button></template></ui-table-column></ui-table></div></section>
<ui-dialog v-model="dialog" title="编辑处置流程版本" width="min(1000px,94vw)" :close-on-click-modal="false" @close="dialog=false"><div class="response-dialog-body"><ui-alert v-if="error" :title="error" type="error" :closable="false"/><ui-form label-position="top" :disabled="busy"><div class="response-grid"><ui-form-item label="流程名称" required><ui-input v-model="form.name"/></ui-form-item><ui-form-item label="适用场景" required><ui-input v-model="form.scenario"/></ui-form-item></div><ui-form-item label="明确设备范围" required><DeviceSelect v-model="form.deviceIds" multiple :disabled="!!form.expectedVersion||!!deviceId"/></ui-form-item><article v-for="(step,index) in form.steps" :key="index" class="response-card response-stack"><div class="response-toolbar"><strong>流程步骤 {{index+1}}</strong><ui-button :disabled="form.steps.length===1" size="small" text @click="form.steps.splice(index,1)"><Trash2/>移除</ui-button></div><div class="response-grid"><ui-form-item :label="'步骤标识 '+(index+1)" required><ui-input v-model="step.id" placeholder="使用稳定且唯一的步骤标识"/></ui-form-item><ui-form-item :label="'步骤名称 '+(index+1)" required><ui-input v-model="step.name"/></ui-form-item><ui-form-item :label="'责任岗位 '+(index+1)" required><ui-input v-model="step.role"/></ui-form-item><ui-form-item label="来源节点"><ui-select v-model="step.systemEventType" clearable placeholder="人工现场节点"><ui-option v-for="[value,label] in Object.entries(systemEvents)" :key="value" :value="value" :label="label"/></ui-select></ui-form-item><ui-form-item label="前置步骤"><ui-select v-model="step.prerequisites" multiple><ui-option v-for="s in form.steps.filter(s=>s.id&&s!==step)" :key="s.id" :value="s.id" :label="s.name || s.id"/></ui-select></ui-form-item><ui-form-item label="计时起点"><ui-select v-model="step.clockStart"><ui-option value="RUN_START" label="实际执行开始"/><ui-option value="PLATFORM_RECEIVED" label="可信平台接收时间"/><ui-option v-for="s in form.steps.filter(s=>s.id&&s!==step)" :key="s.id" :value="s.id" :label="s.name || s.id"/></ui-select></ui-form-item><ui-form-item label="规定证据类型"><ui-select v-model="step.requiredEvidence" multiple><ui-option v-for="[value,label] in Object.entries(evidenceKinds)" :key="value" :value="value" :label="label"/></ui-select></ui-form-item><ui-form-item label="单位目标（秒，选填）"><ui-input-number v-model="step.targetSeconds" :min="0" clearable/></ui-form-item></div><ui-checkbox v-model="step.required">本场景必要步骤</ui-checkbox><p v-if="step.systemEventType" class="response-hint">该节点只允许关联平台实际提交的事务事件，不提供人工时间替代。</p></article><ui-button size="small" @click="add"><Plus/>添加流程步骤</ui-button><p class="response-hint">单位目标由本次流程明确设定，不代表法规时限。已开始的执行保留原流程和人员快照。</p></ui-form></div><template #footer><ui-button :disabled="busy" @click="dialog=false">取消</ui-button><ui-button type="primary" :loading="busy" @click="save">保存流程草稿版本</ui-button></template></ui-dialog></template>
