package httpapi

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"iot-platform/internal/model"
	"iot-platform/internal/protocolbuild"
)

func (s *Server) downloadProtocolPackageV2(w http.ResponseWriter, r *http.Request) {
	release, data, ok := s.readProtocolDownloadV2(w, r)
	if !ok {
		return
	}
	filename := release.ProtocolID + "-" + release.Version + "-package.zip"
	writeProtocolDownloadV2(w, data, filename, "application/zip")
	s.audit(r, "protocol.v2.package.download", "protocolRelease", release.ProtocolID+"@"+release.Version, nil)
}

func (s *Server) downloadProtocolSourceV2(w http.ResponseWriter, r *http.Request) {
	release, data, ok := s.readProtocolDownloadV2(w, r)
	if !ok {
		return
	}
	archive, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		problem(w, 409, "协议制品 ZIP 已损坏，无法提取源码")
		return
	}
	var source *zip.File
	for _, file := range archive.File {
		if file.Name != "source/upload.go" && file.Name != "source/upload.zip" {
			continue
		}
		if source != nil || !file.Mode().IsRegular() || file.UncompressedSize64 == 0 || file.UncompressedSize64 > protocolbuild.MaxSource {
			problem(w, 409, "协议制品中的原始源码无效")
			return
		}
		source = file
	}
	if source == nil {
		problem(w, 404, "该协议版本未保存原始 Go 源码，可下载完整制品；后续请通过 Go 源码接入上传")
		return
	}
	reader, err := source.Open()
	if err != nil {
		problem(w, 409, "无法读取协议版本的原始源码")
		return
	}
	content, readErr := io.ReadAll(io.LimitReader(reader, protocolbuild.MaxSource+1))
	closeErr := reader.Close()
	if readErr != nil || closeErr != nil || len(content) == 0 || len(content) > protocolbuild.MaxSource {
		problem(w, 409, "协议版本的原始源码已损坏或超过大小限制")
		return
	}
	if build, ok := release.Artifact["build"].(map[string]any); ok {
		if expected, ok := build["sourceSha256"].(string); ok && expected != "" && !protocolDownloadHashMatchesV2(content, expected) {
			problem(w, 409, "协议原始源码 SHA-256 校验失败")
			return
		}
	}
	extension, contentType := ".go", "text/plain; charset=utf-8"
	if strings.HasSuffix(source.Name, ".zip") {
		extension, contentType = ".zip", "application/zip"
	}
	filename := release.ProtocolID + "-" + release.Version + "-source" + extension
	writeProtocolDownloadV2(w, content, filename, contentType)
	s.audit(r, "protocol.v2.source.download", "protocolRelease", release.ProtocolID+"@"+release.Version, nil)
}

// Downloads resolve the release in the authenticated tenant, then accept only
// the archive location generated by installation for that exact release. An
// os.Root additionally prevents filesystem links from escaping the data root.
func (s *Server) readProtocolDownloadV2(w http.ResponseWriter, r *http.Request) (model.ProtocolRelease, []byte, bool) {
	tenant, id, version := claims(r).TenantID, r.PathValue("id"), r.PathValue("version")
	var empty model.ProtocolRelease
	if !protocolSegmentV2.MatchString(tenant) || !protocolSegmentV2.MatchString(id) || !protocolSegmentV2.MatchString(version) {
		problem(w, 422, "协议标识或版本号无效")
		return empty, nil, false
	}
	release, err := s.engine.Repo.GetProtocolRelease(r.Context(), tenant, id, version)
	if err != nil {
		problem(w, 404, "协议版本不存在")
		return empty, nil, false
	}
	storedPath, _ := release.Artifact["packagePath"].(string)
	if storedPath == "" {
		problem(w, 404, "该协议版本没有可下载的协议制品")
		return empty, nil, false
	}
	expectedPath := filepath.Join("protocol-releases", tenant, id, version, "package.zip")
	if filepath.ToSlash(storedPath) != filepath.ToSlash(expectedPath) {
		problem(w, 409, "协议制品路径与当前租户及版本不匹配")
		return empty, nil, false
	}
	root, err := os.OpenRoot(s.cfg.DataDir)
	if err != nil {
		problem(w, 500, "无法读取协议制品目录")
		return empty, nil, false
	}
	defer root.Close()
	file, err := root.Open(expectedPath)
	if err != nil {
		problem(w, 404, "协议制品文件不存在或无法读取")
		return empty, nil, false
	}
	defer file.Close()
	info, err := file.Stat()
	if err != nil || !info.Mode().IsRegular() || info.Size() <= 0 || info.Size() > maxProtocolPackageV2 {
		problem(w, 409, "协议制品文件无效或超过大小限制")
		return empty, nil, false
	}
	data, err := io.ReadAll(io.LimitReader(file, maxProtocolPackageV2+1))
	if err != nil || int64(len(data)) > maxProtocolPackageV2 {
		problem(w, 500, "读取协议制品失败")
		return empty, nil, false
	}
	expectedHash, _ := release.Artifact["packageSha256"].(string)
	if !protocolDownloadHashMatchesV2(data, expectedHash) {
		problem(w, 409, "协议制品 SHA-256 校验失败")
		return empty, nil, false
	}
	return release, data, true
}

func protocolDownloadHashMatchesV2(data []byte, expected string) bool {
	digest := sha256.Sum256(data)
	return strings.EqualFold(hex.EncodeToString(digest[:]), expected)
}

func writeProtocolDownloadV2(w http.ResponseWriter, data []byte, filename, contentType string) {
	digest := sha256.Sum256(data)
	w.Header().Set("Content-Type", contentType)
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	w.Header().Set("Content-Length", strconv.Itoa(len(data)))
	w.Header().Set("X-Content-SHA256", hex.EncodeToString(digest[:]))
	w.Header().Set("Cache-Control", "no-store")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(data)
}
