package clusterplan

import (
	"fmt"
	"net"
	"strings"

	"gopkg.in/yaml.v3"
)

// DefaultImages are the pinned images a generated inventory uses; they match
// deploy/cluster/inventory.example.yaml.
func DefaultImages() Images {
	return Images{
		Platform: "iot-platform-api:offline", Web: "iot-platform-web:offline", Harness: "iot-deepseek-harness:offline",
		Backup: "iot-platform-backup:offline", Video: "iot-zlmediakit:offline",
		Redpanda: "redpandadata/redpanda:v25.2.11", EMQX: "emqx/emqx:5.8.8", Etcd: "quay.io/coreos/etcd:v3.5.21",
		Postgres: "ghcr.io/zalando/spilo-17:4.0-p2", Redis: "redis:7.4-alpine",
		ClickHouse: "clickhouse/clickhouse-server:25.7-alpine", Keeper: "clickhouse/clickhouse-keeper:25.7-alpine",
		MinIO: "quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z", Ollama: "ollama/ollama:0.11.4",
		Weaviate: "cr.weaviate.io/semitechnologies/weaviate:1.32.8", Prometheus: "prom/prometheus:v3.5.0",
		NodeExporter: "prom/node-exporter:v1.12.1", LB: "haproxy:3.0-alpine",
	}
}

// GenerateOptions are the wizard answers that shape a generated inventory.
type GenerateOptions struct {
	Name      string
	Addresses []string // node IPs in order; n1, n2, ...
	Video     bool
	Capacity  bool
}

// GenerateInventory lays out a cluster over the given nodes. Every node is
// its own fault domain (separate hosts). Quorum services use the first three
// nodes; single-instance services go to the last node, which carries the
// least quorum load; stateless roles are spread two or three wide.
func GenerateInventory(o GenerateOptions) (*Inventory, error) {
	n := len(o.Addresses)
	if n < 3 {
		return nil, fmt.Errorf("a cluster needs at least 3 nodes (got %d); use the single-node deployment for one server", n)
	}
	seen := map[string]bool{}
	inv := &Inventory{SchemaVersion: 1, Name: o.Name, Images: DefaultImages(), Env: map[string]string{"IOT_ADMIN_TENANTS": "tenant_001", "IOT_OPS_TENANTS": "tenant_001"}}
	names := make([]string, n)
	for i, a := range o.Addresses {
		a = strings.TrimSpace(a)
		if net.ParseIP(a) == nil {
			return nil, fmt.Errorf("node %d: %q is not an IP address", i+1, a)
		}
		if seen[a] {
			return nil, fmt.Errorf("node address %s is listed twice", a)
		}
		seen[a] = true
		names[i] = fmt.Sprintf("n%d", i+1)
		inv.Nodes = append(inv.Nodes, Node{Name: names[i], Address: a, FaultDomain: "host-" + names[i]})
	}
	first3 := names[:3]
	last := names[n-1]
	// span returns k nodes starting at offset, wrapping around.
	span := func(offset, k int) []string {
		out := make([]string, 0, k)
		for i := 0; i < min(k, n); i++ {
			out = append(out, names[(offset+i)%n])
		}
		return out
	}
	inv.Etcd = GroupSpec{Nodes: first3}
	inv.Postgres = PostgresSpec{Nodes: first3, Synchronous: true}
	inv.Redpanda = RedpandaSpec{Nodes: first3}
	inv.EMQX = GroupSpec{Nodes: first3}
	inv.Redis = RedisSpec{Master: names[0], Replicas: names[1:3], Sentinels: first3}
	switch {
	case n == 3:
		inv.ClickHouse = ClickHouseSpec{Shards: [][]string{first3}, Keeper: first3}
	case n < 6:
		inv.ClickHouse = ClickHouseSpec{Shards: [][]string{names[0:2], names[2:4]}, Keeper: span(1, 3)}
	default:
		inv.ClickHouse = ClickHouseSpec{Shards: [][]string{names[0:3], names[3:6]}, Keeper: span(n-3, 3)}
	}
	inv.MinIO = SingleSpec{Node: last}
	inv.Knowledge = SingleSpec{Node: last}
	inv.Backup = SingleSpec{Node: last}
	inv.Monitoring = SingleSpec{Node: last}
	if o.Video {
		inv.Video = SingleSpec{Node: last}
	}
	if o.Capacity {
		inv.Capacity = SingleSpec{Node: last}
	}
	inv.Harness = GroupSpec{Nodes: span(1, 2)}
	workers := min(n, 3)
	inv.Platform = PlatformSpec{
		Roles: map[string]RoleSpec{
			"api":       {Nodes: span(0, 2)},
			"gateway":   {Nodes: span(1, 2)},
			"parser":    {Nodes: span(0, workers)},
			"processor": {Nodes: span(0, workers)},
			"ai":        {Nodes: span(n-2, 2)},
			"jobs":      {Nodes: []string{names[0], last}},
		},
		Web: GroupSpec{Nodes: span(0, 2)},
	}
	inv.defaults()
	if _, err := inv.Validate(); err != nil {
		return nil, fmt.Errorf("generated layout is invalid:\n%w", err)
	}
	return inv, nil
}

// MarshalInventory writes an inventory with a short header.
func MarshalInventory(inv *Inventory) ([]byte, error) {
	b, err := yaml.Marshal(inv)
	if err != nil {
		return nil, err
	}
	header := "# Generated by scripts/cluster-up (cluster-render -generate). Edit placement here and\n# run cluster-up again; see deploy/cluster/inventory.example.yaml for every option.\n"
	return append([]byte(header), b...), nil
}
