package clusterplan

import (
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"gopkg.in/yaml.v3"
)

// optionalSecrets are left empty when missing: an operator supplies them.
var optionalSecrets = map[string]bool{"deepseekApiKey": true, "backupRestoreTargetDSN": true}

const secretAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

func randomSecret(n int) (string, error) {
	b := make([]byte, n)
	for i := range b {
		k, err := rand.Int(rand.Reader, big.NewInt(int64(len(secretAlphabet))))
		if err != nil {
			return "", err
		}
		b[i] = secretAlphabet[k.Int64()]
	}
	return string(b), nil
}

func placeholder(v string) bool {
	return strings.TrimSpace(v) == "" || strings.Contains(strings.ToLower(v), "change-me")
}

// EnsureSecrets creates or completes the private secrets file: every missing
// or placeholder value gets a random one (letters and digits, safe inside
// connection URLs). Existing values are never replaced, so re-running a
// deployment keeps the passwords the cluster was initialised with. The file
// is written with mode 0600. It returns the names of generated values.
func EnsureSecrets(path string) ([]string, error) {
	var s Secrets
	if _, err := os.Stat(path); err == nil {
		if s, err = LoadSecrets(path); err != nil {
			return nil, err
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	var generated []string
	v := reflect.ValueOf(&s).Elem()
	t := v.Type()
	for i := 0; i < t.NumField(); i++ {
		key := strings.Split(t.Field(i).Tag.Get("yaml"), ",")[0]
		if optionalSecrets[key] || !placeholder(v.Field(i).String()) {
			continue
		}
		var value string
		var err error
		switch key {
		case "minioRootUser":
			value = "iotadmin"
		case "videoCredentialKey":
			raw := make([]byte, 32)
			if _, err = rand.Read(raw); err == nil {
				value = base64.StdEncoding.EncodeToString(raw)
			}
		default:
			value, err = randomSecret(32)
		}
		if err != nil {
			return nil, err
		}
		v.Field(i).SetString(value)
		generated = append(generated, key)
	}
	if len(generated) == 0 {
		return nil, nil
	}
	body, err := yaml.Marshal(s)
	if err != nil {
		return nil, err
	}
	header := "# Cluster secrets generated by cluster-render -init-secrets. Keep mode 0600,\n# back this file up and never commit it: the deployed cluster depends on these values.\n# deepseekApiKey and backupRestoreTargetDSN are optional and filled by the operator.\n"
	if err = os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, err
	}
	tmp := path + ".tmp"
	if err = os.WriteFile(tmp, append([]byte(header), body...), 0o600); err != nil {
		return nil, err
	}
	_ = os.Chmod(tmp, 0o600)
	if err = os.Rename(tmp, path); err != nil {
		return nil, fmt.Errorf("write secrets: %w", err)
	}
	return generated, nil
}
