package clusterplan

import (
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"gopkg.in/yaml.v3"
)

// optionalSecrets are left empty when missing: an operator supplies them.
var optionalSecrets = map[string]bool{"deepseekApiKey": true, "embeddingApiKey": true, "backupRestoreTargetDSN": true, "backupRestoreMinioEndpoint": true, "backupRestoreMinioAccessKey": true, "backupRestoreMinioSecretKey": true}

const secretAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

func randomSecret(n int) (string, error) {
	b := make([]byte, n)
	for i := range b {
		k, err := rand.Int(rand.Reader, big.NewInt(int64(len(secretAlphabet))))
		if err != nil {
			return "", err
		}
		b[i] = secretAlphabet[k.Int64()]
	}
	return string(b), nil
}

func placeholder(v string) bool {
	return strings.TrimSpace(v) == "" || strings.Contains(strings.ToLower(v), "change-me")
}

// unifiedSecrets are the human-facing service passwords that one operator
// chosen password may set. Tokens and keys with length or format rules
// (JWT, Harness, video credential key, service-to-service tokens) stay random.
var unifiedSecrets = map[string]bool{
	"postgresPassword": true, "postgresSuperuserPassword": true, "postgresReplicationPassword": true,
	"redisPassword": true, "clickhousePassword": true, "minioRootPassword": true,
	"adminPassword": true, "emqxDashboardPassword": true,
}

// ErrServicePasswordConflict means the secrets file already holds different
// service passwords: the deployed databases use those, so they are kept.
var ErrServicePasswordConflict = errors.New("the secrets file already holds different service passwords; the deployed services use them, so the new password is not applied (changing database passwords is a separate operation)")

// ValidateServicePassword checks a unified service password: it is embedded
// in connection URLs and MinIO needs at least 8 characters.
func ValidateServicePassword(p string) error {
	if len(p) < 8 || !urlSafe.MatchString(p) {
		return errors.New("the service password needs at least 8 characters from letters, digits and . _ ~ -")
	}
	return nil
}

// EnsureSecrets creates or completes the private secrets file: every missing
// or placeholder value gets a random one (letters and digits, safe inside
// connection URLs). Existing values are never replaced, so re-running a
// deployment keeps the passwords the cluster was initialised with. The file
// is written with mode 0600. It returns the names of generated values.
func EnsureSecrets(path string) ([]string, error) {
	return EnsureSecretsWith(path, SecretInputs{})
}

// SecretInputs are operator-supplied values from the deployment wizard.
type SecretInputs struct {
	// ServicePassword sets every unset human-facing service password.
	ServicePassword string
	// DeepSeekAPIKey is stored when the file has none yet.
	DeepSeekAPIKey string
}

// EnsureSecretsWith is EnsureSecrets with wizard inputs applied to the
// values that are still unset.
func EnsureSecretsWith(path string, in SecretInputs) ([]string, error) {
	servicePassword := in.ServicePassword
	if servicePassword != "" {
		if err := ValidateServicePassword(servicePassword); err != nil {
			return nil, err
		}
	}
	var s Secrets
	if _, err := os.Stat(path); err == nil {
		if s, err = LoadSecrets(path); err != nil {
			return nil, err
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	var generated []string
	v := reflect.ValueOf(&s).Elem()
	t := v.Type()
	for i := 0; i < t.NumField(); i++ {
		key := strings.Split(t.Field(i).Tag.Get("yaml"), ",")[0]
		current := v.Field(i).String()
		if servicePassword != "" && unifiedSecrets[key] && !placeholder(current) && current != servicePassword {
			return nil, ErrServicePasswordConflict
		}
		if optionalSecrets[key] || !placeholder(current) {
			continue
		}
		var value string
		var err error
		switch {
		case servicePassword != "" && unifiedSecrets[key]:
			value = servicePassword
		case key == "minioRootUser":
			value = "iotadmin"
		case key == "videoCredentialKey":
			raw := make([]byte, 32)
			if _, err = rand.Read(raw); err == nil {
				value = base64.StdEncoding.EncodeToString(raw)
			}
		default:
			value, err = randomSecret(32)
		}
		if err != nil {
			return nil, err
		}
		v.Field(i).SetString(value)
		generated = append(generated, key)
	}
	if key := strings.TrimSpace(in.DeepSeekAPIKey); key != "" && s.DeepSeekAPIKey == "" {
		if strings.ContainsAny(key, "\n\r\"'$`\\ ") {
			return nil, errors.New("the DeepSeek API key contains characters that are not allowed")
		}
		s.DeepSeekAPIKey = key
		generated = append(generated, "deepseekApiKey")
	}
	if len(generated) == 0 {
		return nil, nil
	}
	body, err := yaml.Marshal(s)
	if err != nil {
		return nil, err
	}
	header := "# Cluster secrets generated by cluster-render -init-secrets. Keep mode 0600,\n# back this file up and never commit it: the deployed cluster depends on these values.\n# deepseekApiKey, embeddingApiKey and backupRestoreTargetDSN are optional and filled by the operator.\n"
	if err = os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, err
	}
	tmp := path + ".tmp"
	if err = os.WriteFile(tmp, append([]byte(header), body...), 0o600); err != nil {
		return nil, err
	}
	_ = os.Chmod(tmp, 0o600)
	if err = os.Rename(tmp, path); err != nil {
		return nil, fmt.Errorf("write secrets: %w", err)
	}
	return generated, nil
}
