<script setup>
import { computed, ref } from 'vue'
import { durationLabel, intervalStates, monitoringTime, reasonText, timelineLanes, trackLabels } from '../../monitoring/helpers.js'
const props = defineProps({ intervals: { type: Array, default: () => [] }, window: { type: Object, required: true }, devices: { type: Array, default: () => [] }, profiles: { type: Array, default: () => [] } })
const emit = defineEmits(['select'])
const detail = ref(false)
const lanes = computed(() => timelineLanes(props.intervals, props.window, detail.value))
const deviceName = id => props.devices.find(row => row.id === id)?.name || id
const tooltip = row => `${deviceName(row.deviceId)} · ${row.attributeId || '策略合并'} · ${trackLabels[row.track] || row.track}\n${monitoringTime(row.start)} 至 ${monitoringTime(row.end)}\n${intervalStates[row.state]} · ${durationLabel(row.end-row.start)}\n${(row.reasons || []).map(reasonText).join('；')}`
</script>
<template><div class="monitor-card monitor-stack"><div class="monitor-toolbar"><h3>连接与有效数据时间线</h3><ui-checkbox v-model="detail">展开逐属性区间</ui-checkbox></div><div class="monitor-legend"><span v-for="[state,label] in Object.entries(intervalStates)" :key="state"><i :class="'monitor-state-'+state"/>{{label}}</span></div><p class="monitor-hint">接收依据采用 receivedAt，有效数据从真实 availableAt 起算并受事件时效限制。区间为空的部分表示本页没有已返回记录，具体覆盖以固定快照为准。</p><div v-if="lanes.length" class="monitor-timeline-scroll"><div class="monitor-timeline"><div class="monitor-time-head"><span>{{monitoringTime(window.start)}}</span><span>{{monitoringTime(window.end)}}</span></div><div v-for="lane in lanes" :key="lane.key" class="monitor-timeline-row"><div class="monitor-lane-label">{{deviceName(lane.deviceId)}}<small>{{lane.attributeId || '策略合并'}} · {{trackLabels[lane.track] || lane.track}}</small></div><div class="monitor-time-track"><button v-for="piece in lane.items" :key="piece.id" class="monitor-time-piece" :class="'monitor-state-'+piece.state" :style="{left:piece.left+'%',width:piece.width+'%'}" :title="tooltip(piece)" :aria-label="tooltip(piece)" @click="emit('select',piece)"><span>{{intervalStates[piece.state]}}</span></button></div></div></div></div><ui-empty v-else :description="detail?'暂无可展示的逐属性区间，请核对策略与来源覆盖。':'暂无可展示的合并区间，请核对快照和来源限制。'"/></div></template>
<style scoped>.monitor-legend{display:flex;gap:12px;flex-wrap:wrap;font-size:12px}.monitor-legend span{display:flex;align-items:center;gap:5px}.monitor-legend i{display:inline-block;width:12px;height:12px;border-radius:2px}.monitor-state-AVAILABLE{background:#57ac92}.monitor-state-UNAVAILABLE{background:#de867c}.monitor-state-UNKNOWN{background:repeating-linear-gradient(45deg,#c1c7d0,#c1c7d0 4px,#e0e4e9 4px,#e0e4e9 8px)}.monitor-state-EXCLUDED{background:#8e9eb9}.monitor-state-NOT_APPLICABLE{background:#dadde3}.monitor-timeline-scroll{overflow-x:auto;min-width:0}.monitor-timeline{min-width:640px}.monitor-time-head{display:flex;justify-content:space-between;font-size:11px;color:var(--text-muted);padding-left:170px}.monitor-timeline-row{display:grid;grid-template-columns:160px minmax(0,1fr);gap:10px;align-items:center;margin-top:10px}.monitor-lane-label{font-size:12px;overflow-wrap:anywhere}.monitor-lane-label small{display:block;color:var(--text-muted);font-size:11px}.monitor-time-track{height:28px;position:relative;background:var(--surface-muted);border:1px solid var(--border);border-radius:4px;overflow:hidden}.monitor-time-piece{position:absolute;top:0;bottom:0;border:0;border-right:1px solid var(--surface);padding:0;cursor:pointer;overflow:hidden;color:#17392c;min-width:1px}.monitor-time-piece>span{font-size:10px;white-space:nowrap}.monitor-state-UNKNOWN>span,.monitor-state-EXCLUDED>span,.monitor-state-NOT_APPLICABLE>span{color:#263447}.monitor-time-piece:focus-visible{outline:2px solid var(--primary);outline-offset:-2px}</style>
