package core

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/url"
	"strconv"
	"strings"
	"time"

	"iot-platform/internal/externaldata"
	"iot-platform/internal/model"
)

// externalSourceId is stamped only by trusted external-data ingestion. The
// legacy video ingress strips the reserved marker before saving caller Raw.
func externalVideoSourceID(event model.VideoAlarmEvent) string {
	id, _ := event.Raw["externalSourceId"].(string)
	return id
}

func (e *Engine) sourceMediaHosts(ctx context.Context, event model.VideoAlarmEvent) ([]string, error) {
	id := externalVideoSourceID(event)
	if id == "" || event.TenantID == "" || event.Source != id {
		return nil, errors.New("外部媒体来源标识无效")
	}
	entry, err := e.Repo.ExternalDataStore().Get(ctx, event.TenantID, "source", id)
	if err != nil {
		return nil, errors.New("外部媒体来源不可用")
	}
	var source externaldata.Source
	if json.Unmarshal(entry.Body, &source) != nil || !source.Enabled || source.ID != id {
		return nil, errors.New("外部媒体来源已停用或配置无效")
	}
	return source.AllowedHosts, nil
}

func parseVideoMediaURL(raw string) (*url.URL, error) {
	u, err := url.Parse(raw)
	if err != nil || u == nil || u.Hostname() == "" || u.User != nil || u.Fragment != "" || (u.Scheme != "http" && u.Scheme != "https") {
		return nil, errors.New("媒体地址须为不含内嵌凭据的 HTTP/HTTPS URL")
	}
	if port := u.Port(); port != "" {
		p, err := strconv.Atoi(port)
		if err != nil || p < 1 || p > 65535 {
			return nil, errors.New("媒体地址端口无效")
		}
	}
	return u, nil
}

func videoMediaHostPort(u *url.URL) string {
	port := u.Port()
	if port == "" {
		port = "80"
		if u.Scheme == "https" {
			port = "443"
		}
	}
	return net.JoinHostPort(strings.ToLower(u.Hostname()), port)
}

func (e *Engine) videoMediaURLAllowed(ctx context.Context, event model.VideoAlarmEvent, u *url.URL) error {
	if _, err := parseVideoMediaURL(u.String()); err != nil {
		return err
	}
	if externalVideoSourceID(event) == "" {
		if !e.videoHostAllowed(u.Hostname()) {
			return errors.New("媒体主机未列入视频允许名单")
		}
		return nil
	}
	hosts, err := e.sourceMediaHosts(ctx, event)
	if err != nil {
		return err
	}
	target := videoMediaHostPort(u)
	for _, host := range hosts {
		if strings.EqualFold(strings.TrimSpace(host), target) {
			return nil
		}
	}
	return errors.New("媒体主机及端口未列入外部系统允许名单")
}

func (e *Engine) validateExternalVideoMediaURLs(ctx context.Context, event model.VideoAlarmEvent) error {
	if _, err := e.sourceMediaHosts(ctx, event); err != nil {
		return err
	}
	for _, raw := range []string{event.SnapshotURL, event.VideoClipURL} {
		if raw == "" {
			continue
		}
		u, err := parseVideoMediaURL(raw)
		if err != nil {
			return err
		}
		if err = e.videoMediaURLAllowed(ctx, event, u); err != nil {
			return err
		}
	}
	return nil
}

func sameVideoEvent(value any, event model.VideoAlarmEvent) bool {
	var linked model.VideoAlarmEvent
	switch v := value.(type) {
	case model.VideoAlarmEvent:
		linked = v
	case *model.VideoAlarmEvent:
		if v == nil {
			return false
		}
		linked = *v
	default:
		raw, err := json.Marshal(value)
		if err != nil || json.Unmarshal(raw, &linked) != nil {
			return false
		}
	}
	return linked.EventID != "" && linked.EventID == event.EventID && linked.TenantID == event.TenantID
}

func videoMediaAttemptCount(v model.VideoAlarmEvent) int {
	var n int
	switch value := v.Raw["mediaAttempts"].(type) {
	case int:
		n = value
	case int64:
		n = int(value)
	case float64:
		n = int(value)
	case json.Number:
		a, _ := value.Int64()
		n = int(a)
	}
	return max(0, min(n, 1000))
}

// QueueVideoMediaRetry only updates the durable event. Downloads remain in the
// background singleton worker and use the latest source allowlist.
func (e *Engine) QueueVideoMediaRetry(ctx context.Context, tenant, eventID string) (model.VideoAlarmEvent, error) {
	v, err := e.Repo.GetVideoEvent(ctx, tenant, eventID)
	if err != nil {
		return v, err
	}
	if v.SnapshotURL == "" && v.VideoClipURL == "" {
		return v, errors.New("该事件没有截图或录像")
	}
	raw := make(map[string]any, len(v.Raw)+3)
	for key, value := range v.Raw {
		raw[key] = value
	}
	v.Raw = raw
	v.Raw["mediaTransferStatus"] = "PENDING"
	v.Raw["mediaAttempts"] = 0
	v.Raw["mediaRetryAt"] = 0
	v.Raw["mediaLastAttemptAt"] = 0
	delete(v.Raw, "mediaTransferError")
	return v, e.Repo.UpdateVideoEvent(ctx, v)
}

// VideoMediaObjectReference permits only the exact object prefix generated by
// transferVideoURL for this event and attachment. Caller-supplied paths cannot
// turn an alarm's media link into a general archive download endpoint.
func VideoMediaObjectReference(v model.VideoAlarmEvent, kind string) (string, string, error) {
	raw := ""
	switch kind {
	case "snapshot":
		raw = v.SnapshotURL
	case "clip":
		raw = v.VideoClipURL
	default:
		return "", "", errors.New("媒体类型须为 snapshot 或 clip")
	}
	u, err := url.Parse(raw)
	if err != nil || u == nil || (u.Scheme != "local" && u.Scheme != "minio") || u.Host != "video-alarm" || u.User != nil || u.RawQuery != "" || u.Fragment != "" {
		return "", "", errors.New("媒体尚未归档")
	}
	key := strings.TrimPrefix(u.Path, "/")
	base := fmt.Sprintf("%s/%s/%s/%s-%s", safeSegment(v.TenantID), time.UnixMilli(v.EventTime).UTC().Format("2006/01/02"), safeSegment(v.EventID), kind, safeSegment(v.CameraID))
	if !strings.HasPrefix(key, base) {
		return "", "", errors.New("媒体归档位置与事件不符")
	}
	suffix := strings.TrimPrefix(key, base)
	if suffix != "" && (!strings.HasPrefix(suffix, ".") || len(suffix) > 10 || strings.ContainsAny(suffix, "/\\")) || strings.Contains(key, "/../") {
		return "", "", errors.New("媒体归档位置无效")
	}
	return "video-alarm", key, nil
}
