import assert from 'node:assert/strict'
import test from 'node:test'
import { candidateDraft, candidatePayload, countLabel, datasetPayload, experimentPayload, inputChart, inputSamples, labelRatio, publicationPayload, semantics, unwrapOutputs } from '../src/rulelab/helpers.js'
const start=Date.parse('2026-10-01T00:00:00Z'),rule={id:'rule',productId:'product',name:'压力异常',description:'已登记规则',alarmType:'FAULT',level:'warning',match:'all',durationSeconds:3,enabled:true,conditions:[{property:'pressure',operator:'gt',value:100.5}],recovery:[{property:'pressure',operator:'lte',value:100}],actions:[{type:'NOTIFY'}]},revision={id:'r1',ruleId:'rule',version:7,rule},dataset={id:'dataset',status:'SUCCEEDED',deviceIds:['d1'],clockPolicy:'EVENT_AS_PROCESSING'}
const form=()=>({resourceId:'experiment',expectedVersion:0,scope:'personal',baselineRevisionIds:['r1'],baselinePolicy:'FIXED_REVISIONS',candidateRuleId:'rule',candidate:candidateDraft(rule),candidateEnabled:true,hypothesis:'候选阈值提高后核实少触发的周期',labelRevisionIds:[],policyVersion:'matching-v1',toleranceSeconds:.125,matchTimeBasis:'EVENT',split:'TUNING',representativeConfirmed:false,representativenessBasis:''})
test('label evaluation preserves independent hand-counted denominators and zero N/A',()=>{const v={status:'EVALUABLE',tp:2,alarmCycles:4,realEvents:5,precision:.5,recall:.4};assert.equal(labelRatio(v,'precision'),'50.0%');assert.equal(labelRatio(v,'recall'),'40.0%');assert.equal(labelRatio({...v,alarmCycles:0,precision:null},'precision'),'不适用');assert.equal(labelRatio({...v,realEvents:0,recall:1},'recall'),'不适用')})
test('unknown initial state or absent representative labels never display supplied accuracy',()=>{for(const status of ['NOT_EVALUABLE','UNKNOWN',undefined])assert.equal(labelRatio({status,alarmCycles:1,realEvents:1,precision:1},'precision'),'证据不足');for(const precision of [undefined,NaN,Infinity,1.1,-.1])assert.equal(labelRatio({status:'EVALUABLE',alarmCycles:1,precision},'precision'),'证据不足')})
test('dataset freezes explicit real clocks, semantics and warmup with Unixms',()=>{const v={deviceIds:['d2','d1','d1'],range:[start,start+40000],warmupStart:start-5000,timeBasis:'RECEIVED',clockPolicy:'RECORDED_TRACE',semanticsVersion:Object.keys(semantics)[1],initialStatePolicy:'TRACE_INITIAL'};const original=structuredClone(v),out=datasetPayload(v,'fixed');assert.deepEqual(out.deviceIds,['d1','d2']);assert.equal(out.start,start);assert.equal(out.warmupStart,start-5000);assert.equal(out.idempotencyKey,'fixed');assert.deepEqual(v,original);assert.throws(()=>datasetPayload({...v,warmupStart:start+1},'key'),/预热/);assert.throws(()=>datasetPayload({...v,semanticsVersion:'V2'},'key'),/语义/);assert.throws(()=>datasetPayload({...v,deviceIds:[]},'key'),/明确设备/)})
test('candidate retains full rule arrays and remains disabled without mutating baseline',()=>{const original=structuredClone(rule),draft=candidateDraft(rule);draft.conditions=JSON.stringify([{property:'pressure',operator:'gt',value:101.5}]);const value=candidatePayload(draft);assert.equal(value.enabled,false);assert.equal(value.conditions[0].value,101.5);assert.deepEqual(value.recovery,rule.recovery);assert.deepEqual(value.actions,rule.actions);assert.deepEqual(rule,original);assert.throws(()=>candidatePayload({...draft,conditions:'{}'}),/结构化数组/);assert.throws(()=>candidatePayload({...draft,durationSeconds:.5}),/整数/)})
test('experiment binds immutable target and labels and separate candidateEnabled',()=>{const v=form(),original=structuredClone(v),out=experimentPayload(v,dataset,[revision]);assert.equal(out.body.candidate.enabled,false);assert.equal(out.body.candidateEnabled,true);assert.equal(out.body.evaluationPolicy.toleranceMs,125);assert.equal(out.body.evaluationPolicy.extraCyclePolicy,'COUNT_EACH_CYCLE');assert.deepEqual(out.body.baselineRevisionIds,['r1']);assert.deepEqual(out.deviceIds,['d1']);assert.deepEqual(v,original)})
test('duplicate rule baseline versions and target substitution are rejected',()=>{const v=form();assert.throws(()=>experimentPayload({...v,baselineRevisionIds:['r1','r2']},dataset,[revision,{...revision,id:'r2',version:8}]),/仅选择一个/);assert.throws(()=>experimentPayload({...v,candidate:{...v.candidate,id:'other'}},dataset,[revision]),/同目标/);assert.throws(()=>experimentPayload(v,{...dataset,status:'RUNNING'},[revision]),/固定完成/);assert.throws(()=>experimentPayload({...v,baselinePolicy:'RECORDED_ACTIVATIONS'},dataset,[revision]),/trace/);assert.throws(()=>experimentPayload({...v,representativeConfirmed:true},dataset,[revision]),/代表性/)})
test('fixed chart has original finite numeric values and distinct event/reception/availability',()=>{const inputs=[{id:'a',message:{deviceId:'d1',timestamp:start,properties:{pressure:4}},receivedAt:start+20,availableAt:start+1000},{id:'b',message:{deviceId:'d2',timestamp:start,properties:{pressure:8}}},{id:'c',message:{deviceId:'d1',timestamp:start+1,properties:{pressure:'9'}},receivedAt:start+30},{id:'d',message:{deviceId:'d1',timestamp:start+2,properties:{pressure:Infinity}}}];assert.deepEqual(inputSamples(inputs,'d1','pressure','event').map(row=>[row.clockAt,row.value]),[[start,4]]);assert.equal(inputSamples(inputs,'d1','pressure','received')[0].clockAt,start+20);assert.equal(inputSamples(inputs,'d1','pressure','available')[0].clockAt,start+1000);assert.equal(inputSamples(inputs,'d2','pressure','received').length,0)})
test('curve keeps units and version changes separate without changing membership counts',()=>{const row=(id,at,value,unit,version)=>({id,message:{deviceId:'d1',timestamp:start+at,properties:{p:value}},units:{p:unit},protocolVersion:version,configurationVersion:'cfg'});const inputs=[row('a',0,1,'kPa','v1'),row('b',1000,2,'Pa','v2'),row('c',1000,3,'Pa','v2'),row('d',2000,4,'kPa','v1')],original=structuredClone(inputs),result=inputChart(inputs,'d1','p','event');assert.deepEqual(result.times,[start,start+1000,start+2000]);assert.deepEqual(result.series.map(s=>s.values),[[1,null,4],[null,2,null]]);assert.equal(result.collapsedCount,1);assert.deepEqual(inputs,original);assert.equal(inputSamples(inputs,'d1','p','event').length,4)})
test('publication fixes candidate enabled state, immutable baseline CAS and cannot alter saved body',()=>{const saved={id:'e1',body:experimentPayload(form(),dataset,[revision]).body},original=structuredClone(saved),payload=publicationPayload(saved,[revision],'  现场依据已核实  ');assert.equal(payload.expectedBaselineVersion,7);assert.equal(payload.experimentId,'e1');assert.equal(payload.rule.enabled,true);assert.equal(payload.reason,'现场依据已核实');assert.equal(saved.body.candidate.enabled,false);assert.deepEqual(saved,original);assert.throws(()=>publicationPayload(saved,[], 'reason'),/固定候选/);assert.throws(()=>publicationPayload(saved,[revision],''),/原因/)})
test('output authority and absent counters remain unknown',()=>{assert.deepEqual(unwrapOutputs([{id:'outer',deviceId:'d1',body:{id:'inner',deviceId:'other',newCycles:2}}]),[{id:'outer',deviceId:'d1',newCycles:2}]);for(const v of [null,undefined,NaN,Infinity,-1,.5])assert.equal(countLabel(v),'未知');assert.equal(countLabel(0),'0')})
