<script setup>
import { onMounted, ref } from 'vue'
import { api, formatTime, notifyError, pretty } from '../api'
import { ElMessageBox, ElMessage } from 'element-plus'
const props=defineProps({deviceId:String})
const emit=defineEmits(['close','navigate'])
const histories=ref([]),events=ref([]),commands=ref([]),historyTotal=ref(0),historyPage=ref(1),eventTotal=ref(0),eventPage=ref(1),commandTotal=ref(0),commandPage=ref(1),credential=ref(null),commandType=ref(''),commandData=ref('{}'),pendingCommand=ref(null)
const data=ref(null),busy=ref(false),command=ref('{"type":""}'),commandResult=ref(null)
const base=()=>`/api/v1/device-registry/${encodeURIComponent(props.deviceId)}`
async function loadHistory(){const x=await api(`${base()}/history?page=${historyPage.value}`);histories.value=x.items;historyTotal.value=x.total}
async function loadEvents(){const x=await api(`${base()}/history?kind=event&page=${eventPage.value}`);events.value=x.items;eventTotal.value=x.total}
async function loadCommands(){const x=await api(`${base()}/commands?page=${commandPage.value}`);commands.value=x.items;commandTotal.value=x.total}
async function pageLoad(fn){try{await fn()}catch(e){notifyError(e)}}
async function rotate(){try{await ElMessageBox.confirm('重新生成后旧凭据立即在平台停用；Broker 撤销结果可在下方查看。','重新生成凭据');const x=await api(`${base()}/credentials`,{method:'POST'});credential.value=x.credential;await load()}catch(e){if(e!=='cancel'&&e!=='close')notifyError(e)}}
async function sendMQTT(){busy.value=true;try{const body={type:commandType.value,data:JSON.parse(commandData.value)};const signature=JSON.stringify(body);if(!pendingCommand.value||pendingCommand.value.signature!==signature)pendingCommand.value={signature,id:crypto.randomUUID()};commandResult.value=await api(`${base()}/commands`,{method:'POST',body:JSON.stringify({...body,id:pendingCommand.value.id})});await loadCommands()}catch(e){notifyError(e)}finally{busy.value=false}}
function newCommand(){pendingCommand.value=null;commandResult.value=null}
async function load(){busy.value=true;try{data.value=await api(`/api/v1/device-registry/${encodeURIComponent(props.deviceId)}/connection`);await Promise.all([loadHistory(),loadEvents(),loadCommands()])}catch(e){notifyError(e)}finally{busy.value=false}}
async function disable(){try{await ElMessageBox.confirm('禁用后设备不能使用此凭据上报或换取 MQTT 令牌。','禁用设备凭据');await api(`/api/v1/device-registry/${encodeURIComponent(props.deviceId)}/credentials`,{method:'DELETE'});ElMessage.success('凭据已禁用');await load()}catch(e){if(e!=='cancel'&&e!=='close')notifyError(e)}}
async function send(){busy.value=true;try{commandResult.value=await api(`/api/v2/device-access-profiles/${encodeURIComponent(data.value.profile.id)}/devices/${encodeURIComponent(props.deviceId)}/commands`,{method:'POST',body:JSON.stringify(JSON.parse(command.value))})}catch(e){notifyError(e)}finally{busy.value=false}}
onMounted(load)
</script>
<template>
<el-drawer :model-value="true" title="设备连接与数据" size="min(780px, 96vw)" @close="emit('close')"><div v-loading="busy"><el-button :loading="busy" @click="load">刷新</el-button><template v-if="data"><el-descriptions :column="2" border><el-descriptions-item label="设备">{{data.device.name}}</el-descriptions-item><el-descriptions-item label="产品">{{data.product.name}}</el-descriptions-item><el-descriptions-item label="Connector">{{data.connector||'历史设备'}}</el-descriptions-item><el-descriptions-item label="创建时间">{{formatTime(data.device.createdAt)}}</el-descriptions-item><el-descriptions-item label="Protocol">{{data.protocolId||'—'}}</el-descriptions-item><el-descriptions-item label="Protocol Version">{{data.protocolVersion||'—'}}</el-descriptions-item><el-descriptions-item label="Collector / Edge">{{data.edgeNode?.name||data.profile?.edgeNodeId||data.profile?.collectorId||'—'}}</el-descriptions-item><el-descriptions-item label="运行时">{{data.profile?.runtimeStatus||'按上报更新'}}</el-descriptions-item><el-descriptions-item label="最后上报">{{formatTime(data.connection.lastSeenAt)}}</el-descriptions-item><el-descriptions-item label="连接状态">{{data.connection.connectionStatus||'未知'}}</el-descriptions-item><el-descriptions-item label="最后连接">{{formatTime(data.connection.lastConnectAt)}}</el-descriptions-item><el-descriptions-item label="最后断开">{{formatTime(data.connection.lastDisconnectAt)}}</el-descriptions-item><el-descriptions-item label="最近错误">{{data.profile?.lastError||'—'}}</el-descriptions-item></el-descriptions><h4>在线会话</h4><el-table :data="data.sessions" empty-text="暂无已识别的在线会话"><el-table-column prop="remoteAddress" label="远端地址"/><el-table-column label="最后有效报文"><template #default="{row}">{{formatTime(row.lastSeenAt)}}</template></el-table-column></el-table><h4>连接与状态历史</h4><el-table :data="histories" empty-text="暂无状态变更"><el-table-column label="记录时间"><template #default="{row}">{{formatTime(row.recordedAt)}}</template></el-table-column><el-table-column prop="state.connectionStatus" label="连接"/><el-table-column prop="state.businessStatus" label="业务"/><el-table-column prop="state.statusSource" label="来源"/></el-table><el-pagination v-model:current-page="historyPage" :page-size="20" :total="historyTotal" layout="prev, pager, next" @current-change="pageLoad(loadHistory)"/>
<h4>最近事件</h4><pre v-for="event in events" :key="event.messageId">{{formatTime(event.timestamp)}} · {{event.messageId}}
{{pretty(event.event)}}</pre><p v-if="!events.length">暂无事件</p><el-pagination v-model:current-page="eventPage" :page-size="20" :total="eventTotal" layout="prev, pager, next" @current-change="pageLoad(loadEvents)"/>
<h4>最新属性</h4><pre>{{pretty(data.latestProperties?.[0]?.properties||{})}}</pre><h4>最新报文</h4><pre>{{pretty(data.latest)}}</pre><el-button @click="emit('navigate','raw',{deviceId:props.deviceId})">原始报文与回放</el-button><el-button @click="emit('navigate','alarms',{deviceId:props.deviceId})">设备告警</el-button><el-button :disabled="!data.credentialEnabled" @click="disable">禁用凭据</el-button><el-button @click="rotate">重新生成凭据</el-button><pre v-if="credential">仅本次显示，请妥善保存：{{pretty(credential)}}</pre><p v-for="revocation in data.revocations" :key="revocation.id">旧凭据 Broker 撤销：{{revocation.status==='REVOKED'?'已完成':'待完成（平台已停用旧凭据）'}}</p>
<template v-if="data.connector==='MQTT'"><h4>MQTT 命令</h4><p>已发送不代表设备执行成功。回执到达后刷新可查看结果；重试相同命令不会再次下发。</p><el-select v-if="data.product.thingModel?.commands?.length" v-model="commandType" placeholder="命令类型"><el-option v-for="c in data.product.thingModel.commands" :key="c.identifier" :value="c.identifier" :label="c.name||c.identifier"/></el-select><el-input v-else v-model="commandType" placeholder="命令类型"/><el-input v-model="commandData" type="textarea" :rows="4" placeholder="命令参数 JSON"/><el-button :disabled="!data.mqttCommandAvailable||!data.credentialEnabled" :loading="busy" @click="sendMQTT">发送 MQTT 命令</el-button><el-button v-if="pendingCommand" @click="newCommand">开始一条新命令</el-button><pre v-if="commandResult">{{pretty(commandResult)}}</pre><el-table :data="commands"><el-table-column prop="type" label="命令"/><el-table-column prop="status" label="状态"/><el-table-column label="回执"><template #default="{row}">{{pretty(row.reply||{})}}</template></el-table-column></el-table><el-pagination v-model:current-page="commandPage" :page-size="20" :total="commandTotal" layout="prev, pager, next" @current-change="pageLoad(loadCommands)"/></template>
<template v-if="data.sessions.length&&data.profile&&data.canCommand"><h4>协议命令</h4><el-input v-model="command" type="textarea" :rows="4" placeholder="按协议文档填写命令"/><el-button :loading="busy" @click="send">发送命令</el-button><pre v-if="commandResult">{{pretty(commandResult)}}</pre></template></template></div></el-drawer>
</template>
<style scoped>.el-descriptions{margin-top:16px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--el-fill-color-light);padding:12px}</style>
