<script setup>
import { onMounted, ref } from 'vue'
import { api, formatTime, notifyError, pretty } from '../api'
import { ElMessageBox, ElMessage } from 'element-plus'
const props=defineProps({deviceId:String})
const emit=defineEmits(['close','navigate'])
const data=ref(null),busy=ref(false),command=ref('{"type":""}'),commandResult=ref(null)
async function load(){busy.value=true;try{data.value=await api(`/api/v1/device-registry/${encodeURIComponent(props.deviceId)}/connection`)}catch(e){notifyError(e)}finally{busy.value=false}}
async function disable(){try{await ElMessageBox.confirm('禁用后设备不能使用此凭据上报或换取 MQTT 令牌。','禁用设备凭据');await api(`/api/v1/device-registry/${encodeURIComponent(props.deviceId)}/credentials`,{method:'DELETE'});ElMessage.success('凭据已禁用');await load()}catch(e){if(e!=='cancel'&&e!=='close')notifyError(e)}}
async function send(){busy.value=true;try{commandResult.value=await api(`/api/v2/device-access-profiles/${encodeURIComponent(data.value.profile.id)}/devices/${encodeURIComponent(props.deviceId)}/commands`,{method:'POST',body:JSON.stringify(JSON.parse(command.value))})}catch(e){notifyError(e)}finally{busy.value=false}}
onMounted(load)
</script>
<template>
<el-drawer :model-value="true" title="设备连接与数据" size="min(780px, 96vw)" @close="emit('close')"><div v-loading="busy"><el-button :loading="busy" @click="load">刷新</el-button><template v-if="data"><el-descriptions :column="2" border><el-descriptions-item label="设备">{{data.device.name}}</el-descriptions-item><el-descriptions-item label="产品">{{data.product.name}}</el-descriptions-item><el-descriptions-item label="Connector">{{data.connector||'历史设备'}}</el-descriptions-item><el-descriptions-item label="创建时间">{{formatTime(data.device.createdAt)}}</el-descriptions-item><el-descriptions-item label="Protocol">{{data.protocolId||'—'}}</el-descriptions-item><el-descriptions-item label="Protocol Version">{{data.protocolVersion||'—'}}</el-descriptions-item><el-descriptions-item label="Collector / Edge">{{data.profile?.collectorId||'—'}}</el-descriptions-item><el-descriptions-item label="运行时">{{data.profile?.runtimeStatus||'按上报更新'}}</el-descriptions-item><el-descriptions-item label="最后上报">{{formatTime(data.connection.lastSeenAt)}}</el-descriptions-item><el-descriptions-item label="连接状态">{{data.connection.connectionStatus||'未知'}}</el-descriptions-item><el-descriptions-item label="最后连接">{{formatTime(data.connection.lastConnectAt)}}</el-descriptions-item><el-descriptions-item label="最后断开">{{formatTime(data.connection.lastDisconnectAt)}}</el-descriptions-item><el-descriptions-item label="最近错误">{{data.profile?.lastError||'—'}}</el-descriptions-item></el-descriptions><h4>在线会话</h4><el-table :data="data.sessions" empty-text="暂无已识别的在线会话"><el-table-column prop="remoteAddress" label="远端地址"/><el-table-column label="最后有效报文"><template #default="{row}">{{formatTime(row.lastSeenAt)}}</template></el-table-column></el-table><h4>最新属性 / 事件</h4><pre>{{pretty(data.latest)}}</pre><el-button @click="emit('navigate','raw',{deviceId:props.deviceId})">原始报文与回放</el-button><el-button @click="emit('navigate','alarms',{deviceId:props.deviceId})">设备告警</el-button><el-button :disabled="!data.credentialEnabled" @click="disable">禁用凭据</el-button><template v-if="data.sessions.length&&data.profile&&data.canCommand"><h4>协议命令</h4><el-input v-model="command" type="textarea" :rows="4" placeholder="按协议文档填写命令"/><el-button :loading="busy" @click="send">发送命令</el-button><pre v-if="commandResult">{{pretty(commandResult)}}</pre></template></template></div></el-drawer>
</template>
<style scoped>.el-descriptions{margin-top:16px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--el-fill-color-light);padding:12px}</style>
