import { stateLabel as factStateLabel, stateTone, runIsActive } from '../quality/helpers.js'
import { monitoringTime, durationLabel } from '../monitoring/helpers.js'
export { stateTone, runIsActive, durationLabel }
export const responseTime=monitoringTime
export const sourceLabels={DRILL:'隔离演练',REAL_CASE:'真实处置案例',MANUAL:'人工现场记录',SYSTEM:'已提交系统操作',EXERCISE:'演练内部模拟'}
export const statusLabels={DRAFT:'草稿',PUBLISHED:'已发布',RUNNING:'执行中',RECORDING:'记录中',ENDED:'已结束',REVIEWED:'已有正式复盘',ARCHIVED:'已归档',CANCELLED:'已取消',OPEN:'待处理',IN_PROGRESS:'处理中',PENDING_VERIFICATION:'待独立验收',DONE:'已验收完成',UNVERIFIED:'未确认',CONFIRMED:'已确认',DISPUTED:'存在争议',NOT_RECORDED:'未记录',TIME_CONFLICT:'时间异常',EVIDENCE_MISSING:'规定证据缺失',PREREQUISITE_UNCONFIRMED:'前置步骤未确认',WITHIN_UNIT_TARGET:'单位目标内',EXCEEDS_UNIT_TARGET:'超过单位目标',NOT_EVALUATED:'缺少评价依据',PASSED:'验收通过',FAILED:'验收失败',PRODUCTION:'生产来源',EXERCISE:'演练内部记录',TEST:'明确测试关联',UNCLASSIFIED:'未分类'}
export const stateLabel=value=>statusLabels[value]||factStateLabel(value)
export const evidenceKinds={MANUAL_RECORD:'人工登记资料',ATTACHMENT:'受权附件',ALARM_LIFECYCLE:'具体告警事务事件',ALARM_REPORT:'单次设备告警上报',RAW_MESSAGE:'具体原始报文',ALARM:'生产告警资料'}
export const systemEvents={ALARM_ACKNOWLEDGED:'平台告警确认',ALARM_RECOVERED:'告警恢复事务',ALARM_CLOSED:'告警关闭事务'}
export const revisionBody=value=>({...value.body,revisionId:value.id,resourceId:value.resourceId,version:value.version,deviceIds:value.deviceIds,createdAt:value.createdAt,hash:value.hash})
export const lines=value=>String(value||'').split('\n').map(v=>v.trim()).filter(Boolean)
export function procedureDraft(row){const b=row?.body||{};return{resourceId:row?.resourceId||'',expectedVersion:row?.version||0,deviceIds:[...(row?.deviceIds||[])],name:b.name||'',scenario:b.scenario||'',steps:(b.steps||[{id:'',name:'',role:'',required:true,prerequisites:[],requiredEvidence:[],clockStart:'RUN_START'}]).map(s=>({...s,prerequisites:[...(s.prerequisites||[])],requiredEvidence:[...(s.requiredEvidence||[])],targetSeconds:s.targetMs?s.targetMs/1000:null}))}}
export function procedurePayload(form,key){const deviceIds=[...new Set(form.deviceIds||[])].sort();if(!deviceIds.length||!form.name.trim()||!form.scenario.trim()||!form.steps.length)throw Error('请明确设备范围、流程名称、场景与实际步骤');const steps=form.steps.map(s=>{if(!s.id.trim()||!s.name.trim()||!s.role.trim()||(s.targetSeconds!=null&&(!Number.isSafeInteger(Number(s.targetSeconds)*1000)||s.targetSeconds<0)))throw Error('步骤标识、名称、责任岗位与单位目标无效');return{id:s.id.trim(),name:s.name.trim(),role:s.role.trim(),required:!!s.required,prerequisites:[...new Set(s.prerequisites||[])],requiredEvidence:[...new Set(s.requiredEvidence||[])],clockStart:s.clockStart,targetMs:s.targetSeconds==null?0:Number(s.targetSeconds)*1000,systemEventType:s.systemEventType||''}});const byId=new Map(steps.map(s=>[s.id,s]));if(byId.size!==steps.length)throw Error('步骤标识不得重复');const done=new Set(),active=new Set();function visit(id){if(active.has(id))throw Error('前置或计时关系不能成环');if(done.has(id))return;const s=byId.get(id);if(!s)throw Error('引用步骤不存在');active.add(id);for(const d of [...s.prerequisites,...(['RUN_START','PLATFORM_RECEIVED'].includes(s.clockStart)?[]:[s.clockStart])])visit(d);active.delete(id);done.add(id)}for(const s of steps)visit(s.id);return{resourceId:form.resourceId,expectedVersion:form.expectedVersion||0,deviceIds,idempotencyKey:key,body:{name:form.name.trim(),scenario:form.scenario.trim(),steps,published:false}}}
export function evidencePayload(rows,allowedDeviceIds){return rows.map(row=>{if(!evidenceKinds[row.kind]||!allowedDeviceIds.includes(row.deviceId)||(row.kind==='MANUAL_RECORD'?!row.description.trim():!row.sourceId))throw Error('证据须引用范围内的具体资料，人工资料须有实际内容');return{kind:row.kind,deviceId:row.deviceId,sourceId:row.kind==='MANUAL_RECORD'?'':row.sourceId,description:row.description.trim()}})}
export function evaluationRatio(evaluation,field){const denominator=field==='completionRate'?evaluation?.requiredSteps:evaluation?.requiredEvidence;if(denominator===0)return'不适用';const value=evaluation?.[field];return !(denominator>0)||value==null||!Number.isFinite(value)||value<0||value>1?'证据不足':`${(value*100).toFixed(1)}%`}
export function stepDuration(step){if(step?.status==='TIME_CONFLICT'||step?.durationMs<0)return'时间异常';return step?.durationMs==null?'未形成可信完成时长':durationLabel(step.durationMs)}
export function evaluationPayload(execution,end,cutoff,key){if(!execution?.body?.startedAt||!['RUNNING','RECORDING','ENDED','REVIEWED'].includes(execution.body.status))throw Error('执行尚未开始或已归档');const actualEnd=execution.body.endedAt||end;if(!(actualEnd>execution.body.startedAt)||!(cutoff>=actualEnd))throw Error('复盘区间与资料截止时间无效');return{deviceIds:execution.deviceIds.slice(),start:execution.body.startedAt,end:actualEnd,configurationVersion:execution.id,idempotencyKey:key,parameters:{executionRevisionId:execution.id,cutoff}}}
export function milestonePayload(form,execution,key){const step=execution.body.procedure.steps.find(s=>s.id===form.stepId);if(!step||step.systemEventType)throw Error('系统节点只能关联真实事务事件');if(!form.occurredAt||!form.executor||!form.explanation.trim()||!['UNVERIFIED','CONFIRMED','DISPUTED'].includes(form.status))throw Error('请明确发生时间、执行人、确认状态和实际依据');return{expectedVersion:execution.version,idempotencyKey:key,stepId:form.stepId,occurredAt:form.occurredAt,executor:form.executor,status:form.status,explanation:form.explanation.trim(),correctsId:form.correctsId||'',evidence:evidencePayload(form.evidence||[],execution.deviceIds)}}
export function correctedMilestones(rows=[]){const superseded=new Set(rows.map(row=>row.correctsId).filter(Boolean));return rows.map(row=>({...row,superseded:superseded.has(row.id)})).sort((a,b)=>a.occurredAt-b.occurredAt||a.recordedAt-b.recordedAt||String(a.id).localeCompare(String(b.id)))}
export const executionActions=row=>row?.source==='DRILL'?({DRAFT:['PUBLISH','CANCEL'],PUBLISHED:['START','CANCEL'],RUNNING:['END','CANCEL'],ENDED:['ARCHIVE'],REVIEWED:['ARCHIVE'],CANCELLED:['ARCHIVE']}[row.status]||[]):({RECORDING:['END'],ENDED:['ARCHIVE'],REVIEWED:['ARCHIVE']}[row?.status]||[])
export const actionLabels={PUBLISH:'发布计划',START:'开始执行',END:'结束执行',CANCEL:'取消并说明原因',ARCHIVE:'归档执行',ASSIGN:'调整负责人及期限',RECORD:'登记处理证据',SUBMIT_VERIFICATION:'提交独立验收',LINK_FOLLOW_UP:'关联后续执行'}
export const correctiveActions=row=>({OPEN:['START','ASSIGN','CANCEL','LINK_FOLLOW_UP'],IN_PROGRESS:['RECORD','SUBMIT_VERIFICATION','ASSIGN','CANCEL','LINK_FOLLOW_UP'],PENDING_VERIFICATION:['ASSIGN','CANCEL','LINK_FOLLOW_UP']}[row?.status]||[])
export function hasNewEvidence(fixed,latest){return ['milestones','simulationEvents','sampleAssociations'].some(key=>{const ids=new Set((fixed?.[key]||[]).map(row=>row.id));return(latest?.[key]||[]).some(row=>!ids.has(row.id))})}
export function formalConfirmation(execution,run,snapshot){return(execution?.body?.confirmations||[]).find(row=>row.revisionId===run?.id&&row.factsHash===snapshot?.factsHash)}
export function confirmationPayload(execution,run,snapshot,conclusion,key){if(!['ENDED','REVIEWED'].includes(execution?.body?.status)||run?.status!=='SUCCEEDED'||!snapshot?.factsHash||!conclusion.trim())throw Error('正式确认需要已结束执行、完成的固定复盘及人工结论');if(formalConfirmation(execution,run,snapshot))throw Error('此固定复盘已经正式确认');return{expectedVersion:execution.version,expectedRunVersion:run.version,factsHash:snapshot.factsHash,conclusion:conclusion.trim(),idempotencyKey:key}}
export function correctivePayload(form,execution,run,snapshot,findings,key){const requiredVerification=(form.requiredVerification||[]).map(value=>value.trim()).filter(Boolean);if(!formalConfirmation(execution,run,snapshot))throw Error('整改必须来自已正式确认的固定复盘');if(!findings.some(row=>row.id===form.findingId)||!form.title.trim()||!form.owner||!(form.dueAt>0)||!requiredVerification.length||requiredVerification.length>20||new Set(requiredVerification).size!==requiredVerification.length)throw Error('请明确实际发现、整改名称、负责人、期限与不重复的验收项');return{resourceId:form.resourceId,expectedVersion:0,deviceIds:execution.deviceIds.slice(),idempotencyKey:key,body:{title:form.title.trim(),reviewRevisionId:run.id,reviewFactsHash:snapshot.factsHash,findingId:form.findingId,owner:form.owner,dueAt:form.dueAt,requiredVerification}}}
export function verificationPayload(form,corrective,key){if(corrective?.body?.status!=='PENDING_VERIFICATION'||!['PASSED','FAILED'].includes(form.result)||!form.explanation.trim())throw Error('独立验收需要待验收事项、实际结论与依据');const required=corrective.body.requiredVerification||[],items=[...new Set(form.items||[])];if(items.some(item=>!required.includes(item)))throw Error('验收项不属于当前固定整改');const evidence=evidencePayload(form.evidence||[],corrective.deviceIds);if(form.result==='PASSED'&&(required.some(item=>!items.includes(item))||!evidence.length))throw Error('通过验收须核实全部规定项并关联实际证据');return{expectedVersion:corrective.version,idempotencyKey:key,result:form.result,items,explanation:form.explanation.trim(),evidence}}
export const compatibleDutyRuns=(runs,deviceIds)=>runs.filter(row=>row.status==='ACTIVE'&&deviceIds.every(id=>row.deviceIds?.includes(id)))
