-- Governed resources have separate tables, indexed relationships and tenant keys.
CREATE TABLE IF NOT EXISTS alarm_governance_template(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,resource_id,revision_number));
CREATE INDEX IF NOT EXISTS alarm_governance_template_scope_idx ON alarm_governance_template USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_template_list_idx ON alarm_governance_template(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_template_round_idx ON alarm_governance_template(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_scene_preset(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,resource_id,revision_number));
CREATE INDEX IF NOT EXISTS alarm_governance_scene_preset_scope_idx ON alarm_governance_scene_preset USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_scene_preset_list_idx ON alarm_governance_scene_preset(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_scene_preset_round_idx ON alarm_governance_scene_preset(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_type_profile(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,resource_id,revision_number));
CREATE INDEX IF NOT EXISTS alarm_governance_type_profile_scope_idx ON alarm_governance_type_profile USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_type_profile_list_idx ON alarm_governance_type_profile(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_type_profile_round_idx ON alarm_governance_type_profile(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_case(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id));
CREATE INDEX IF NOT EXISTS alarm_governance_case_scope_idx ON alarm_governance_case USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_case_list_idx ON alarm_governance_case(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_case_round_idx ON alarm_governance_case(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_round(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,UNIQUE(tenant_id,case_id,revision_number));
CREATE INDEX IF NOT EXISTS alarm_governance_round_scope_idx ON alarm_governance_round USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_round_list_idx ON alarm_governance_round(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_round_round_idx ON alarm_governance_round(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_alarm_link(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_alarm_link_scope_idx ON alarm_governance_alarm_link USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_alarm_link_list_idx ON alarm_governance_alarm_link(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_alarm_link_round_idx ON alarm_governance_alarm_link(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_verification(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_verification_scope_idx ON alarm_governance_verification USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_verification_list_idx ON alarm_governance_verification(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_verification_round_idx ON alarm_governance_verification(tenant_id,round_id,occurred_at,id);
CREATE INDEX IF NOT EXISTS alarm_governance_verification_correction_idx ON alarm_governance_verification(tenant_id,corrects_id,status) WHERE corrects_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS alarm_governance_verification_link(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,verification_id text GENERATED ALWAYS AS (body->>'verificationId') STORED,FOREIGN KEY(tenant_id,verification_id) REFERENCES alarm_governance_verification(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_verification_link_scope_idx ON alarm_governance_verification_link USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_verification_link_list_idx ON alarm_governance_verification_link(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_verification_link_round_idx ON alarm_governance_verification_link(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_activity(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,UNIQUE(tenant_id,resource_id,revision_number));
CREATE INDEX IF NOT EXISTS alarm_governance_activity_scope_idx ON alarm_governance_activity USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_activity_list_idx ON alarm_governance_activity(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_activity_round_idx ON alarm_governance_activity(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_activity_coverage(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,UNIQUE(tenant_id,resource_id,revision_number));
CREATE INDEX IF NOT EXISTS alarm_governance_activity_coverage_scope_idx ON alarm_governance_activity_coverage USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_activity_coverage_list_idx ON alarm_governance_activity_coverage(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_activity_coverage_round_idx ON alarm_governance_activity_coverage(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_cause(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_cause_scope_idx ON alarm_governance_cause USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_cause_list_idx ON alarm_governance_cause(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_cause_round_idx ON alarm_governance_cause(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_measure(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_measure_scope_idx ON alarm_governance_measure USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_measure_list_idx ON alarm_governance_measure(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_measure_round_idx ON alarm_governance_measure(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_observation_plan(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_observation_plan_scope_idx ON alarm_governance_observation_plan USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_observation_plan_list_idx ON alarm_governance_observation_plan(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_observation_plan_round_idx ON alarm_governance_observation_plan(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_observation_review(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,plan_id text GENERATED ALWAYS AS (body->>'planId') STORED,FOREIGN KEY(tenant_id,plan_id) REFERENCES alarm_governance_observation_plan(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_observation_review_scope_idx ON alarm_governance_observation_review USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_observation_review_list_idx ON alarm_governance_observation_review(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_observation_review_round_idx ON alarm_governance_observation_review(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_report(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,review_id text GENERATED ALWAYS AS (body->>'reviewId') STORED,FOREIGN KEY(tenant_id,review_id) REFERENCES alarm_governance_observation_review(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_report_scope_idx ON alarm_governance_report USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_report_list_idx ON alarm_governance_report(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_report_round_idx ON alarm_governance_report(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_event(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_event_scope_idx ON alarm_governance_event USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_event_list_idx ON alarm_governance_event(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_event_round_idx ON alarm_governance_event(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_receipt(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id));
CREATE INDEX IF NOT EXISTS alarm_governance_receipt_scope_idx ON alarm_governance_receipt USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_receipt_list_idx ON alarm_governance_receipt(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_receipt_round_idx ON alarm_governance_receipt(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_attachment(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_attachment_scope_idx ON alarm_governance_attachment USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_attachment_list_idx ON alarm_governance_attachment(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_attachment_round_idx ON alarm_governance_attachment(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_business_link(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_business_link_scope_idx ON alarm_governance_business_link USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_business_link_list_idx ON alarm_governance_business_link(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_business_link_round_idx ON alarm_governance_business_link(tenant_id,round_id,occurred_at,id);
CREATE TABLE IF NOT EXISTS alarm_governance_reminder(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(tenant_id,round_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS alarm_governance_reminder_scope_idx ON alarm_governance_reminder USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_reminder_list_idx ON alarm_governance_reminder(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_reminder_round_idx ON alarm_governance_reminder(tenant_id,round_id,occurred_at,id);
CREATE UNIQUE INDEX IF NOT EXISTS alarm_governance_active_point ON alarm_governance_case(tenant_id,point_key) WHERE status NOT IN ('COMPLETED','CANCELLED');
CREATE UNIQUE INDEX IF NOT EXISTS alarm_governance_active_round ON alarm_governance_round(tenant_id,case_id) WHERE status='ACTIVE';
CREATE TABLE IF NOT EXISTS alarm_governance_source_version(tenant_id text NOT NULL,dependency_key text NOT NULL,bucket_start bigint NOT NULL,generation bigint NOT NULL DEFAULT 0 CHECK(generation>=0),PRIMARY KEY(tenant_id,dependency_key,bucket_start));
CREATE TABLE IF NOT EXISTS alarm_governance_published_config(tenant_id text NOT NULL,kind text NOT NULL,resource_id text NOT NULL,revision_id text NOT NULL,version bigint NOT NULL DEFAULT 1,PRIMARY KEY(tenant_id,kind,resource_id));

-- Every committed resource version remains inspectable after current state advances.
CREATE TABLE IF NOT EXISTS alarm_governance_template_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_template(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_scene_preset_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_scene_preset(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_type_profile_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_type_profile(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_case_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_case(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_round_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_round(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_alarm_link_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_alarm_link(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_verification_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_verification(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_verification_link_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_verification_link(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_activity_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_activity(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_activity_coverage_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_activity_coverage(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_cause_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_cause(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_measure_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_measure(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_observation_plan_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_observation_plan(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_observation_review_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_observation_review(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_report_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_report(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_event_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_event(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_receipt_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_receipt(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_attachment_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_attachment(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_business_link_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_business_link(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS alarm_governance_reminder_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_reminder(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);

-- Recoverable private upload attempts are separate from immutable request receipts.
CREATE TABLE IF NOT EXISTS alarm_governance_upload_attempt(tenant_id text NOT NULL,id text NOT NULL,version bigint NOT NULL CHECK(version>0),created_by text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,
 case_id text,round_id text,parent_id text,resource_id text,revision_number integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT '',owner_user_id text NOT NULL DEFAULT '',device_ids text[] NOT NULL DEFAULT '{}',point_key text NOT NULL DEFAULT '',occurred_at bigint NOT NULL DEFAULT 0,corrects_id text,
 body jsonb NOT NULL,PRIMARY KEY(tenant_id,id));
CREATE INDEX IF NOT EXISTS alarm_governance_upload_attempt_scope_idx ON alarm_governance_upload_attempt USING gin(device_ids);
CREATE INDEX IF NOT EXISTS alarm_governance_upload_attempt_list_idx ON alarm_governance_upload_attempt(tenant_id,status,owner_user_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS alarm_governance_upload_attempt_round_idx ON alarm_governance_upload_attempt(tenant_id,round_id,occurred_at,id);

CREATE TABLE IF NOT EXISTS alarm_governance_upload_attempt_history(tenant_id text NOT NULL,resource_id text NOT NULL,version bigint NOT NULL CHECK(version>0),recorded_at bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(tenant_id,resource_id,version),FOREIGN KEY(tenant_id,resource_id) REFERENCES alarm_governance_upload_attempt(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
