package config

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// LoadEnvFile loads the literal KEY=VALUE files generated by the setup scripts.
// It accepts UTF-8 (with or without BOM), CRLF, comments and quoted values.
// Values are never evaluated as shell commands or expanded as variables.
// Existing process variables, including empty values, take precedence.
func LoadEnvFile(path string) error {
	file, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("open environment file: %w", err)
	}
	defer file.Close()

	entries := make(map[string]string)
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 4096), 1024*1024)
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := scanner.Text()
		if lineNo == 1 {
			line = strings.TrimPrefix(line, "\ufeff")
		}
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		key, value = strings.TrimSpace(key), strings.TrimSpace(value)
		if !ok || !validEnvKey(key) {
			return fmt.Errorf("environment file line %d: expected KEY=VALUE", lineNo)
		}
		if strings.IndexByte(value, 0) >= 0 {
			return fmt.Errorf("environment file line %d: invalid value", lineNo)
		}
		if len(value) > 0 && (value[0] == '\'' || value[0] == '"') {
			end := strings.IndexByte(value[1:], value[0])
			if end < 0 {
				return fmt.Errorf("environment file line %d: unclosed quote", lineNo)
			}
			end++
			tail := strings.TrimSpace(value[end+1:])
			if tail != "" && !strings.HasPrefix(tail, "#") {
				return fmt.Errorf("environment file line %d: unexpected text after quote", lineNo)
			}
			value = value[1:end]
		} else if comment := strings.Index(value, " #"); comment >= 0 {
			value = strings.TrimSpace(value[:comment])
		}
		entries[key] = value
	}
	if err := scanner.Err(); err != nil {
		// Scanner errors may be wrapped by callers; never include file contents.
		return fmt.Errorf("read environment file: %w", err)
	}
	for key, value := range entries {
		if _, exists := os.LookupEnv(key); !exists {
			if err := os.Setenv(key, value); err != nil {
				return fmt.Errorf("set environment variable %s: %w", key, err)
			}
		}
	}
	return nil
}

func validEnvKey(key string) bool {
	if key == "" {
		return false
	}
	for i, c := range key {
		if c != '_' && !(c >= 'a' && c <= 'z') && !(c >= 'A' && c <= 'Z') && !(i > 0 && c >= '0' && c <= '9') {
			return false
		}
	}
	return true
}
