package config /* 声明 config 包。 */

import ( /* 引入当前代码需要的依赖。 */
	"bufio"   /* 执行当前语句并推进处理流程。 */
	"fmt"     /* 执行当前语句并推进处理流程。 */
	"os"      /* 执行当前语句并推进处理流程。 */
	"strings" /* 执行当前语句并推进处理流程。 */
) /* 结束当前表达式或代码块。 */

// LoadEnvFile loads the literal KEY=VALUE files generated by the setup scripts.
// It accepts UTF-8 (with or without BOM), CRLF, comments and quoted values.
// Values are never evaluated as shell commands or expanded as variables.
// Existing process variables, including empty values, take precedence.
func LoadEnvFile(path string) error { /* 定义 LoadEnvFile 函数。 */
	file, err := os.Open(path) /* 更新 err 的值。 */
	if err != nil {            /* 判断条件并选择处理分支。 */
		return fmt.Errorf("open environment file: %w", err) /* 返回当前处理结果。 */
	} /* 结束当前表达式或代码块。 */
	defer file.Close() /* 安排函数结束时执行清理。 */

	entries := make(map[string]string)            /* 更新 entries 的值。 */
	scanner := bufio.NewScanner(file)             /* 更新 scanner 的值。 */
	scanner.Buffer(make([]byte, 4096), 1024*1024) /* 执行当前语句并推进处理流程。 */
	lineNo := 0                                   /* 更新 lineNo 的值。 */
	for scanner.Scan() {                          /* 循环处理当前数据。 */
		lineNo++               /* 执行当前语句并推进处理流程。 */
		line := scanner.Text() /* 更新 line 的值。 */
		if lineNo == 1 {       /* 判断条件并选择处理分支。 */
			line = strings.TrimPrefix(line, "\ufeff") /* 更新 line 的值。 */
		} /* 结束当前表达式或代码块。 */
		line = strings.TrimSpace(line)                  /* 更新 line 的值。 */
		if line == "" || strings.HasPrefix(line, "#") { /* 判断条件并选择处理分支。 */
			continue /* 执行当前语句并推进处理流程。 */
		} /* 结束当前表达式或代码块。 */
		key, value, ok := strings.Cut(line, "=")                      /* 更新 ok 的值。 */
		key, value = strings.TrimSpace(key), strings.TrimSpace(value) /* 更新 value 的值。 */
		if !ok || !validEnvKey(key) {                                 /* 判断条件并选择处理分支。 */
			return fmt.Errorf("environment file line %d: expected KEY=VALUE", lineNo) /* 返回当前处理结果。 */
		} /* 结束当前表达式或代码块。 */
		if strings.IndexByte(value, 0) >= 0 { /* 判断条件并选择处理分支。 */
			return fmt.Errorf("environment file line %d: invalid value", lineNo) /* 返回当前处理结果。 */
		} /* 结束当前表达式或代码块。 */
		if len(value) > 0 && (value[0] == '\'' || value[0] == '"') { /* 判断条件并选择处理分支。 */
			end := strings.IndexByte(value[1:], value[0]) /* 更新 end 的值。 */
			if end < 0 {                                  /* 判断条件并选择处理分支。 */
				return fmt.Errorf("environment file line %d: unclosed quote", lineNo) /* 返回当前处理结果。 */
			} /* 结束当前表达式或代码块。 */
			end++                                            /* 执行当前语句并推进处理流程。 */
			tail := strings.TrimSpace(value[end+1:])         /* 更新 tail 的值。 */
			if tail != "" && !strings.HasPrefix(tail, "#") { /* 判断条件并选择处理分支。 */
				return fmt.Errorf("environment file line %d: unexpected text after quote", lineNo) /* 返回当前处理结果。 */
			} /* 结束当前表达式或代码块。 */
			value = value[1:end] /* 更新 value 的值。 */
		} else if comment := strings.Index(value, " #"); comment >= 0 { /* 结束当前表达式或代码块。 */
			value = strings.TrimSpace(value[:comment]) /* 更新 value 的值。 */
		} /* 结束当前表达式或代码块。 */
		entries[key] = value /* 更新 entries[key] 的值。 */
	} /* 结束当前表达式或代码块。 */
	if err := scanner.Err(); err != nil { /* 判断条件并选择处理分支。 */
		// Scanner errors may be wrapped by callers; never include file contents.
		return fmt.Errorf("read environment file: %w", err) /* 返回当前处理结果。 */
	} /* 结束当前表达式或代码块。 */
	for key, value := range entries { /* 循环处理当前数据。 */
		if _, exists := os.LookupEnv(key); !exists { /* 判断条件并选择处理分支。 */
			if err := os.Setenv(key, value); err != nil { /* 判断条件并选择处理分支。 */
				return fmt.Errorf("set environment variable %s: %w", key, err) /* 返回当前处理结果。 */
			} /* 结束当前表达式或代码块。 */
		} /* 结束当前表达式或代码块。 */
	} /* 结束当前表达式或代码块。 */
	return nil /* 返回当前处理结果。 */
} /* 结束当前表达式或代码块。 */

func validEnvKey(key string) bool { /* 定义 validEnvKey 函数。 */
	if key == "" { /* 判断条件并选择处理分支。 */
		return false /* 返回当前处理结果。 */
	} /* 结束当前表达式或代码块。 */
	for i, c := range key { /* 循环处理当前数据。 */
		if c != '_' && !(c >= 'a' && c <= 'z') && !(c >= 'A' && c <= 'Z') && !(i > 0 && c >= '0' && c <= '9') { /* 判断条件并选择处理分支。 */
			return false /* 返回当前处理结果。 */
		} /* 结束当前表达式或代码块。 */
	} /* 结束当前表达式或代码块。 */
	return true /* 返回当前处理结果。 */
} /* 结束当前表达式或代码块。 */
