<script setup>
import DeviceSelect from '../DeviceSelect.vue'
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { canGovernance as can } from '../../governance/permissions.js'
import { createClientId } from '../../clientId.js'
import { governanceRead, governanceWrite } from '../../governance/api.js'
import { conflictMessage, label, recordBody, time } from '../../governance/helpers.js'
const props=defineProps({devices:Array,configs:Object,deviceId:{type:String,default:''}})
const tab=ref('activities'), rows=ref([]), total=ref(0), page=ref(1), loading=ref(false), saving=ref(false), error=ref(''), dialog=ref(false), form=reactive({}), previous=ref(null)
const sceneOptions=computed(()=>(props.configs['scene-presets']||[]).map(recordBody).filter(row=>row.status==='PUBLISHED'))
const activityOptions=computed(()=>sceneOptions.value.find(row=>row.id===form.scenePresetRevisionId)?.activityOptions||[])
const deviceName=id=>props.devices.find(row=>row.id===id)?.name||id
let generation=0
async function load(){const token=++generation;loading.value=true;error.value='';try{const result=await governanceRead(tab.value,'','',{deviceIds:props.deviceId?[props.deviceId]:[],limit:20,offset:(page.value-1)*20});if(token!==generation)return;rows.value=(result.items||[]).map(recordBody);total.value=result.total||0}catch(cause){if(token===generation)error.value=cause.message}finally{if(token===generation)loading.value=false}}
function edit(row,copy=false){previous.value=copy?null:row||null;Object.assign(form,{activityId:copy?'':row?.activityId||'',coverageId:row?.coverageId||'',location:row?.location||'',deviceIds:row?.deviceIds?.slice()||(props.deviceId?[props.deviceId]:[]),activityType:row?.activityType||'',unit:row?.unit||'',actual:copy?false:row?.actual??true,startAt:copy?null:row?.startAt??null,endAt:copy?null:row?.endAt??null,timeQuality:copy?'MISSING':row?.timeQuality||'MISSING',source:'MANUAL',conditions:row?.conditions||{},status:'DRAFT',coverage:row?.coverage||'UNKNOWN',basis:row?.basis||'',description:row?.description||'',templateRevisionId:row?.templateRevisionId||'',scenePresetRevisionId:row?.scenePresetRevisionId||'',correctionReason:'',idempotencyKey:createClientId()});error.value='';dialog.value=true}
async function save(){if(saving.value||!can(`POST /api/v1/alarm-governance/${tab.value}${previous.value?'/:id/revisions':''}`))return;saving.value=true;error.value='';try{if(!form.deviceIds.length||!form.location||!form.activityType)throw new Error('请明确位置、设备成员与活动类型');if(tab.value==='activities'&&!form.unit)throw new Error('请填写固定活动单位');if(tab.value==='activity-coverages'&&!(form.endAt>form.startAt))throw new Error('请填写有效覆盖区间');if(form.endAt!=null&&form.startAt!=null&&form.endAt<=form.startAt)throw new Error('结束时间须晚于开始时间');if(previous.value&&!form.correctionReason.trim())throw new Error('请填写更正依据');await governanceWrite(tab.value,previous.value?.id||'',previous.value?'revisions':'',{...form,expectedVersion:previous.value?.version||0});dialog.value=false;await load()}catch(cause){error.value=conflictMessage(cause)}finally{saving.value=false}}
async function confirm(row){if(saving.value||!can('POST /api/v1/alarm-governance/activities/:id/confirm'))return;saving.value=true;try{await governanceWrite('activities',row.id,'confirm',{expectedVersion:row.version,idempotencyKey:createClientId()});await load()}catch(cause){error.value=conflictMessage(cause)}finally{saving.value=false}}
function endActivity(row){edit(row);form.endAt=Date.now()}
watch(tab,()=>{page.value=1;void load()});watch(page,load);watch(()=>props.deviceId,()=>{page.value=1;void load()});onMounted(load)
</script>
<template><section class="gov-stack"><ui-tabs v-model="tab"><ui-tab-pane name="activities" label="实际 / 计划活动"/><ui-tab-pane name="activity-coverages" label="登记覆盖声明"/></ui-tabs><div class="gov-toolbar"><p class="gov-meta">活动独立于报警登记。完整活动分母需要明确实际区间、固定活动单位、可用监测与完整登记声明。</p><ui-button v-if="can(`POST /api/v1/alarm-governance/${tab}`)" size="small" @click="edit()">{{tab==='activities'?'开始 / 登记活动':'声明登记覆盖'}}</ui-button></div><ui-alert v-if="error&&!dialog" :title="error" type="error" :closable="false"/><ui-skeleton v-if="loading" :rows="4"/><div v-else class="gov-cards"><article v-for="row in rows" :key="row.id" class="gov-card"><div class="gov-toolbar"><strong>{{row.location}} · {{row.activityType}}</strong><ui-tag>{{tab==='activities'?(row.actual?'实际活动':'待确认计划'):label(row.coverage)}}</ui-tag></div><p>{{row.deviceIds.map(deviceName).join('、')}}</p><p class="gov-meta">{{time(row.startAt)}} ～ {{time(row.endAt)}} · {{label(row.timeQuality)}} · {{row.unit||'覆盖范围'}} · {{label(row.status)}}</p><p>{{row.description||row.basis}}</p><p v-if="row.coverage==='FULL_DECLARED'" class="gov-meta">负责人按约定声明完整，系统不推断全部现场活动已知。</p><div class="gov-actions"><ui-button v-if="tab==='activities'&&row.actual&&!row.endAt&&can('POST /api/v1/alarm-governance/activities/:id/revisions')" text size="small" @click="endActivity(row)">结束活动</ui-button><ui-button v-if="can(`POST /api/v1/alarm-governance/${tab}/:id/revisions`)" text size="small" @click="edit(row)">追加更正版本</ui-button><ui-button v-if="tab==='activities'&&row.status==='DRAFT'&&can('POST /api/v1/alarm-governance/activities/:id/confirm')" text size="small" :loading="saving" @click="confirm(row)">人工确认实际记录</ui-button><ui-button v-if="tab==='activities'&&can('POST /api/v1/alarm-governance/activities')" text size="small" @click="edit(row,true)">复制为待确认计划</ui-button></div></article></div><ui-empty v-if="!loading&&!rows.length" description="暂无独立活动记录。无报警活动也需要按约定登记。"/><ui-pagination :current-page="page" :total="total" :page-size="20" @current-change="page=$event"/></section>
<ui-dialog v-model="dialog" :title="tab==='activities'?'现场活动登记':'活动登记覆盖声明'" width="min(740px,94vw)" :close-on-click-modal="false"><div class="gov-dialog-body"><ui-alert v-if="error" :title="error" type="error" :closable="false"/><ui-form label-position="top" :disabled="saving"><div class="gov-grid"><ui-form-item label="历史位置" required><ui-input v-model="form.location"/></ui-form-item><ui-form-item label="明确设备成员" required><DeviceSelect v-model="form.deviceIds" multiple/></ui-form-item><ui-form-item label="场景预设"><ui-select v-model="form.scenePresetRevisionId"><ui-option v-for="row in sceneOptions" :key="row.id" :value="row.id" :label="`${row.name} · 版本 ${row.revisionNumber}`"/></ui-select></ui-form-item><ui-form-item label="固定模板版本"><ui-select v-model="form.templateRevisionId"><ui-option v-for="row in (configs.templates||[]).map(recordBody).filter(row=>row.status==='PUBLISHED')" :key="row.id" :value="row.id" :label="row.name"/></ui-select></ui-form-item><ui-form-item label="活动类型" required><ui-select v-model="form.activityType" filterable allow-create><ui-option v-for="option in activityOptions" :key="option.code" :value="option.code" :label="option.label"/></ui-select></ui-form-item><ui-form-item v-if="tab==='activities'" label="活动单位" required><ui-input v-model="form.unit" placeholder="例如一次供餐，不随意拆分"/></ui-form-item><ui-form-item label="实际开始 / 登记覆盖开始"><ui-date-time v-model="form.startAt" clearable/><ui-button v-if="tab==='activities'" text size="small" @click="form.startAt=Date.now()">现在开始</ui-button></ui-form-item><ui-form-item label="实际结束 / 登记覆盖结束"><ui-date-time v-model="form.endAt" clearable/><ui-button v-if="tab==='activities'" text size="small" @click="form.endAt=Date.now()">现在结束</ui-button></ui-form-item><ui-form-item v-if="tab==='activities'" label="时间质量"><ui-select v-model="form.timeQuality"><ui-option v-for="code in ['MISSING','TRUSTED','UNVERIFIED','ESTIMATED','CONFLICTED']" :key="code" :value="code" :label="label(code)"/></ui-select></ui-form-item><ui-form-item v-if="tab==='activities'" label="实际发生"><ui-checkbox v-model="form.actual">现场确认已实际发生（未勾选为计划）</ui-checkbox></ui-form-item><ui-form-item v-else label="登记完整性" required><ui-select v-model="form.coverage"><ui-option v-for="code in ['UNKNOWN','ALARM_ONLY','PARTIAL','FULL_DECLARED']" :key="code" :value="code" :label="label(code)"/></ui-select></ui-form-item></div><ui-form-item v-if="tab==='activity-coverages'" label="声明依据与抽查记录" required><ui-input v-model="form.basis" type="textarea" :rows="3"/></ui-form-item><ui-form-item v-else label="条件与现场说明"><ui-input v-model="form.description" type="textarea" :rows="3"/></ui-form-item><ui-form-item v-if="previous" label="更正 / 结束依据" required><ui-input v-model="form.correctionReason"/></ui-form-item></ui-form></div><template #footer><ui-button :disabled="saving" @click="dialog=false">取消</ui-button><ui-button type="primary" :loading="saving" @click="save">保存独立记录</ui-button></template></ui-dialog>
</template>
