<script setup>
import DeviceSelect from '../DeviceSelect.vue'
import { computed, ref, watch } from 'vue'
import { governanceRead } from '../../governance/api.js'
import { time } from '../../governance/helpers.js'
const props=defineProps({field:Object,devices:Array})
const deviceId=ref(props.field?.sourceDeviceId||''),range=ref([Date.now()-7*86400000,Date.now()]),rows=ref([]),loading=ref(false),error=ref(''),selected=ref('')
let generation=0
const eligible=computed(()=>rows.value.filter(row=>props.field.control==='text'?row.sourceType==='STRING':props.field.control==='number'?row.sourceType==='NUMBER':props.field.control==='single'?(row.enumValues?.length||row.sourceType==='BOOLEAN'):false))
function clear(){for(const key of ['sourceDeviceId','sourceMessageId','sourceType','sourceFieldPath','sourceConfirmedBy','sourceConfirmedAt','sourceValueHash'])delete props.field[key];selected.value=''}
async function load(){if(!deviceId.value||!range.value)return;const token=++generation;loading.value=true;error.value='';try{const value=await governanceRead('source-fields','','',{deviceId:deviceId.value,start:range.value[0],end:range.value[1]});if(token!==generation)return;rows.value=(value.items||[]).map(row=>({...row,key:`${row.messageId}:${row.sourceFieldPath}`}));selected.value=rows.value.find(row=>row.messageId===props.field.sourceMessageId&&row.sourceFieldPath===props.field.sourceFieldPath)?.key||''}catch(cause){if(token===generation)error.value=cause.message}finally{if(token===generation)loading.value=false}}
function bind(key){const row=eligible.value.find(item=>item.key===key);if(!row)return;clear();Object.assign(props.field,{sourceDeviceId:row.deviceId,sourceMessageId:row.messageId,sourceType:row.sourceType,sourceFieldPath:row.sourceFieldPath});if(props.field.control==='single'){const options=props.field.options||[];const actual=row.sourceType==='BOOLEAN'?['true','false']:row.enumValues||[];for(const code of [...actual,'UNKNOWN','DISPUTED'])if(!options.some(option=>option.code===code))options.push({code,label:code==='UNKNOWN'?'未知':code==='DISPUTED'?'存在争议':code});props.field.options=options}selected.value=key}
watch(deviceId,()=>{generation++;rows.value=[];selected.value=''})
watch(()=>props.field.control,clear)
</script>
<template><details v-if="!field.protected&&['text','number','single'].includes(field.control)"><summary>绑定真实成功解析样本字段（选填）</summary><div class="gov-stack"><p class="gov-meta">来源选择只绑定取证字段；现场结果、活动归属和设施结论保持人工填写。配置需明确影响设备并包含来源设备；发布时服务端复核来源与范围。</p><div class="gov-grid"><ui-form-item label="来源设备"><DeviceSelect v-model="deviceId"/></ui-form-item><ui-form-item label="有界样本区间"><ui-date-range v-model="range" disable-future/></ui-form-item></div><ui-button size="small" :loading="loading" :disabled="!deviceId" @click="load">读取成功解析字段</ui-button><ui-alert v-if="error" :title="error" type="error" :closable="false"/><ui-form-item v-if="eligible.length" label="实际样本字段"><ui-select v-model="selected" filterable @change="bind"><ui-option v-for="(row,index) in eligible" :key="row.key||index" :value="row.key" :label="`${row.sourceFieldPath} · ${row.sourceType} · ${time(row.observedAt)}`"/></ui-select></ui-form-item><p v-if="field.sourceFieldPath" class="gov-meta">固定来源 {{field.sourceType}} · {{field.sourceFieldPath}} · {{field.sourceMessageId}} · {{field.sourceConfirmedBy?'发布时已由服务端确认':'草稿待发布复核'}}</p><ui-button v-if="field.sourceFieldPath" text size="small" @click="clear">移除来源绑定</ui-button><ui-empty v-if="!loading&&deviceId&&!rows.length" description="请读取本区间真实样本；没有样本时保留未绑定。"/></div></details></template>
