<script setup>
import {onMounted,reactive,ref} from 'vue' /* 引入当前代码需要的依赖。 */
import {UiMessage,UiMessageBox} from '../ui/feedback.js' /* 引入当前代码需要的依赖。 */
import {api,notifyError,session} from '../api' /* 引入当前代码需要的依赖。 */
import PermissionPicker from '../components/PermissionPicker.vue' /* 引入当前代码需要的依赖。 */
defineEmits(['navigate']) /* 执行当前语句并推进处理流程。 */
const tab=ref('users'),users=ref([]),roles=ref([]),catalog=ref([]),loading=ref(false),saving=ref(false),dialog=ref(''),editing=ref(false) /* 声明 tab。 */
const user=reactive({username:'',displayName:'',password:'',enabled:true,roleIds:[],permissions:[],deviceScope:'none',deviceIds:[]}) /* 声明 user。 */
const role=reactive({id:'',name:'',description:'',permissions:[]}) /* 声明 role。 */
const tenantId=ref(session.tenant),deviceOptions=ref([]) /* 声明 tenantId。 */
const scopeLabel=value=>value.deviceScope==='all'?'当前租户全部设备':value.deviceScope==='selected'?`指定 ${value.deviceIds?.length||0} 台设备`:'无设备' /* 声明 scopeLabel。 */
const password=reactive({username:'',value:''}) /* 声明 password。 */
async function load(){loading.value=true;try{const [u,r,p,d]=await Promise.all([api('/api/v1/access/users'),api('/api/v1/access/roles'),api('/api/v1/access/permissions'),api('/api/v1/access/device-options')]);tenantId.value=u.tenantId;deviceOptions.value=d.items||[];users.value=u.items||[];roles.value=r.items||[];catalog.value=p.items||[]}catch(e){notifyError(e)}finally{loading.value=false}} /* 定义 load 函数。 */
function editUser(value){editing.value=!!value;Object.assign(user,{username:'',displayName:'',password:'',enabled:true,roleIds:[],permissions:[],deviceScope:'none',deviceIds:[]},value?JSON.parse(JSON.stringify(value)):{});dialog.value='user'} /* 定义 editUser 函数。 */
function editRole(value){editing.value=!!value;Object.assign(role,{id:'',name:'',description:'',permissions:[]},value?JSON.parse(JSON.stringify(value)):{});dialog.value='role'} /* 定义 editRole 函数。 */
async function save(){if(saving.value)return;saving.value=true;try{const isUser=dialog.value==='user',value=isUser?user:role;const base=isUser?'/api/v1/access/users':'/api/v1/access/roles';await api(base+(editing.value?'/'+encodeURIComponent(isUser?user.username:role.id):''),{method:editing.value?'PUT':'POST',body:JSON.stringify(value)});dialog.value='';user.password='';await load();UiMessage.success('已保存')}catch(e){notifyError(e)}finally{saving.value=false}} /* 定义 save 函数。 */
async function remove(kind,value){try{await UiMessageBox.confirm(`确认删除${kind==='users'?'用户':'角色'}“${value.displayName||value.name||value.username}”？`,'删除确认',{type:'warning'});await api(`/api/v1/access/${kind}/${encodeURIComponent(value.username||value.id)}`,{method:'DELETE'});await load()}catch(e){if(e!=='cancel'&&e!=='close')notifyError(e)}} /* 定义 remove 函数。 */
function reset(value){password.username=value.username;password.value='';dialog.value='password'} /* 定义 reset 函数。 */
async function savePassword(){saving.value=true;try{await api(`/api/v1/access/users/${encodeURIComponent(password.username)}/password`,{method:'POST',body:JSON.stringify({password:password.value})});password.value='';dialog.value='';UiMessage.success('密码已重置，旧登录已失效')}catch(e){notifyError(e)}finally{saving.value=false}} /* 定义 savePassword 函数。 */
onMounted(load) /* 执行当前语句并推进处理流程。 */
</script>
<template>
 <ui-tabs v-model="tab"><ui-tab-pane label="用户管理" name="users"/><ui-tab-pane label="角色管理" name="roles"/><ui-tab-pane label="权限说明" name="permissions"/></ui-tabs> <!-- 渲染 ui-tabs 界面元素。 -->
 <div class="page-toolbar"><ui-button v-if="tab==='users'" v-permission="'POST /api/v1/access/users'" type="primary" @click="editUser()">添加用户</ui-button><ui-button v-if="tab==='roles'" v-permission="'POST /api/v1/access/roles'" type="primary" @click="editRole()">添加角色</ui-button><ui-button :loading="loading" @click="load">刷新</ui-button></div> <!-- 渲染 div 界面元素。 -->
 <ui-alert :title="`当前租户：${tenantId}。此处创建的用户归属该租户，登录时填写相同租户。`" type="info" :closable="false" class="bottom-gap"/> <!-- 渲染 ui-alert 界面元素。 -->
 <ui-alert title="内置管理员用于系统维护，不在此列表中修改。角色权限与用户单独授权合并生效。" type="info" :closable="false"/> <!-- 渲染 ui-alert 界面元素。 -->
 <ui-table v-if="tab==='users'" v-loading="loading" :data="users" class="top-gap" empty-text="暂无用户，点击添加用户创建登录账户"><ui-table-column prop="username" label="用户名"/><ui-table-column prop="displayName" label="姓名 / 显示名称"/><ui-table-column label="所属租户"><template #default>{{tenantId}}</template></ui-table-column><ui-table-column label="设备访问范围"><template #default="{row}">{{scopeLabel(row)}}</template></ui-table-column><ui-table-column label="角色"><template #default="{row}">{{row.roleIds.map(id=>roles.find(r=>r.id===id)?.name||id).join('、')||'未分配'}}</template></ui-table-column><ui-table-column label="状态" width="100"><template #default="{row}"><ui-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</ui-tag></template></ui-table-column><ui-table-column label="操作" width="270" fixed="right"><template #default="{row}"><div class="table-actions"><ui-button v-permission="'PUT /api/v1/access/users/:id'" :disabled="row.username===session.user" @click="editUser(row)">编辑</ui-button><ui-button v-permission="'POST /api/v1/access/users/:id/password'" @click="reset(row)">重置密码</ui-button><ui-button v-permission="'DELETE /api/v1/access/users/:id'" type="danger" :disabled="row.username===session.user" @click="remove('users',row)">删除</ui-button></div></template></ui-table-column></ui-table> <!-- 渲染 ui-table 界面元素。 -->
 <ui-table v-if="tab==='roles'" v-loading="loading" :data="roles" class="top-gap" empty-text="暂无角色，点击添加角色配置权限"><ui-table-column prop="name" label="角色名称"/><ui-table-column prop="id" label="角色标识"/><ui-table-column prop="description" label="说明"/><ui-table-column label="权限数量" width="100"><template #default="{row}">{{row.permissions.length}}</template></ui-table-column><ui-table-column label="操作" width="180" fixed="right"><template #default="{row}"><ui-button v-permission="'PUT /api/v1/access/roles/:id'" @click="editRole(row)">编辑</ui-button><ui-button v-permission="'DELETE /api/v1/access/roles/:id'" type="danger" @click="remove('roles',row)">删除</ui-button></template></ui-table-column></ui-table> <!-- 渲染 ui-table 界面元素。 -->
 <ui-card v-if="tab==='permissions'" class="top-gap"><h3>菜单与操作权限</h3><p>菜单权限控制可见页面及读取范围；操作权限分别控制新增、编辑、删除、下载、发布、设备控制等动作。后端会再次校验，每次请求均使用最新角色配置。</p><p>修改用户、停用用户或重置密码会使旧登录失效。角色被用户使用时不能删除。</p><p>设备列表、告警、原始报文、总览和实时提醒按用户设备范围过滤；没有设备管理权限时不返回设备及告警。全租户任务仅向拥有全部设备范围及相应菜单权限的用户开放。</p></ui-card> <!-- 渲染 ui-card 界面元素。 -->
 <ui-dialog :model-value="dialog==='user'||dialog==='role'" :title="`${editing?'编辑':'添加'}${dialog==='user'?'用户':'角色'}`" width="min(850px,94vw)" :close-on-click-modal="false" @close="dialog='';user.password=''"> <!-- 渲染 ui-dialog 界面元素。 -->
  <ui-form v-if="dialog==='user'" label-position="top" :disabled="saving"><ui-form-item label="所属租户"><ui-input :model-value="tenantId" disabled/></ui-form-item><ui-form-item label="用户名" required><ui-input v-model="user.username" :disabled="editing" autocomplete="off" placeholder="3至64位字母、数字、点、横线或下划线"/></ui-form-item><ui-form-item label="显示名称"><ui-input v-model="user.displayName"/></ui-form-item><ui-form-item v-if="!editing" label="初始密码" required><ui-input v-model="user.password" type="password" show-password autocomplete="new-password" placeholder="至少10位，最长72字节"/></ui-form-item><ui-form-item label="启用账户"><ui-switch v-model="user.enabled"/></ui-form-item><ui-form-item label="角色"><ui-select v-model="user.roleIds" multiple clearable style="width:100%"><ui-option v-for="r in roles" :key="r.id" :label="r.name" :value="r.id"/></ui-select></ui-form-item><ui-form-item label="设备访问范围"><ui-radio-group v-model="user.deviceScope"><ui-radio-button value="none">无设备</ui-radio-button><ui-radio-button value="selected">指定设备</ui-radio-button><ui-radio-button value="all">当前租户全部设备</ui-radio-button></ui-radio-group></ui-form-item><ui-form-item v-if="user.deviceScope==='selected'" label="可访问设备"><ui-select v-model="user.deviceIds" multiple filterable clearable collapse-tags collapse-tags-tooltip style="width:100%" placeholder="选择允许查看的设备"><ui-option v-for="d in deviceOptions" :key="d.id" :label="`${d.name}（${d.id}）`" :value="d.id"/></ui-select></ui-form-item><ui-alert title="须同时分配设备管理菜单及设备范围；告警随设备范围过滤。主设备与子设备分别授权。" type="info" :closable="false"/><p class="muted-text">全租户任务（智能助手、巡检、备份、接入配置、规则、摄像头和用户权限管理）需全部设备范围及对应菜单权限。</p><ui-form-item label="用户单独授权（在角色基础上增加）"><PermissionPicker v-model="user.permissions" :catalog="catalog"/></ui-form-item></ui-form> <!-- 渲染 ui-form 界面元素。 -->
  <ui-form v-else label-position="top" :disabled="saving"><ui-form-item label="角色标识" required><ui-input v-model="role.id" :disabled="editing" placeholder="例如 operations"/></ui-form-item><ui-form-item label="角色名称" required><ui-input v-model="role.name" placeholder="例如 设备运维"/></ui-form-item><ui-form-item label="说明"><ui-input v-model="role.description"/></ui-form-item><ui-form-item label="菜单与操作权限"><PermissionPicker v-model="role.permissions" :catalog="catalog"/></ui-form-item></ui-form> <!-- 渲染 ui-form 界面元素。 -->
  <template #footer><ui-button :disabled="saving" @click="dialog='';user.password=''">取消</ui-button><ui-button type="primary" :loading="saving" @click="save">保存</ui-button></template>
 </ui-dialog> <!-- 结束当前界面区域。 -->
 <ui-dialog :model-value="dialog==='password'" title="重置密码" width="min(460px,94vw)" @close="dialog='';password.value=''"><ui-form label-position="top"><ui-form-item :label="`用户：${password.username}`"><ui-input v-model="password.value" type="password" show-password autocomplete="new-password" placeholder="至少10位，最长72字节"/></ui-form-item></ui-form><template #footer><ui-button type="primary" :loading="saving" @click="savePassword">重置密码</ui-button></template></ui-dialog> <!-- 渲染 ui-dialog 界面元素。 -->
</template>
