<script setup>
import {onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,notifyError,session} from '../api'
import PermissionPicker from '../components/PermissionPicker.vue'
defineEmits(['navigate'])
const tab=ref('users'),users=ref([]),roles=ref([]),catalog=ref([]),loading=ref(false),saving=ref(false),dialog=ref(''),editing=ref(false)
const user=reactive({username:'',displayName:'',password:'',enabled:true,roleIds:[],permissions:[]})
const role=reactive({id:'',name:'',description:'',permissions:[]})
const password=reactive({username:'',value:''})
async function load(){loading.value=true;try{const [u,r,p]=await Promise.all([api('/api/v1/access/users'),api('/api/v1/access/roles'),api('/api/v1/access/permissions')]);users.value=u.items||[];roles.value=r.items||[];catalog.value=p.items||[]}catch(e){notifyError(e)}finally{loading.value=false}}
function editUser(value){editing.value=!!value;Object.assign(user,{username:'',displayName:'',password:'',enabled:true,roleIds:[],permissions:[]},value?JSON.parse(JSON.stringify(value)):{});dialog.value='user'}
function editRole(value){editing.value=!!value;Object.assign(role,{id:'',name:'',description:'',permissions:[]},value?JSON.parse(JSON.stringify(value)):{});dialog.value='role'}
async function save(){if(saving.value)return;saving.value=true;try{const isUser=dialog.value==='user',value=isUser?user:role;const base=isUser?'/api/v1/access/users':'/api/v1/access/roles';await api(base+(editing.value?'/'+encodeURIComponent(isUser?user.username:role.id):''),{method:editing.value?'PUT':'POST',body:JSON.stringify(value)});dialog.value='';user.password='';await load();ElMessage.success('已保存')}catch(e){notifyError(e)}finally{saving.value=false}}
async function remove(kind,value){try{await ElMessageBox.confirm(`确认删除${kind==='users'?'用户':'角色'}“${value.displayName||value.name||value.username}”？`,'删除确认',{type:'warning'});await api(`/api/v1/access/${kind}/${encodeURIComponent(value.username||value.id)}`,{method:'DELETE'});await load()}catch(e){if(e!=='cancel'&&e!=='close')notifyError(e)}}
function reset(value){password.username=value.username;password.value='';dialog.value='password'}
async function savePassword(){saving.value=true;try{await api(`/api/v1/access/users/${encodeURIComponent(password.username)}/password`,{method:'POST',body:JSON.stringify({password:password.value})});password.value='';dialog.value='';ElMessage.success('密码已重置，旧登录已失效')}catch(e){notifyError(e)}finally{saving.value=false}}
onMounted(load)
</script>
<template>
 <el-tabs v-model="tab"><el-tab-pane label="用户管理" name="users"/><el-tab-pane label="角色管理" name="roles"/><el-tab-pane label="权限说明" name="permissions"/></el-tabs>
 <div class="page-toolbar"><el-button v-if="tab==='users'" v-permission="'POST /api/v1/access/users'" type="primary" @click="editUser()">添加用户</el-button><el-button v-if="tab==='roles'" v-permission="'POST /api/v1/access/roles'" type="primary" @click="editRole()">添加角色</el-button><el-button :loading="loading" @click="load">刷新</el-button></div>
 <el-alert title="内置管理员用于系统维护，不在此列表中修改。角色权限与用户单独授权合并生效。" type="info" :closable="false"/>
 <el-table v-if="tab==='users'" v-loading="loading" :data="users" class="top-gap" empty-text="暂无用户，点击添加用户创建登录账户"><el-table-column prop="username" label="用户名"/><el-table-column prop="displayName" label="姓名 / 显示名称"/><el-table-column label="角色"><template #default="{row}">{{row.roleIds.map(id=>roles.find(r=>r.id===id)?.name||id).join('、')||'未分配'}}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="270" fixed="right"><template #default="{row}"><div class="table-actions"><el-button v-permission="'PUT /api/v1/access/users/:id'" :disabled="row.username===session.user" @click="editUser(row)">编辑</el-button><el-button v-permission="'POST /api/v1/access/users/:id/password'" @click="reset(row)">重置密码</el-button><el-button v-permission="'DELETE /api/v1/access/users/:id'" type="danger" :disabled="row.username===session.user" @click="remove('users',row)">删除</el-button></div></template></el-table-column></el-table>
 <el-table v-if="tab==='roles'" v-loading="loading" :data="roles" class="top-gap" empty-text="暂无角色，点击添加角色配置权限"><el-table-column prop="name" label="角色名称"/><el-table-column prop="id" label="角色标识"/><el-table-column prop="description" label="说明"/><el-table-column label="权限数量" width="100"><template #default="{row}">{{row.permissions.length}}</template></el-table-column><el-table-column label="操作" width="180" fixed="right"><template #default="{row}"><el-button v-permission="'PUT /api/v1/access/roles/:id'" @click="editRole(row)">编辑</el-button><el-button v-permission="'DELETE /api/v1/access/roles/:id'" type="danger" @click="remove('roles',row)">删除</el-button></template></el-table-column></el-table>
 <el-card v-if="tab==='permissions'" class="top-gap"><h3>菜单与操作权限</h3><p>菜单权限控制可见页面及读取范围；操作权限分别控制新增、编辑、删除、下载、发布、设备控制等动作。后端会再次校验，每次请求均使用最新角色配置。</p><p>修改用户、停用用户或重置密码会使旧登录失效。角色被用户使用时不能删除。</p><p>智能助手、运行总览和巡检会查询租户内业务数据，请仅向需要该数据范围的人员开放这些菜单及相应执行权限。</p></el-card>
 <el-dialog :model-value="dialog==='user'||dialog==='role'" :title="`${editing?'编辑':'添加'}${dialog==='user'?'用户':'角色'}`" width="min(850px,94vw)" :close-on-click-modal="false" @close="dialog='';user.password=''">
  <el-form v-if="dialog==='user'" label-position="top" :disabled="saving"><el-form-item label="用户名" required><el-input v-model="user.username" :disabled="editing" autocomplete="off" placeholder="3至64位字母、数字、点、横线或下划线"/></el-form-item><el-form-item label="显示名称"><el-input v-model="user.displayName"/></el-form-item><el-form-item v-if="!editing" label="初始密码" required><el-input v-model="user.password" type="password" show-password autocomplete="new-password" placeholder="至少10位，最长72字节"/></el-form-item><el-form-item label="启用账户"><el-switch v-model="user.enabled"/></el-form-item><el-form-item label="角色"><el-select v-model="user.roleIds" multiple clearable style="width:100%"><el-option v-for="r in roles" :key="r.id" :label="r.name" :value="r.id"/></el-select></el-form-item><el-form-item label="用户单独授权（在角色基础上增加）"><PermissionPicker v-model="user.permissions" :catalog="catalog"/></el-form-item></el-form>
  <el-form v-else label-position="top" :disabled="saving"><el-form-item label="角色标识" required><el-input v-model="role.id" :disabled="editing" placeholder="例如 operations"/></el-form-item><el-form-item label="角色名称" required><el-input v-model="role.name" placeholder="例如 设备运维"/></el-form-item><el-form-item label="说明"><el-input v-model="role.description"/></el-form-item><el-form-item label="菜单与操作权限"><PermissionPicker v-model="role.permissions" :catalog="catalog"/></el-form-item></el-form>
  <template #footer><el-button :disabled="saving" @click="dialog='';user.password=''">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template>
 </el-dialog>
 <el-dialog :model-value="dialog==='password'" title="重置密码" width="min(460px,94vw)" @close="dialog='';password.value=''"><el-form label-position="top"><el-form-item :label="`用户：${password.username}`"><el-input v-model="password.value" type="password" show-password autocomplete="new-password" placeholder="至少10位，最长72字节"/></el-form-item></el-form><template #footer><el-button type="primary" :loading="saving" @click="savePassword">重置密码</el-button></template></el-dialog>
</template>
