<script setup>
import DeviceSelect from '../components/DeviceSelect.vue'
import { provideDeviceCatalog } from '../useDeviceCatalog.js'
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { ClipboardCheck, Plus, RefreshCw } from '@lucide/vue'
import { session } from '../api.js'
import { permissionState } from '../permissions.js'
import { canGovernance as can } from '../governance/permissions.js'
import { createClientId } from '../clientId.js'
import { governanceCatalog, governanceRead, governanceWrite } from '../governance/api.js'
import { activeRun, caseStates, conflictMessage, label, recordBody, time, tone } from '../governance/helpers.js'
import GovernanceConfig from '../components/governance/GovernanceConfig.vue'
import GovernanceActivities from '../components/governance/GovernanceActivities.vue'
import GovernanceCaseDetail from '../components/governance/GovernanceCaseDetail.vue'
import GovernanceResults from '../components/governance/GovernanceResults.vue'
import VerificationDialog from '../components/governance/VerificationDialog.vue'
import GovernanceHistory from '../components/governance/GovernanceHistory.vue'
const props=defineProps({deviceId:{type:String,default:''}})
const emit=defineEmits(['navigate'])
const tab=ref('cases'),devices=ref([]),configs=reactive({templates:[],'scene-presets':[],'type-profiles':[]}),cases=ref([]),candidates=ref([]),runs=ref([]),verifications=ref([]),reminders=ref([]),totals=reactive({cases:0,candidates:0,runs:0,verifications:0,reminders:0}),page=ref(1),filterDevice=ref(''),status=ref(''),owner=ref(''),loading=ref(false),saving=ref(false),error=ref(''),caseId=ref(''),selectedRun=ref(null),snapshot=ref(null),drawer=ref(false),caseDialog=ref(false),runDialog=ref(false),verificationDialog=ref(false),initial=ref({}),caseForm=reactive({}),runForm=reactive({}),detailComponent=ref(null),adoption=ref(null),candidateRunId=ref(''),runPlans=ref([])
const effectiveDevice=computed(()=>props.deviceId||filterDevice.value), deviceName=id=>devices.value.find(row=>row.id===id)?.name||id
const published=kind=>(configs[kind]||[]).map(recordBody).filter(row=>row.status==='PUBLISHED')
const currentCases=computed(()=>cases.value.map(recordBody)), verificationRows=computed(()=>verifications.value.map(recordBody)), total=computed(()=>totals[tab.value]||0)
const stateStorage=()=>`iot:governance-run:${session.tenant}:${session.user}:${permissionState.accessVersion}:${props.deviceId||'all'}`
const deviceCatalog = provideDeviceCatalog(devices, () => [props.deviceId,filterDevice.value,caseForm.deviceId,...(runForm.deviceIds||[]),...(selectedRun.value?.deviceIds||[])])
let generation=0,listGeneration=0,runGeneration=0,timer=0,disposed=false
function remember(id){try{if(id)sessionStorage.setItem(stateStorage(),id);else sessionStorage.removeItem(stateStorage())}catch{/* Server state stays available. */}}
function stop(){clearTimeout(timer);timer=0}
async function refreshRun(){if(!selectedRun.value?.id)return;const token=++runGeneration;try{const value=await governanceRead('runs',selectedRun.value.id);if(token!==runGeneration||disposed)return;if(value.parameters?.jobMode==='HISTORICAL_PROJECTION'){selectedRun.value=null;remember('');return}selectedRun.value=value;stop();if(activeRun(value))timer=setTimeout(refreshRun,1800);else if(tab.value==='runs')await loadList()}catch(cause){if(token===runGeneration&&!disposed){error.value=cause.message;stop();if([403,404].includes(cause.status)){selectedRun.value=null;remember('')}}}}
async function openRun(row){selectedRun.value=row;snapshot.value=null;remember(row.id);await refreshRun()}
async function loadList(){if(!['cases','candidates','runs','verifications','reminders'].includes(tab.value))return;const token=++listGeneration,view=generation;if(tab.value==='runs'){const value=await governanceCatalog('runs',{deviceIds:effectiveDevice.value?[effectiveDevice.value]:[]});if(token!==listGeneration||view!==generation||disposed)return;const ordinary=(value.items||[]).filter(row=>row.parameters?.jobMode!=='HISTORICAL_PROJECTION');totals.runs=ordinary.length;runs.value=ordinary.slice((page.value-1)*20,page.value*20);return}if(tab.value==='candidates'&&!candidateRunId.value){const completed=await governanceCatalog('runs');if(token!==listGeneration||disposed)return;runs.value=(completed.items||[]).filter(row=>row.parameters?.jobMode!=='HISTORICAL_PROJECTION');candidateRunId.value=runs.value.find(row=>row.snapshotId&&row.parameters?.jobMode!=='HISTORICAL_PROJECTION')?.id||'';if(!candidateRunId.value){candidates.value=[];totals.candidates=0;return}}const data=await governanceRead(tab.value,'','',{deviceIds:effectiveDevice.value?[effectiveDevice.value]:[],deviceId:effectiveDevice.value,runId:tab.value==='candidates'?candidateRunId.value:'',status:tab.value==='cases'?status.value:'',ownerUserId:tab.value==='cases'?owner.value:'',limit:20,offset:(page.value-1)*20});if(token!==listGeneration||view!==generation||disposed)return;if(tab.value==='cases')cases.value=data.items||[];else if(tab.value==='candidates')candidates.value=(data.items||[]).map(row=>({...recordBody(row),...(row.body?.point||row.point||{})}));else if(tab.value==='runs')runs.value=data.items||[];else if(tab.value==='reminders')reminders.value=(data.items||[]).map(recordBody);else verifications.value=data.items||[];totals[tab.value]=data.total??data.items?.length??0}
async function load(){const token=++generation;loading.value=true;error.value='';try{const mainList=loadList().catch(cause=>{if(token===generation&&!disposed)error.value=cause.message});const results=await Promise.allSettled(['templates','scene-presets','type-profiles'].map(kind=>governanceCatalog(kind)));if(token!==generation||disposed)return;results.forEach((result,index)=>{if(result.status==='rejected'){error.value=result.reason.message;return}configs[['templates','scene-presets','type-profiles'][index]]=result.value.items||[]});await mainList;if(!selectedRun.value){let id='';try{id=sessionStorage.getItem(stateStorage())||''}catch{}if(id)await openRun({id})}}catch(cause){if(token===generation)error.value=cause.message}finally{if(token===generation)loading.value=false}}
function openCase(row){caseId.value=row.id||row.existingCaseId;drawer.value=true;const id=caseId.value;governanceCatalog('runs').then(value=>{if(caseId.value===id)runs.value=(value.items||[]).filter(row=>row.parameters?.jobMode!=='HISTORICAL_PROJECTION')}).catch(cause=>error.value=cause.message)}
function newCase(source={}){if(source.existingCaseId){openCase({id:source.existingCaseId});return}const point=source.point||source;Object.assign(caseForm,{title:'',location:'',deviceId:point.deviceId||effectiveDevice.value||'',componentId:point.componentId||'',alarmType:point.alarmType||'',originKind:point.originKind||'',signalKey:point.signalKey||'',templateRevisionId:point.templateRevisionId||'',scenePresetRevisionId:point.scenePresetRevisionId||'',typeProfileRevisionId:point.typeProfileRevisionId||'',ownerUserId:session.user||'',observationIds:source.observationIds?.slice()||[],idempotencyKey:createClientId()});caseDialog.value=true;error.value=''}
async function saveCase(){if(saving.value||!can('POST /api/v1/alarm-governance/cases'))return;saving.value=true;error.value='';try{if(!caseForm.title||!caseForm.ownerUserId||!caseForm.deviceId||!caseForm.alarmType||!caseForm.originKind||!caseForm.signalKey)throw new Error('请填写标题、负责人、单一点位与原始信号');const value=await governanceWrite('cases','','',caseForm);caseDialog.value=false;openCase(value);await loadList()}catch(cause){error.value=conflictMessage(cause)}finally{saving.value=false}}
function quick(source={}){initial.value=source;verificationDialog.value=true}
function newRun(source={}){const now=Date.now();Object.assign(runForm,{deviceIds:source.deviceId?[source.deviceId]:effectiveDevice.value?[effectiveDevice.value]:[],range:[now-7*86400000,now],profileRevisionId:source.typeProfileRevisionId||'',caseId:source.id||'',roundId:source.roundId||source.currentRoundId||'',expectedDataRevision:source.dataRevision,planId:'',timeBasis:'EVENT_AT',includeHistoricalStandardMessages:false,historicalProjectionRunIds:[],reportEnabled:false,cyclesEnabled:false,openEnabled:false,minReportCount:null,minKnownCycleStarts:null,minOpenDurationHours:null,policyVersion:'',idempotencyKey:createClientId()});runPlans.value=[];runDialog.value=true;error.value='';if(runForm.roundId){const id=runForm.roundId;governanceCatalog('rounds',{},id,'observation-plans').then(value=>{if(id===runForm.roundId)runPlans.value=(value.items||[]).map(recordBody).filter(row=>row.status==='CONFIRMED')}).catch(cause=>error.value=cause.message)}}
async function saveRun(){if(saving.value||!can('POST /api/v1/alarm-governance/runs'))return;saving.value=true;error.value='';try{if(!runForm.deviceIds.length||!runForm.profileRevisionId||!runForm.range||!(runForm.range[1]>runForm.range[0]))throw new Error('请选择明确设备、类型配置与有效区间');if(runForm.cyclesEnabled&&published('type-profiles').find(row=>row.id===runForm.profileRevisionId)?.cycleMethod==='REPORT_ONLY')throw new Error('仅上报类型不能启用可靠周期条件');if(!runForm.caseId&&!runForm.reportEnabled&&!runForm.cyclesEnabled&&!runForm.openEnabled)throw new Error('请至少明确启用一个问题发现条件');const policy={window:runForm.range[1]-runForm.range[0],version:runForm.policyVersion||createClientId()};if(runForm.reportEnabled){if(!(runForm.minReportCount>0))throw new Error('请填写上报次数阈值');policy.minReportCount=runForm.minReportCount}if(runForm.cyclesEnabled){if(!(runForm.minKnownCycleStarts>0))throw new Error('请填写可靠新开始阈值');policy.minKnownCycleStarts=runForm.minKnownCycleStarts}if(runForm.openEnabled){if(!(runForm.minOpenDurationHours>0))throw new Error('请填写持续时间阈值');policy.minOpenDuration=runForm.minOpenDurationHours*3600000}const value=await governanceWrite('runs','','',{deviceIds:runForm.deviceIds,start:runForm.range[0],end:runForm.range[1],configurationVersion:runForm.profileRevisionId,parameters:{profileRevisionId:runForm.profileRevisionId,caseId:runForm.caseId,roundId:runForm.roundId,planId:runForm.planId,expectedDataRevision:runForm.expectedDataRevision,discoveryPolicy:policy,timeBasis:runForm.timeBasis,includeHistoricalStandardMessages:runForm.includeHistoricalStandardMessages,...(runForm.historicalProjectionRunIds?.length?{historicalProjectionRunIds:runForm.historicalProjectionRunIds}:{})},idempotencyKey:runForm.idempotencyKey});runDialog.value=false;tab.value='runs';page.value=1;await openRun(value);await loadList()}catch(cause){error.value=conflictMessage(cause)}finally{saving.value=false}}
async function stopRun(){if(saving.value||!selectedRun.value||!can('POST /api/v1/alarm-governance/runs/:id/stop'))return;saving.value=true;try{selectedRun.value=await governanceWrite('runs',selectedRun.value.id,'stop',{expectedVersion:selectedRun.value.version,idempotencyKey:createClientId()});await refreshRun()}catch(cause){error.value=conflictMessage(cause)}finally{saving.value=false}}
async function reminderAction(row,operation){if(saving.value||!can('POST /api/v1/alarm-governance/reminders/:id/'+operation))return;saving.value=true;try{await governanceWrite('reminders',row.id,operation,{expectedVersion:row.version,idempotencyKey:createClientId()});await loadList()}catch(cause){error.value=conflictMessage(cause)}finally{saving.value=false}}
async function refreshReminders(){if(saving.value)return;saving.value=true;try{await governanceWrite('reminders','refresh');await loadList()}catch(cause){error.value=cause.message}finally{saving.value=false}}
async function confirmVerification(row){if(saving.value||!can('POST /api/v1/alarm-governance/verifications/:id/confirm'))return;saving.value=true;try{await governanceWrite('verifications',row.id,'confirm',{expectedVersion:row.version,idempotencyKey:createClientId()});await loadList()}catch(cause){error.value=conflictMessage(cause)}finally{saving.value=false}}
function adopt(item){const id=selectedRun.value?.parameters?.caseId;if(!id){error.value='请在对应事项的固定分析中采纳候选解释。';return}caseId.value=id;adoption.value=item;drawer.value=true}
watch([tab,effectiveDevice,status,owner],()=>{page.value=1;void loadList().catch(cause=>error.value=cause.message)});watch(candidateRunId,()=>{if(tab.value==='candidates'){page.value=1;void loadList().catch(cause=>error.value=cause.message)}});watch(page,()=>loadList().catch(cause=>error.value=cause.message));watch(()=>[permissionState.accessVersion,session.tenant,session.user],()=>{generation++;runGeneration++;listGeneration++;stop();selectedRun.value=null;drawer.value=false;verificationDialog.value=false;caseDialog.value=false;runDialog.value=false;devices.value=[];cases.value=[];verifications.value=[];reminders.value=[];candidates.value=[];runs.value=[];candidateRunId.value='';runPlans.value=[];snapshot.value=null;adoption.value=null;void load()})
onMounted(()=>{if(!props.deviceId)try{const navigation=JSON.parse(sessionStorage.getItem('iot:navigation-detail')||'{}');sessionStorage.removeItem('iot:navigation-detail');filterDevice.value=navigation.deviceId||'';if(navigation.caseId)openCase({id:navigation.caseId});if(navigation.action==='verify')quick(navigation)}catch{}void load()});onBeforeUnmount(()=>{disposed=true;generation++;listGeneration++;runGeneration++;stop()})
</script>
<template><div class="governance-page gov-stack"><header class="gov-toolbar"><div><h1><ClipboardCheck/>反复报警治理</h1><p class="gov-meta">记录每次核实，调查原因、实施改善，再按固定口径观察复发。</p></div><div class="gov-actions"><ui-button size="small" :loading="loading" @click="load"><RefreshCw/>刷新</ui-button><ui-button v-if="can('POST /api/v1/alarm-governance/verifications')" size="small" @click="quick({deviceId:effectiveDevice})">填写核实</ui-button><ui-button v-if="can('POST /api/v1/alarm-governance/runs')" size="small" @click="newRun()">发现 / 分析问题</ui-button><ui-button v-if="can('POST /api/v1/alarm-governance/cases')" size="small" type="primary" @click="newCase()"><Plus/>建立事项</ui-button></div></header><ui-alert v-if="error&&!caseDialog&&!runDialog" :title="error" type="error" :closable="false"/><ui-tabs v-model="tab"><ui-tab-pane name="cases" label="治理事项"/><ui-tab-pane name="reminders" label="我的治理待办"/><ui-tab-pane name="candidates" label="问题汇总"/><ui-tab-pane name="verifications" label="独立核实"/><ui-tab-pane name="activities" label="活动与覆盖"/><ui-tab-pane name="runs" label="分析与解读"/><ui-tab-pane name="configs" label="模板与场景"/></ui-tabs><div v-if="['cases','candidates','verifications','runs'].includes(tab)" class="gov-filters"><DeviceSelect v-if="!deviceId" v-model="filterDevice" clearable placeholder="全部获授权设备"/><ui-select v-if="tab==='cases'" v-model="status" clearable placeholder="全部治理阶段"><ui-option v-for="[code,title] in Object.entries(caseStates)" :key="code" :value="code" :label="title"/></ui-select><ui-input v-if="tab==='cases'" v-model="owner" clearable placeholder="负责人账户"/></div><ui-skeleton v-if="loading&&!cases.length&&!runs.length" :rows="5"/>
<template v-else-if="tab==='cases'"><div class="gov-desktop-table"><ui-table :data="currentCases" empty-text="暂无治理事项。可从具体报警先登记核实，或由负责人建立事项。"><ui-table-column label="事项 / 点位" min-width="250"><template #default="{row}"><strong>{{row.title}}</strong><p class="gov-meta">{{deviceName(row.deviceId)}} · {{row.componentId||'设备'}} · {{row.alarmType}}</p></template></ui-table-column><ui-table-column label="负责人 / 位置" min-width="160"><template #default="{row}">{{row.ownerUserId}}<p class="gov-meta">{{row.location||'位置未知'}}</p></template></ui-table-column><ui-table-column label="阶段 / 新资料" min-width="180"><template #default="{row}"><ui-tag :type="tone(row.status)">{{label(row.status)}}</ui-tag><p class="gov-meta">资料版本 {{row.dataRevision}} · {{time(row.updatedAt)}}</p></template></ui-table-column><ui-table-column label="操作" width="100"><template #default="{row}"><ui-button text size="small" @click="openCase(row)">查看事项</ui-button></template></ui-table-column></ui-table></div><div class="gov-mobile-cards"><article v-for="row in currentCases" :key="row.id" class="gov-card"><strong>{{row.title}}</strong><p>{{deviceName(row.deviceId)}} · {{row.alarmType}}</p><ui-tag :type="tone(row.status)">{{label(row.status)}}</ui-tag><p class="gov-meta">{{row.ownerUserId}} · {{row.location||'位置未知'}} · 资料 {{row.dataRevision}}</p><ui-button text size="small" @click="openCase(row)">查看事项</ui-button></article><ui-empty v-if="!currentCases.length" description="暂无治理事项。"/></div></template>
<section v-else-if="tab==='candidates'" class="gov-stack"><ui-select v-model="candidateRunId" placeholder="选择已完成固定问题发现任务"><ui-option v-for="row in runs.filter(row=>row.snapshotId&&row.parameters?.jobMode!=='HISTORICAL_PROJECTION')" :key="row.id" :value="row.id" :label="`${time(row.createdAt)} · ${time(row.start)} ～ ${time(row.end)}`"/></ui-select><p class="gov-meta">候选来自已完成固定分析；独立条件合并显示。纯重复上报只提示上报问题。阈值由现场负责人配置。</p><div class="gov-cards"><article v-for="row in candidates" :key="row.id" class="gov-card"><strong>{{deviceName(row.deviceId)}} · {{row.alarmType}}</strong><p>{{(row.conditions||[]).map(item=>label(typeof item==='string'?item:item.description||item.kind)).join('；')}}</p><p class="gov-meta">{{time(row.window?.start)}} ～ {{time(row.window?.end)}} · {{label(row.coverage)}} · 策略 {{row.policyVersion}}</p><div class="gov-actions"><ui-button v-if="can('POST /api/v1/alarm-governance/verifications')" size="small" @click="quick(row)">具体事件核实</ui-button><ui-button v-if="row.existingCaseId||can('POST /api/v1/alarm-governance/cases')" size="small" @click="newCase(row)">{{row.existingCaseId?'追加 / 复核已有事项':'人工建立事项'}}</ui-button></div></article></div><ui-empty v-if="!candidates.length" description="暂无已完成分析提供的候选。先配置发现口径并运行分析。"/></section>
<section v-else-if="tab==='reminders'" class="gov-stack"><div class="gov-toolbar"><p class="gov-meta">当前用户受权范围内的持续待办；已读与已处理单独保存。</p><ui-button v-if="can('POST /api/v1/alarm-governance/reminders/refresh')" size="small" :loading="saving" @click="refreshReminders">更新治理待办</ui-button></div><div class="gov-metrics"><div v-for="code in ['MEASURE_OVERDUE','ACCEPTANCE_PENDING','OBSERVATION_INSUFFICIENT','POST_COMPLETION_REPORT']" :key="code"><span>{{label(code)}}（本页）</span><strong>{{reminders.filter(row=>row.category===code&&row.status!=='HANDLED').length}}</strong></div></div><article v-for="row in reminders" :key="row.id" class="gov-card"><div class="gov-toolbar"><strong>{{row.message||label(row.category)}}</strong><ui-tag>{{label(row.status)}}</ui-tag></div><p class="gov-meta">{{time(row.createdAt)}} · 关联事实 {{row.count}} 条 · {{row.dueAt?'期限 '+time(row.dueAt):'待负责人核对'}}</p><div class="gov-actions"><ui-button size="small" @click="openCase({id:row.caseId})">查看对应事项</ui-button><ui-button v-if="row.status==='UNREAD'&&can('POST /api/v1/alarm-governance/reminders/:id/read')" text size="small" :loading="saving" @click="reminderAction(row,'read')">标记已读</ui-button><ui-button v-if="row.status!=='HANDLED'&&can('POST /api/v1/alarm-governance/reminders/:id/handled')" text size="small" :loading="saving" @click="reminderAction(row,'handled')">标记已处理</ui-button></div></article><ui-empty v-if="!reminders.length" description="当前没有受权治理待办，可更新本人的待办范围。"/></section>
<section v-else-if="tab==='verifications'" class="gov-stack"><p class="gov-meta">现场登记可先于事项独立保存，不自动建事项或重开完成轮次。</p><div class="gov-cards"><article v-for="row in verificationRows" :key="row.id" class="gov-card"><div class="gov-toolbar"><strong>{{deviceName(row.deviceId)}} · {{label(row.fieldResult)}}</strong><ui-tag>{{label(row.status)}}</ui-tag></div><p>{{row.description}}</p><p class="gov-meta">{{label(row.verificationMethod)}} · 实际 {{time(row.verifiedAt)}} · 登记 {{time(row.recordedAt)}} · {{row.observationIds?.length||0}} 个具体事件</p><ui-button v-if="can(row.status==='DRAFT'?'PATCH /api/v1/alarm-governance/verifications/:id':'POST /api/v1/alarm-governance/verifications/:id/corrections')" text size="small" @click="quick(row)">{{row.status==='DRAFT'?'编辑草稿':'追加更正'}}</ui-button><ui-button v-if="row.status==='DRAFT'&&can('POST /api/v1/alarm-governance/verifications/:id/confirm')" text size="small" :loading="saving" @click="confirmVerification(row)">确认核实范围与依据</ui-button></article></div><ui-empty v-if="!verificationRows.length" description="暂无独立现场核实。"/></section>
<GovernanceActivities v-else-if="tab==='activities'" :devices="devices" :configs="configs" :device-id="effectiveDevice"/>
<GovernanceConfig v-else-if="tab==='configs'" :devices="devices" :configs="configs" @refresh="load"/>
<section v-else-if="tab==='runs'" class="gov-stack"><div class="gov-cards"><article v-for="row in runs" :key="row.id" class="gov-card"><div class="gov-toolbar"><strong>{{label(row.status)}}</strong><ui-button text size="small" @click="openRun(row)">查看固定任务</ui-button></div><p class="gov-meta">{{time(row.start)}} ～ {{time(row.end)}} · {{row.deviceIds?.map(deviceName).join('、')}}</p><p class="gov-meta">阶段 {{row.stage||'等待执行'}} · 实际处理 {{row.processed||0}} 条 · {{row.error}}</p></article></div><ui-empty v-if="!runs.length" description="尚无持久分析任务。"/><ui-alert v-if="selectedRun" :type="tone(selectedRun.status)" :closable="false"><div class="gov-toolbar"><strong>{{label(selectedRun.status)}} · 实际处理 {{selectedRun.processed||0}} 条</strong><ui-button v-if="activeRun(selectedRun)&&can('POST /api/v1/alarm-governance/runs/:id/stop')" size="small" :loading="saving" @click="stopRun">停止计算</ui-button></div><p class="gov-meta">{{selectedRun.stage}} · {{selectedRun.error||'刷新后恢复服务端进度'}}</p></ui-alert><GovernanceResults v-if="selectedRun" :run="selectedRun" :devices="devices" @candidate="newCase" @navigate="(...args)=>emit('navigate',...args)" @snapshot="snapshot=$event" @adopt="adopt"/></section>
<ui-pagination v-if="['cases','candidates','runs','verifications','reminders'].includes(tab)" :current-page="page" :page-size="20" :total="total" @current-change="page=$event"/></div>
<ui-drawer v-model="drawer" title="治理事项与历次轮次" size="min(1060px,96vw)"><div class="gov-drawer-body"><GovernanceCaseDetail v-if="drawer&&caseId" ref="detailComponent" :case-id="caseId" :devices="devices" :configs="configs" :runs="runs" :snapshot="snapshot" :adoption="adoption" @refresh="loadList" @navigate="(...args)=>emit('navigate',...args)" @analyse="newRun" @view-run="row=>{drawer=false;tab='runs';openRun(row)}"/></div></ui-drawer>
<VerificationDialog v-model="verificationDialog" :devices="devices" :configs="configs" :initial="initial" @saved="loadList" @navigate="(...args)=>emit('navigate',...args)"/>
<ui-dialog v-model="caseDialog" title="人工建立单点位治理事项" width="min(820px,94vw)" :close-on-click-modal="false"><div class="gov-dialog-body"><ui-alert v-if="error" :title="error" type="error" :closable="false"/><ui-form label-position="top" :disabled="saving"><div class="gov-grid"><ui-form-item label="事项标题" required><ui-input v-model="caseForm.title"/></ui-form-item><ui-form-item label="点位设备" required><DeviceSelect v-model="caseForm.deviceId"/></ui-form-item><ui-form-item label="部件 ID（设备级可空）"><ui-input v-model="caseForm.componentId"/></ui-form-item><ui-form-item label="原始报警类型" required><ui-input v-model="caseForm.alarmType" placeholder="保持真实报警代码"/></ui-form-item><ui-form-item label="来源语义" required><ui-select v-model="caseForm.originKind"><ui-option v-for="code in ['COMPONENT_STATE','DEVICE_DIRECT','RULE_LIFECYCLE']" :key="code" :value="code" :label="label(code)"/></ui-select></ui-form-item><ui-form-item label="明确信号键" required><ui-input v-model="caseForm.signalKey" placeholder="规则信号包含 ruleId"/></ui-form-item><ui-form-item label="历史位置"><ui-input v-model="caseForm.location"/></ui-form-item><ui-form-item label="负责人账户" required><ui-input v-model="caseForm.ownerUserId"/></ui-form-item><ui-form-item v-for="kind in ['templates','scene-presets','type-profiles']" :key="kind" :label="{templates:'固定模板版本','scene-presets':'固定场景版本','type-profiles':'固定报警类型版本'}[kind]" required><ui-select v-model="caseForm[{templates:'templateRevisionId','scene-presets':'scenePresetRevisionId','type-profiles':'typeProfileRevisionId'}[kind]]"><ui-option v-for="row in published(kind)" :key="row.id" :value="row.id" :label="`${row.name} · 版本 ${row.revisionNumber}`"/></ui-select></ui-form-item></div><p class="gov-meta">同一点位与信号仅允许一个活动事项。新事件只登记待核实，不继承旧成因。</p></ui-form></div><template #footer><ui-button :disabled="saving" @click="caseDialog=false">取消</ui-button><ui-button type="primary" :loading="saving" @click="saveCase">建立首轮事项</ui-button></template></ui-dialog>
<ui-dialog v-model="runDialog" title="固定事实分析与问题发现" width="min(780px,94vw)" :close-on-click-modal="false"><div class="gov-dialog-body"><ui-alert v-if="error" :title="error" type="error" :closable="false"/><ui-form label-position="top" :disabled="saving"><ui-form-item label="明确设备范围" required><DeviceSelect v-model="runForm.deviceIds" multiple/></ui-form-item><div class="gov-grid"><ui-form-item label="固定类型配置" required><ui-select v-model="runForm.profileRevisionId"><ui-option v-for="row in published('type-profiles')" :key="row.id" :value="row.id" :label="`${row.name} · ${label(row.cycleMethod)} · 版本 ${row.revisionNumber}`"/></ui-select></ui-form-item><ui-form-item label="有界时间窗口" required><ui-date-range v-model="runForm.range" disable-future/></ui-form-item><ui-form-item label="时间口径"><ui-select v-model="runForm.timeBasis"><ui-option value="EVENT_AT" label="可信设备事件时间"/><ui-option value="RECEIVED_AT" label="平台接收上报分布"/></ui-select></ui-form-item><ui-form-item v-if="runForm.caseId" label="已确认观察计划（正式评价需要）"><ui-select v-model="runForm.planId" clearable><ui-option v-for="row in runPlans" :key="row.id" :value="row.id" :label="`版本 ${row.version} · ${time(row.beforeStart)} ～ ${time(row.afterEnd)}`"/></ui-select></ui-form-item></div><ui-checkbox v-model="runForm.includeHistoricalStandardMessages">补充本窗口历史成功解析输入（覆盖标为部分，生产状态不变）</ui-checkbox><GovernanceHistory v-model="runForm.historicalProjectionRunIds" :devices="devices"/><h3>独立问题发现条件</h3><p class="gov-meta">按上报机制与现场工作负担启用条件；无通用消防阈值。仅上报类型不计算可靠周期。</p><div class="gov-grid"><ui-form-item label="上报次数"><div class="gov-stack"><ui-checkbox v-model="runForm.reportEnabled">启用去重上报阈值</ui-checkbox><ui-input-number v-if="runForm.reportEnabled" v-model="runForm.minReportCount" :min="1" :precision="0"/></div></ui-form-item><ui-form-item label="可靠新开始"><div class="gov-stack"><ui-checkbox v-model="runForm.cyclesEnabled">启用可靠周期阈值</ui-checkbox><ui-input-number v-if="runForm.cyclesEnabled" v-model="runForm.minKnownCycleStarts" :min="1" :precision="0"/></div></ui-form-item><ui-form-item label="持续未解除"><div class="gov-stack"><ui-checkbox v-model="runForm.openEnabled">启用可靠持续阈值</ui-checkbox><ui-input-number v-if="runForm.openEnabled" v-model="runForm.minOpenDurationHours" :min="0.001" placeholder="小时"/></div></ui-form-item></div></ui-form></div><template #footer><ui-button :disabled="saving" @click="runDialog=false">取消</ui-button><ui-button type="primary" :loading="saving" @click="saveRun">开始确定性计算</ui-button></template></ui-dialog>
</template>
<style>
.governance-page{min-width:0}.governance-page h1{display:flex;align-items:center;gap:8px;margin:0;font-size:20px}.governance-page h1 svg{width:21px;height:21px}.gov-stack{display:grid;gap:14px;grid-template-columns:minmax(0,1fr);min-width:0}.gov-toolbar,.gov-actions{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap;min-width:0}.gov-actions{justify-content:flex-start}.gov-meta{font-size:12px;color:var(--text-muted);line-height:1.7;margin:5px 0;overflow-wrap:anywhere}.gov-card{padding:14px;border:1px solid var(--border);background:var(--surface);border-radius:8px;min-width:0}.gov-card p{overflow-wrap:anywhere;white-space:pre-wrap}.gov-card h3,.gov-stack h3{font-size:14px;margin:0 0 9px}.gov-stack h2{font-size:18px;margin:0}.gov-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(320px,100%),1fr));gap:12px;min-width:0}.gov-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 14px;min-width:0}.gov-grid>*{min-width:0}.gov-dialog-body{max-height:68vh;overflow:auto;min-width:0;padding:0 3px 8px 0}.gov-drawer-body{min-width:0;overflow:auto}.gov-compact{width:300px;max-width:100%}.gov-filters{display:flex;gap:8px;flex-wrap:wrap}.gov-filters>*{flex:1;min-width:160px}.gov-desktop-table{overflow:auto;min-width:0}.gov-mobile-cards{display:none}.gov-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.gov-metrics span{font-size:12px;color:var(--text-muted)}.gov-metrics strong{display:block;font-size:19px;overflow-wrap:anywhere}.gov-fact{font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere;max-height:40vh;overflow:auto}details summary{cursor:pointer;font-size:12px;color:var(--text-muted)}@media(max-width:640px){.gov-grid{grid-template-columns:minmax(0,1fr)}.gov-desktop-table{display:none}.gov-mobile-cards{display:grid;gap:10px}.gov-dialog-body{max-height:64vh}.gov-toolbar{align-items:flex-start}.gov-toolbar>.ui-input{flex-basis:100%}.gov-card{padding:11px}.gov-actions .ui-button{max-width:100%}.governance-page h1{font-size:18px}.gov-filters>*{min-width:100%;}.gov-compact{width:100%}}
</style>
