<script setup>
import { computed,onBeforeUnmount,onMounted,reactive,ref,watch } from 'vue'
import { Wrench,RefreshCw } from '@lucide/vue'
import { apiAll,session } from '../api.js'
import { can,permissionState } from '../permissions.js'
import { createClientId } from '../clientId.js'
import { maintenanceAll,maintenanceRead,maintenanceWrite,maintenanceRevision } from '../maintenance/api.js'
import { observationPayload,stateLabel,maintenanceTime,runIsActive } from '../maintenance/helpers.js'
import MaintenanceAssets from '../components/maintenance/MaintenanceAssets.vue'
import MaintenanceRecords from '../components/maintenance/MaintenanceRecords.vue'
import MaintenanceContexts from '../components/maintenance/MaintenanceContexts.vue'
import MaintenanceInvestments from '../components/maintenance/MaintenanceInvestments.vue'
import MaintenanceResults from '../components/maintenance/MaintenanceResults.vue'
const props=defineProps({assetId:String,maintenanceRecordId:String,deviceId:String,scenarioId:String})
const emit=defineEmits(['navigate'])
const tab=ref('assets'),loading=ref(false),error=ref(''),devices=ref([]),assets=ref([]),records=ref([]),contexts=ref([]),admissions=ref([]),faults=ref([]),costs=ref([]),scenarios=ref([]),observations=ref([]),correctives=ref([]),qualityRuns=ref([]),selectedAsset=ref(null),work=ref(null),scenario=ref(null),observation=ref(null),investment=ref(null),workRuns=ref([]),scenarioRuns=ref([]),investmentSnapshot=ref(null),viewKey=ref(0),initialDevice=ref('')
const dialog=ref(false),busy=ref(false),formError=ref(''),form=reactive({comparisonType:'SAME_INSTANCE_REPAIR',beforeAssetRevisionId:'',afterAssetRevisionId:'',switchAt:null,before:null,after:null,contextRevisionIds:[],qualityRunIds:[],admissionRevisionId:'',useFinance:false,idempotencyKey:''})
let generation=0,selectionGeneration=0,runGeneration=0,disposed=false,timer=0,initial={}
const effectiveDevice=computed(()=>props.deviceId||initialDevice.value),effectiveAsset=computed(()=>selectedAsset.value?.resourceId||props.assetId||''),currentRun=computed(()=>tab.value==='scenarios'?investment.value:observation.value),activeRuns=computed(()=>tab.value==='scenarios'?scenarioRuns.value:workRuns.value),runResource=computed(()=>tab.value==='scenarios'?'investment-evaluations':'maintenance-observations'),allowedAssets=computed(()=>assets.value.filter(a=>work.value?.deviceIds.includes(a.body.deviceId))),allowedContexts=computed(()=>contexts.value.filter(c=>c.deviceIds.every(id=>work.value?.deviceIds.includes(id)))),allowedAdmissions=computed(()=>admissions.value.filter(c=>c.deviceIds.every(id=>work.value?.deviceIds.includes(id))))
const cacheKey=()=>`iot:maintenance:${session.tenant}:${session.user}:${effectiveDevice.value||'all'}:${permissionState.accessVersion||''}`
function remember(){try{sessionStorage.setItem(cacheKey(),JSON.stringify({tab:tab.value,assetId:selectedAsset.value?.resourceId,maintenanceRecordId:work.value?.resourceId,scenarioId:scenario.value?.resourceId,observationRunId:observation.value?.id,investmentRunId:investment.value?.id}))}catch{}}
function stopPolling(){clearTimeout(timer);timer=0}
function reset(){generation++;selectionGeneration++;runGeneration++;viewKey.value++;stopPolling();for(const r of [devices,assets,records,contexts,costs,admissions,faults,scenarios,observations,correctives,qualityRuns,workRuns,scenarioRuns])r.value=[];for(const r of [selectedAsset,work,scenario,observation,investment,investmentSnapshot])r.value=null;dialog.value=false}
async function assetRevision(id){if(assets.value.some(a=>a.id===id))return null;return await maintenanceRevision(id,'assets')}
function checkScope(row){if(effectiveDevice.value&&!row.deviceIds.includes(effectiveDevice.value))throw Error('固定记录不属于当前设备范围')}
async function loadRelated(){const token=generation,workId=work.value?.resourceId,scenarioId=scenario.value?.resourceId;const [w,s]=await Promise.all([workId?maintenanceAll('maintenance-records',workId,'observations'):Promise.resolve({items:[]}),scenarioId?maintenanceAll('investment-scenarios',scenarioId,'evaluations'):Promise.resolve({items:[]})]);if(token!==generation||disposed||workId!==work.value?.resourceId||scenarioId!==scenario.value?.resourceId)return;workRuns.value=w.items||[];scenarioRuns.value=s.items||[]}
async function restore(value){const token=generation,sel=++selectionGeneration;stopPolling();let w=null,s=null,a=null,o=null,i=null;const oldAssets=[];if(value.observationRunId||(!value.scenarioId&&value.runId)){o=await maintenanceRead('maintenance-observations',value.observationRunId||value.runId);const input=await maintenanceRevision(o.parameters.observation.interventionRevisionId,'maintenance-records');value={...value,maintenanceRecordId:input.resourceId};for(const id of [o.parameters.observation.beforeAssetRevisionId,o.parameters.observation.afterAssetRevisionId]){const a=await assetRevision(id);if(a)oldAssets.push(a)}}if(value.investmentRunId||(value.scenarioId&&value.runId)){i=await maintenanceRead('investment-evaluations',value.investmentRunId||value.runId);const input=await maintenanceRevision(i.parameters.scenarioRevisionId,'investment-scenarios');value={...value,scenarioId:input.resourceId}}if(value.assetId)a=await maintenanceRead('assets',value.assetId);if(value.maintenanceRecordId){w=await maintenanceRead('maintenance-records',value.maintenanceRecordId);const old=await assetRevision(w.body.assetRevisionId);if(old)oldAssets.push(old)}if(value.scenarioId){s=await maintenanceRead('investment-scenarios',value.scenarioId);for(const c of s.body.candidates){const old=await assetRevision(c.assetRevisionId);if(old)oldAssets.push(old)}}if(token!==generation||sel!==selectionGeneration||disposed)return;for(const row of [a,w,s,o,i])if(row)checkScope(row);for(const row of oldAssets)if(!assets.value.some(a=>a.id===row.id))assets.value.push(row);selectedAsset.value=a;work.value=w;scenario.value=s;observation.value=o;investment.value=i;tab.value=value.tab||(s?'scenarios':w?'records':'assets');await loadRelated();remember();schedule()}
async function load(){const token=++generation;loading.value=true;error.value='';try{if(!can('menu:devices'))throw Error('维护与投入需要设备管理读取权限与已分配设备范围。');const catalog=['assets','maintenance-records','maintenance-contexts','maintenance-admissions','maintenance-fault-cycles','investment-scenarios','maintenance-observations'];const values=await Promise.all([apiAll('/api/v1/device-registry'),...catalog.map(p=>maintenanceAll(p)),can('GET /api/v1/maintenance-costs')?maintenanceAll('maintenance-costs'):Promise.resolve({items:[]}),can('menu:response')?maintenanceAll('corrective-actions'):Promise.resolve({items:[]}),can('menu:dataQuality')?maintenanceAll('data-quality/runs'):Promise.resolve({items:[]})]);if(token!==generation||disposed)return;devices.value=(values[0].items||[]).map(r=>r.device||r).filter(r=>r.id);[assets.value,records.value,contexts.value,admissions.value,faults.value,scenarios.value,observations.value,costs.value,correctives.value,qualityRuns.value]=values.slice(1).map(v=>v.items||[]);const current={assetId:selectedAsset.value?.resourceId,maintenanceRecordId:work.value?.resourceId,scenarioId:scenario.value?.resourceId,observationRunId:observation.value?.id,investmentRunId:investment.value?.id,tab:tab.value};let remembered;try{remembered=JSON.parse(sessionStorage.getItem(cacheKey())||'null')}catch{}const value=Object.values(initial).some(Boolean)?initial:(current.assetId||current.maintenanceRecordId||current.scenarioId?current:remembered);if(value){await restore(value);initial={}}}catch(cause){if(token===generation&&!disposed){error.value=cause.message;if([403,404].includes(cause.status)){selectedAsset.value=null;work.value=null;scenario.value=null;observation.value=null;investment.value=null;investmentSnapshot.value=null;stopPolling()}}}finally{if(token===generation)loading.value=false}}
function selectAsset(row){selectedAsset.value=row;work.value=null;observation.value=null;workRuns.value=[];tab.value='records';remember()}
async function selectWork(row){if(!row)return;const token=++selectionGeneration;work.value=row;observation.value=null;workRuns.value=[];error.value='';try{const old=await assetRevision(row.body.assetRevisionId),fresh=await maintenanceRead('maintenance-records',row.resourceId);if(token!==selectionGeneration||disposed)return;if(old)assets.value.push(old);work.value=fresh;await loadRelated();remember()}catch(cause){if(token===selectionGeneration){error.value=cause.message;work.value=null}}}
async function selectScenario(row){const token=++selectionGeneration;scenario.value=row;investment.value=null;investmentSnapshot.value=null;scenarioRuns.value=[];error.value='';try{const fresh=await maintenanceRead('investment-scenarios',row.resourceId);if(token!==selectionGeneration||disposed)return;scenario.value=fresh;await loadRelated();remember()}catch(cause){if(token===selectionGeneration){error.value=cause.message;scenario.value=null}}}
async function refreshRun(){const token=++runGeneration;const entries=[['maintenance-observations',observation],['investment-evaluations',investment]];for(const [resource,target] of entries){const id=target.value?.id;if(!id)continue;try{const value=await maintenanceRead(resource,id);if(token!==runGeneration||disposed||id!==target.value?.id)return;target.value=value}catch(cause){if(token===runGeneration){error.value=cause.message;target.value=null;investmentSnapshot.value=null;stopPolling()}}}await loadRelated()}
function schedule(){stopPolling();if(disposed)return;if(runIsActive(observation.value)||runIsActive(investment.value))timer=setTimeout(async()=>{try{await refreshRun();schedule()}catch(cause){error.value=cause.message;stopPolling()}},1800)}
async function selectRun(row){const target=tab.value==='scenarios'?investment:observation;target.value=row;investmentSnapshot.value=null;remember();await refreshRun();schedule()}
async function stopRun(){if(!currentRun.value)return;try{await maintenanceWrite(runResource.value,currentRun.value.id,'stop',{expectedVersion:currentRun.value.version});await refreshRun();schedule()}catch(cause){error.value=cause.message}}
async function beginObservation(row){await selectWork(row);if(!work.value)return;Object.assign(form,{comparisonType:'SAME_INSTANCE_REPAIR',beforeAssetRevisionId:row.body.assetRevisionId,afterAssetRevisionId:row.body.assetRevisionId,switchAt:null,before:null,after:null,contextRevisionIds:[],qualityRunIds:[],admissionRevisionId:'',useFinance:false,idempotencyKey:createClientId()});formError.value='';dialog.value=true}
async function observe(){if(busy.value)return;const token=generation;busy.value=true;formError.value='';try{const value=await maintenanceWrite('maintenance-records',work.value.resourceId,'observations',observationPayload(form,work.value,assets.value,form.idempotencyKey));if(token!==generation||disposed)return;observation.value=value;dialog.value=false;tab.value='observations';remember();await loadRelated();schedule()}catch(cause){if(token===generation)formError.value=cause.status===409?'维修或资料版本已变化，请刷新后重新选择固定输入。':cause.message}finally{if(token===generation)busy.value=false}}
async function evaluate(row){if(busy.value)return;busy.value=true;const token=generation;try{await selectScenario(row);if(!scenario.value)return;const value=await maintenanceWrite('investment-scenarios',scenario.value.resourceId,'evaluate',{expectedVersion:scenario.value.version,idempotencyKey:createClientId(),useFinance:!!scenario.value.body.useFinance});if(token!==generation||disposed)return;investment.value=value;tab.value='scenarios';remember();await loadRelated();schedule()}catch(cause){if(token===generation)error.value=cause.message}finally{if(token===generation)busy.value=false}}
function navigate(name,detail){if(name!=='maintenance')return emit('navigate',name,detail);error.value='';restore(detail).catch(cause=>{error.value=cause.message;work.value=null;scenario.value=null;observation.value=null;investment.value=null})}
watch(tab,remember);watch(()=>[props.assetId,props.maintenanceRecordId,props.deviceId,props.scenarioId,permissionState.accessVersion,session.tenant,session.user],()=>{reset();initial={assetId:props.assetId,maintenanceRecordId:props.maintenanceRecordId,scenarioId:props.scenarioId};load()})
onMounted(()=>{try{const value=JSON.parse(sessionStorage.getItem('iot:navigation-detail')||'{}');initialDevice.value=typeof value.deviceId==='string'?value.deviceId:'';initial={...value,assetId:props.assetId||value.assetId,maintenanceRecordId:props.maintenanceRecordId||value.maintenanceRecordId,scenarioId:props.scenarioId||value.scenarioId};sessionStorage.removeItem('iot:navigation-detail')}catch{}load()});onBeforeUnmount(()=>{disposed=true;generation++;selectionGeneration++;runGeneration++;stopPolling()})
</script>
<template><section class="maintenance-page"><header class="maintenance-toolbar"><div><h1><Wrench/>维护与投入</h1><p class="maintenance-hint">实物、实际干预、独立验收、固定变化观察与透明投入决定。</p></div><ui-button size="small" :loading="loading" @click="load"><RefreshCw/>刷新</ui-button></header><ui-alert v-if="error" :title="error" type="error" :closable="false"><ui-button size="small" @click="load">重新读取</ui-button></ui-alert><ui-tabs v-model="tab"><ui-tab-pane name="assets" label="实物资产"/><ui-tab-pane name="records" label="维修与验收"/><ui-tab-pane name="observations" label="变化观察"/><ui-tab-pane name="scenarios" label="投入方案"/><ui-tab-pane name="context" label="工况与准入"/></ui-tabs><ui-skeleton v-if="loading&&!assets.length" :rows="5"/><template v-else><MaintenanceAssets v-if="tab==='assets'" :key="viewKey+'assets'" :items="assets" :devices="devices" :device-id="effectiveDevice" @select="selectAsset" @refresh="load" @navigate="navigate"/><MaintenanceRecords v-if="tab==='records'" :key="viewKey+'records'" :items="records" :assets="assets" :devices="devices" :device-id="effectiveDevice" :asset-id="effectiveAsset" :selected="work" :correctives="correctives" @select="selectWork" @observe="beginObservation" @refresh="load" @navigate="navigate"/><MaintenanceContexts v-if="tab==='context'" :key="viewKey+'context'" :devices="devices" :assets="assets" :records="records" :contexts="contexts" :admissions="admissions" :faults="faults" :costs="costs" :device-id="effectiveDevice" @refresh="load" @navigate="navigate"/><MaintenanceInvestments v-if="tab==='scenarios'" :key="viewKey+'scenarios'" :items="scenarios" :assets="assets" :records="records" :costs="costs" :observations="observations" :selected="scenario" :run="investment" :snapshot="investmentSnapshot" :device-id="effectiveDevice" @select="selectScenario" @evaluate="evaluate" @refresh="load"/>
<section v-if="tab==='observations'" class="maintenance-stack"><div class="maintenance-toolbar"><h3>维修变化观察</h3><ui-button v-if="work?.body.status==='COMPLETED'&&can('POST /api/v1/maintenance-records/:id/observations')" size="small" @click="beginObservation(work)">建立新的固定观察</ui-button></div><ui-select :model-value="work?.resourceId" placeholder="选择已结束的实际维修记录" @update:model-value="selectWork(records.find(r=>r.resourceId===$event))"><ui-option v-for="r in records.filter(r=>r.body.status==='COMPLETED'&&(!effectiveDevice||r.deviceIds.includes(effectiveDevice)))" :key="r.resourceId" :value="r.resourceId" :label="r.body.name"/></ui-select></section>
<section v-if="['observations','scenarios'].includes(tab)" class="maintenance-stack"><h3>持久计算版本</h3><div class="maintenance-table-scroll"><ui-table :data="activeRuns" empty-text="请选择实际来源，尚无固定计算版本。"><ui-table-column label="固定区间 / 建立时间" min-width="250"><template #default="{row}">{{maintenanceTime(row.start)}} 至 {{maintenanceTime(row.end)}}<p class="maintenance-meta">{{maintenanceTime(row.createdAt)}}</p></template></ui-table-column><ui-table-column label="状态 / 实际处理量" min-width="180"><template #default="{row}">{{stateLabel(row.status)}}<p class="maintenance-meta">实际处理 {{row.processed}} 条固定记录</p></template></ui-table-column><ui-table-column label="操作" width="130"><template #default="{row}"><ui-button text size="small" :data-maintenance-run="row.id" @click="selectRun(row)">读取固定事实</ui-button></template></ui-table-column></ui-table></div><ui-alert v-if="currentRun" :closable="false" :type="currentRun.status==='FAILED'?'error':'info'"><div class="maintenance-toolbar"><p>{{stateLabel(currentRun.status)}} · 实际处理 {{currentRun.processed}} 条固定记录<br>{{currentRun.error}}</p><ui-button v-if="runIsActive(currentRun)&&can('POST /api/v1/'+runResource+'/:id/stop')" size="small" @click="stopRun">停止事实计算</ui-button></div></ui-alert><MaintenanceResults v-if="currentRun" :run="currentRun" :scenario="scenario" :devices="devices" :assets="assets" :investment="tab==='scenarios'" @snapshot="investmentSnapshot=$event" @refresh="refreshRun" @navigate="navigate"/></section></template>
<ui-dialog v-model="dialog" title="绑定固定实物与窗口建立变化观察" width="min(940px,94vw)" :close-on-click-modal="false"><div v-if="work" class="maintenance-dialog-body maintenance-stack"><ui-alert v-if="formError" :title="formError" type="error" :closable="false"/><p class="maintenance-meta">{{work.body.name}} · 工作固定版本 {{work.version}}<br>实际维修 {{maintenanceTime(work.body.startedAt)}} 至 {{maintenanceTime(work.body.endedAt)}}</p><ui-form label-position="top" :disabled="busy"><ui-form-item label="比较类型" required><ui-select v-model="form.comparisonType"><ui-option value="SAME_INSTANCE_REPAIR" label="同实物维修前后"/><ui-option value="CROSS_INSTANCE_REPLACEMENT" label="跨实物替换前后"/></ui-select></ui-form-item><div class="maintenance-grid"><ui-form-item label="维修前固定实物" required><ui-select v-model="form.beforeAssetRevisionId"><ui-option v-for="a in allowedAssets" :key="a.id" :value="a.id" :label="`${a.body.name} · ${a.body.physicalId} · 版本 ${a.version}`"/></ui-select></ui-form-item><ui-form-item label="维修后固定实物" required><ui-select v-model="form.afterAssetRevisionId"><ui-option v-for="a in allowedAssets" :key="a.id" :value="a.id" :label="`${a.body.name} · ${a.body.physicalId} · 版本 ${a.version}`"/></ui-select></ui-form-item></div><ui-form-item v-if="form.comparisonType==='CROSS_INSTANCE_REPLACEMENT'" label="实际旧新实物切换时间" required><ui-date-time v-model="form.switchAt" disable-future/></ui-form-item><ui-form-item label="维修前观察窗口" required><ui-date-range v-model="form.before"/></ui-form-item><ui-form-item label="维修后观察窗口（未来部分保持观察中）" required><ui-date-range v-model="form.after"/></ui-form-item><ui-form-item label="固定工况版本"><ui-select v-model="form.contextRevisionIds" multiple><ui-option v-for="c in allowedContexts" :key="c.id" :value="c.id" :label="`${c.body.intensity||c.body.reason} · ${maintenanceTime(c.body.start)} · 版本 ${c.version}`"/></ui-select></ui-form-item><ui-form-item label="固定比较准入要求（未选则仅描述）"><ui-select v-model="form.admissionRevisionId" clearable><ui-option v-for="a in allowedAdmissions" :key="a.id" :value="a.id" :label="`${a.body.faultType} · ${a.body.parameters.version} · 固定版本 ${a.version}`"/></ui-select></ui-form-item><ui-form-item v-if="can('menu:dataQuality')" label="固定数据质量报告（选填）"><ui-select v-model="form.qualityRunIds" multiple><ui-option v-for="r in qualityRuns.filter(r=>['SUCCEEDED','PARTIAL'].includes(r.status)&&r.deviceIds.every(id=>work.deviceIds.includes(id)))" :key="r.id" :value="r.id" :label="`${maintenanceTime(r.createdAt)} · ${stateLabel(r.status)}`"/></ui-select></ui-form-item><ui-checkbox v-model="form.useFinance" :disabled="!can('GET /api/v1/maintenance-costs')">此观察版本使用已记录实际费用，全部结果继承资金权限</ui-checkbox></ui-form><p class="maintenance-hint">前后窗口与固定实物有效期求交，排除有依据区间的并集。设备离线仍计入有效分母；实物边界未知不能跨实例比较。</p></div><template #footer><ui-button :disabled="busy" @click="dialog=false">取消</ui-button><ui-button type="primary" :loading="busy" @click="observe">开始固定变化计算</ui-button></template></ui-dialog></section></template>
<style>.maintenance-page,.maintenance-stack{display:grid;grid-template-columns:minmax(0,1fr);gap:14px;min-width:0}.maintenance-toolbar,.maintenance-actions{display:flex;align-items:center;justify-content:space-between;gap:9px;flex-wrap:wrap;min-width:0}.maintenance-actions{justify-content:flex-end}.maintenance-toolbar>div{min-width:0}.maintenance-page h1{display:flex;align-items:center;gap:8px;font-size:20px;margin:0}.maintenance-page h1 svg{width:21px;height:21px}.maintenance-page h3,.maintenance-dialog-body h3{font-size:14px;margin:0}.maintenance-meta,.maintenance-hint{font-size:12px;line-height:1.65;color:var(--text-muted);margin:5px 0;white-space:pre-wrap;overflow-wrap:anywhere}.maintenance-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 14px}.maintenance-card{background:var(--surface);padding:14px;border:1px solid var(--border);border-radius:8px;min-width:0}.maintenance-dialog-body{display:grid;grid-template-columns:minmax(0,1fr);gap:13px;max-height:68vh;overflow:auto;padding:0 4px 8px 0;min-width:0}.maintenance-dialog-body p{overflow-wrap:anywhere}.maintenance-table-scroll{overflow-x:auto;min-width:0}.maintenance-table-scroll .n-data-table{min-width:690px}.maintenance-native-table{border-collapse:collapse;width:100%;min-width:640px;font-size:12px}.maintenance-native-table th,.maintenance-native-table td{text-align:left;padding:9px;border-bottom:1px solid var(--border);overflow-wrap:anywhere}.maintenance-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.maintenance-stats article{display:grid;gap:6px;padding:12px;background:var(--surface-soft);border-radius:6px}.maintenance-stats strong{font-size:19px}@media(max-width:600px){.maintenance-grid{grid-template-columns:minmax(0,1fr)}.maintenance-dialog-body{max-height:65vh}.maintenance-toolbar{align-items:flex-start}.maintenance-page h1{font-size:18px}}</style>
