<script setup>
import { provideDeviceCatalog } from '../useDeviceCatalog.js'
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { ClipboardCheck, RefreshCw } from '@lucide/vue'
import { session } from '../api.js'
import { can, permissionState } from '../permissions.js'
import { createClientId } from '../clientId.js'
import { responseAll, responseRead, responseWrite } from '../response/api.js'
import { evaluationPayload, responseTime, runIsActive, stateLabel } from '../response/helpers.js'
import ResponseProcedures from '../components/response/ResponseProcedures.vue'
import ResponseExecutions from '../components/response/ResponseExecutions.vue'
import ResponseReviewResults from '../components/response/ResponseReviewResults.vue'
import ResponseCorrectiveActions from '../components/response/ResponseCorrectiveActions.vue'
const props=defineProps({executionId:String,alarmId:String,deviceId:String})
const emit=defineEmits(['navigate'])
const tab=ref('executions'),loading=ref(false),error=ref(''),devices=ref([]),procedures=ref([]),executions=ref([]),correctives=ref([]),selected=ref(null),runs=ref([]),run=ref(null),page=ref(1),total=ref(0),viewKey=ref(0),initialAlarm=ref(''),initialDevice=ref(''),initialExecution=ref(''),initialCorrective=ref(''),initialRun=ref('')
const evaluationDialog=ref(false),evaluating=ref(false),evaluationError=ref(''),evaluationForm=reactive({end:null,cutoff:null,idempotencyKey:''})
const effectiveDevice=computed(()=>props.deviceId||initialDevice.value),effectiveAlarm=computed(()=>props.alarmId||initialAlarm.value),scopedExecutions=computed(()=>executions.value.filter(row=>(!effectiveDevice.value||row.deviceIds.includes(effectiveDevice.value))&&(!effectiveAlarm.value||row.body.alarmId===effectiveAlarm.value)))
const deviceCatalog = provideDeviceCatalog(devices, () => [props.deviceId,initialDevice.value,...(selected.value?.deviceIds||[])])
let generation=0,listGeneration=0,selectionGeneration=0,runGeneration=0,timer=0,disposed=false
const cacheKey=()=>`iot:response:${session.tenant}:${session.user}:${effectiveDevice.value||'all'}:${effectiveAlarm.value||'all'}:${permissionState.accessVersion||''}`
function remember(){try{sessionStorage.setItem(cacheKey(),JSON.stringify({executionId:selected.value?.resourceId||'',runId:run.value?.id||''}))}catch{/* Fixed records remain server-owned. */}}
function stopPolling(){clearTimeout(timer);timer=0}
function schedule(){stopPolling();if(!disposed&&runIsActive(run.value))timer=setTimeout(async()=>{await refreshRun();schedule()},1800)}
function reset(){generation++;listGeneration++;selectionGeneration++;runGeneration++;viewKey.value++;stopPolling();devices.value=[];procedures.value=[];executions.value=[];correctives.value=[];selected.value=null;runs.value=[];run.value=null;total.value=0;page.value=1;evaluationDialog.value=false;evaluating.value=false}
async function loadRuns(){const token=++listGeneration,id=selected.value?.resourceId;if(!id){runs.value=[];total.value=0;return}const value=await responseRead('response-runs',id,'evaluations',{limit:20,offset:(page.value-1)*20});if(token!==listGeneration||disposed)return;runs.value=value.items||[];total.value=value.total||0}
async function refreshSelected(){const token=++selectionGeneration,id=selected.value?.resourceId;if(!id)return;const value=await responseRead('response-runs',id);if(token!==selectionGeneration||disposed)return;selected.value=value;executions.value=executions.value.map(row=>row.resourceId===id?value:row)}
async function refreshRun(){const token=++runGeneration,id=run.value?.id;if(!id)return;try{const value=await responseRead('response-evaluations',id);if(token!==runGeneration||disposed)return;run.value=value;if(!runIsActive(value))await loadRuns()}catch(cause){if(token===runGeneration&&!disposed){error.value=cause.message;if([403,404].includes(cause.status)){run.value=null;remember();stopPolling()}}}}
async function selectExecution(row){selectionGeneration++;runGeneration++;stopPolling();selected.value=row;run.value=null;page.value=1;error.value='';remember();try{await refreshSelected();await loadRuns()}catch(cause){if(disposed||selected.value?.resourceId!==row.resourceId)return;error.value=cause.message;if([403,404].includes(cause.status)){selected.value=null;runs.value=[];remember()}}}
async function selectRun(row){selectionGeneration++;run.value=row;remember();await refreshRun();schedule()}
async function restore(value){const token=generation,selectionToken=++selectionGeneration,runToken=++runGeneration;stopPolling();let record=null,executionId=value.executionId;if(value.runId){record=await responseRead('response-evaluations',value.runId);const input=await responseRead('response-revisions',record.parameters.executionRevisionId);executionId=input.resourceId}const execution=executionId?await responseRead('response-runs',executionId):null;if(token!==generation||selectionToken!==selectionGeneration||runToken!==runGeneration||disposed)return;if(execution){if(effectiveDevice.value&&!execution.deviceIds.includes(effectiveDevice.value))throw Error('固定执行不属于当前设备');if(effectiveAlarm.value&&execution.body.alarmId!==effectiveAlarm.value)throw Error('固定执行不属于当前告警')}selected.value=execution;run.value=record;if(execution){await loadRuns();tab.value='executions'}remember();schedule()}
async function load(){const token=++generation;loading.value=true;error.value='';try{if(!can('menu:devices'))throw Error('演练与复盘需要设备管理读取权限与已分配范围。');const values=await Promise.all([responseAll('response-procedures'),responseAll('drills'),responseAll('response-cases'),responseAll('corrective-actions')]);if(token!==generation||disposed)return;procedures.value=values[0].items||[];executions.value=[...(values[1].items||[]),...(values[2].items||[])].sort((a,b)=>b.createdAt-a.createdAt);correctives.value=values[3].items||[];if(selected.value){await refreshSelected();await loadRuns();await refreshRun()}else{let remembered;try{remembered=JSON.parse(sessionStorage.getItem(cacheKey())||'null')}catch{/* Invalid IDs do not change public source lists. */}if(initialExecution.value||initialRun.value){await restore({executionId:initialExecution.value,runId:initialRun.value});initialExecution.value='';initialRun.value=''}else if(remembered&&!effectiveAlarm.value&&!initialCorrective.value)await restore(remembered)}}catch(cause){if(token===generation&&!disposed){error.value=cause.message;if([403,404].includes(cause.status)){selected.value=null;run.value=null;runs.value=[];remember()}}}finally{if(token===generation)loading.value=false}}
function beginEvaluation(){evaluationError.value='';Object.assign(evaluationForm,{end:selected.value.body.endedAt||Date.now(),cutoff:Date.now(),idempotencyKey:createClientId()});evaluationDialog.value=true}
async function navigate(name,detail){if(name!=='response')return emit('navigate',name,detail);if(detail.correctiveId){initialCorrective.value=detail.correctiveId;tab.value='correctives';return}if(detail.executionId||detail.runId){initialCorrective.value='';tab.value='executions';error.value='';try{await restore(detail)}catch(cause){error.value=cause.message;selected.value=null;run.value=null}}}
async function evaluate(){if(evaluating.value)return;const token=generation;evaluating.value=true;evaluationError.value='';try{const body=evaluationPayload(selected.value,evaluationForm.end,evaluationForm.cutoff,evaluationForm.idempotencyKey),record=await responseWrite('response-runs',selected.value.resourceId,'evaluations',body);if(token!==generation||disposed)return;run.value=record;evaluationDialog.value=false;remember();await loadRuns();schedule()}catch(cause){if(token===generation&&!disposed)evaluationError.value=cause.status===409?'执行版本已变化，请刷新后生成新的固定复盘。':cause.message}finally{if(token===generation)evaluating.value=false}}
async function stopRun(){if(!run.value)return;try{await responseWrite('response-evaluations',run.value.id,'stop',{expectedVersion:run.value.version});await refreshRun();schedule()}catch(cause){error.value=cause.message}}
watch(page,()=>loadRuns().catch(cause=>{error.value=cause.message}));watch(()=>[props.executionId,props.alarmId,props.deviceId,permissionState.accessVersion,session.tenant,session.user],()=>{reset();initialExecution.value=props.executionId||'';load()})
onMounted(()=>{try{const detail=JSON.parse(sessionStorage.getItem('iot:navigation-detail')||'{}');initialAlarm.value=typeof detail.alarmId==='string'?detail.alarmId:'';initialDevice.value=typeof detail.deviceId==='string'?detail.deviceId:'';initialExecution.value=props.executionId||(typeof detail.executionId==='string'?detail.executionId:'');sessionStorage.removeItem('iot:navigation-detail');initialRun.value=typeof detail.runId==='string'?detail.runId:'';if(detail.correctiveId){initialCorrective.value=detail.correctiveId;tab.value='correctives'}}catch{/* Invalid navigation state is ignored. */}load()})
onBeforeUnmount(()=>{disposed=true;generation++;selectionGeneration++;listGeneration++;runGeneration++;stopPolling()})
</script>
<template><section class="response-review-page"><header class="response-toolbar"><div><h1><ClipboardCheck/>演练与处置复盘</h1><p class="response-hint">计划、执行证据、固定复盘与独立整改。</p></div><ui-button size="small" :loading="loading" @click="load"><RefreshCw/>刷新</ui-button></header><ui-alert v-if="error" :title="error" type="error" :closable="false"><ui-button size="small" @click="load">重新读取</ui-button></ui-alert><ui-tabs v-model="tab"><ui-tab-pane name="executions" label="计划与执行"/><ui-tab-pane name="procedures" label="流程版本"/><ui-tab-pane name="correctives" label="整改与验收"/></ui-tabs><ui-skeleton v-if="loading&&!executions.length&&!procedures.length" :rows="5"/><template v-else><ResponseProcedures v-if="tab==='procedures'" :key="viewKey+'-procedures'" :items="procedures" :devices="devices" :device-id="effectiveDevice" @refresh="load"/><ResponseCorrectiveActions v-else-if="tab==='correctives'" :key="viewKey+'-correctives'" :items="correctives" :devices="devices" :executions="executions" :device-id="effectiveDevice" :initial-id="initialCorrective" @refresh="load" @navigate="navigate"/><section v-else class="response-stack"><ResponseExecutions :key="viewKey+'-executions'" :items="scopedExecutions" :procedures="procedures" :devices="devices" :selected="selected" :device-id="effectiveDevice" :alarm-id="effectiveAlarm" @select="selectExecution" @refresh="load" @evaluate="beginEvaluation" @navigate="navigate"/><template v-if="selected"><h3>固定复盘版本</h3><div class="response-table-scroll"><ui-table :data="runs" empty-text="此执行尚无固定复盘版本。"><ui-table-column label="区间 / 截止" min-width="230"><template #default="{row}">{{responseTime(row.start)}} 至 {{responseTime(row.end)}}<p class="response-meta">资料截至 {{responseTime(row.parameters.cutoff)}}</p></template></ui-table-column><ui-table-column label="状态 / 处理量" min-width="180"><template #default="{row}">{{stateLabel(row.status)}}<p class="response-meta">实际处理 {{row.processed}} 个步骤</p></template></ui-table-column><ui-table-column label="操作" width="100"><template #default="{row}"><ui-button :data-response-evaluation="row.id" text size="small" @click="selectRun(row)">查看固定复盘</ui-button></template></ui-table-column></ui-table></div><ui-pagination :current-page="page" :page-size="20" :total="total" @current-change="page=$event"/></template><ui-alert v-if="run" :type="run.status==='FAILED'?'error':'info'" :closable="false"><div class="response-toolbar"><p>{{stateLabel(run.status)}} · 实际处理 {{run.processed}} 个步骤<br>{{run.error}}</p><ui-button v-if="runIsActive(run)&&can('POST /api/v1/response-evaluations/:id/stop')" size="small" @click="stopRun">停止复盘计算</ui-button></div></ui-alert><ResponseReviewResults v-if="run&&selected" :run="run" :execution="selected" :devices="devices" @refresh="load" @navigate="navigate"/></section></template></section>
<ui-dialog v-model="evaluationDialog" title="生成固定资料复盘版本" width="min(650px,94vw)" :close-on-click-modal="false" @close="evaluationDialog=false"><div v-if="selected" class="response-dialog-body"><ui-alert v-if="evaluationError" :title="evaluationError" type="error" :closable="false"/><p>执行版本 {{selected.version}} · {{selected.body.name}}<br>实际开始 {{responseTime(selected.body.startedAt)}}</p><ui-form label-position="top" :disabled="evaluating"><ui-form-item label="本次执行观察结束" required><ui-date-time v-model="evaluationForm.end" :disabled="!!selected.body.endedAt" disable-future/></ui-form-item><ui-form-item label="资料登记截止" required><ui-date-time v-model="evaluationForm.cutoff" disable-future/></ui-form-item></ui-form><p class="response-hint">执行版本、节点与截止时间在此复盘中固定。后续补登记另行生成新版本，原正式报告仍可查看。</p></div><template #footer><ui-button :disabled="evaluating" @click="evaluationDialog=false">取消</ui-button><ui-button type="primary" :loading="evaluating" @click="evaluate">开始固定事实计算</ui-button></template></ui-dialog></template>
<style>.response-review-page,.response-stack{display:grid;grid-template-columns:minmax(0,1fr);gap:14px;min-width:0}.response-review-page h1{display:flex;align-items:center;gap:8px;font-size:20px;margin:0}.response-review-page h1 svg{width:21px;height:21px}.response-review-page h3,.response-dialog-body h3{font-size:14px;margin:0}.response-toolbar,.response-actions{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:9px;min-width:0}.response-actions{justify-content:flex-end}.response-toolbar>div{min-width:0}.response-hint,.response-meta{color:var(--text-muted);font-size:12px;line-height:1.65;margin:5px 0;overflow-wrap:anywhere;white-space:pre-wrap}.response-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 14px}.response-card{padding:14px;min-width:0;background:var(--surface);border:1px solid var(--border);border-radius:8px}.response-dialog-body{display:grid;grid-template-columns:minmax(0,1fr);gap:13px;max-height:68vh;overflow:auto;padding:0 4px 8px 0;min-width:0}.response-dialog-body p{overflow-wrap:anywhere}.response-table-scroll{overflow-x:auto;min-width:0}.response-table-scroll .n-data-table{min-width:670px}.response-native-table{width:100%;min-width:640px;border-collapse:collapse;font-size:12px}.response-native-table th,.response-native-table td{padding:9px;border-bottom:1px solid var(--border);text-align:left;overflow-wrap:anywhere}.response-tags{display:flex;flex-wrap:wrap;gap:6px}.response-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.response-stats article{display:grid;gap:6px;padding:12px;background:var(--surface-soft);border-radius:6px}.response-stats strong{font-size:21px}.response-stat-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.response-stat-grid article{padding:13px;background:var(--surface);border:1px solid var(--border);border-radius:8px}.response-stat-grid strong{display:block;font-size:18px}.response-filter-row{display:flex;gap:8px;flex-wrap:wrap}.response-filter-row>*{flex:1;min-width:150px}@media(max-width:640px){.response-grid{grid-template-columns:minmax(0,1fr)}.response-dialog-body{max-height:65vh}.response-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.response-stats article{display:grid;gap:6px;padding:12px;background:var(--surface-soft);border-radius:6px}.response-stats strong{font-size:21px}.response-stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.response-actions{justify-content:flex-start}.response-card{padding:11px}.response-review-page h1{font-size:18px}}</style>
