import { stateLabel as commonLabel,stateTone,runIsActive } from '../quality/helpers.js'
import { durationLabel,monitoringTime } from '../monitoring/helpers.js'
export { stateTone,runIsActive,durationLabel }
export const maintenanceTime=monitoringTime
export const labels={DRAFT:'草稿',IN_PROGRESS:'工作进行中',COMPLETED:'工作记录已结束',CANCELLED:'已取消',PENDING:'待功能验收',PASSED:'功能验收通过',FAILED:'失败',UNKNOWN:'未知或未确认',CONFIRMED:'人工已确认',DISPUTED:'存在争议',PLANNED:'已规划观察',OBSERVING:'观察中',READY:'具备描述性比较条件',REVIEWED:'已人工核实',INSUFFICIENT:'证据不足',CONFOUNDED:'存在混杂',DECIDED:'已记录人工决定',ARCHIVED:'已归档',PRODUCTION:'生产来源',TEST:'测试来源',FAULT:'同类故障',FIRE:'真实火警',OTHER:'其他周期',COMPARABLE:'可参与同口径排序',AWAITING_INFORMATION:'同层待补资料',INCLUDED_IN_ORDERED_TRIAL:'已纳入有序预算试算',ADDITIONAL_BUDGET_REQUIRED:'需追加预算',QUOTE_MISSING_OR_INCOMPARABLE:'报价缺失或口径不同',PRIORITY_UNCONFIRMED:'优先顺序待确认',BUDGET_UNKNOWN:'预算未知',EARLIER_QUOTE_OR_PRIORITY_UNKNOWN:'前序报价或顺序未知',FINANCE_NOT_INCLUDED:'本版本不使用资金',SAME_INSTANCE_REPAIR:'同实物维修前后',CROSS_INSTANCE_REPLACEMENT:'跨实物替换前后',INSPECTION:'检查',REPAIR:'维修',REPLACEMENT:'实物替换',CALIBRATION:'校准',PREVENTIVE:'预防维护',ESTIMATE:'未来估算或报价',ACTUAL:'已发生支出',OBSERVE:'继续观察',INSPECT:'进一步检查',CALIBRATE:'校准',REPLACE:'评估替换'}
export const stateLabel=value=>{const prefix=String(value||'').match(/^(BEFORE|AFTER):(.+)$/);const required=String(value||'').match(/^(REQUIRED_TIER|MANUAL_IMPORTANCE)_(\d+)$/);if(required)return(required[1]==='REQUIRED_TIER'?'人工必需层 ':'人工重要性 ')+required[2];return prefix?(prefix[1]==='BEFORE'?'维修前：':'维修后：')+stateLabel(prefix[2]):labels[value]||commonLabel(value)}
export const contextKinds={OPERATING_INTENSITY:'运行强度',PLANNED_STOP:'有依据的计划停运',CONFIRMED_TEST:'已确认测试',PLATFORM_OBSERVATION_UNAVAILABLE:'平台观测不可用',CONSTRUCTION:'施工影响',RULE_CHANGE:'规则变更',PROTOCOL_CHANGE:'协议变更',GATEWAY_CHANGE:'网关变更',POINT_TABLE_CHANGE:'测点变更',REPORT_PERIOD_CHANGE:'上报周期变更'}
export const evidenceKinds={HUMAN_CONFIRMATION:'人工核实资料',ATTACHMENT:'受权附件',ALARM:'实际生产告警周期',ALARM_REPORT:'单次设备上报',ALARM_LIFECYCLE:'已提交告警事务',RAW_MESSAGE:'具体原始报文'}
export const reviewStates={CONFIRMED_PROBLEM:'已确认存在问题',NORMAL_EXPLANATION:'有正常解释',RESOLVED:'已解决',OBSERVE:'继续观察'}
export const listLines=value=>String(value||'').split('\n').map(value=>value.trim()).filter(Boolean)
export const unwrapOutputs=rows=>(rows||[]).map(row=>({...row.body,id:row.id,deviceId:row.deviceId}))
export const hours=value=>value==null||!Number.isFinite(value)||value<0?'未知':`${(value/3600000).toFixed(4)} 小时`
export const number=value=>value==null||!Number.isFinite(value)?'未知':String(value)
export const money=value=>value==null||value===''?'未知':String(value)
export function ratio(value,denominator){if(denominator===0)return'不适用';return !(denominator>0)||value==null||!Number.isFinite(value)||value<0||value>1?'未知':`${(value*100).toFixed(1)}%`}
export function decimal(value){if(value==null||value==='')return null;const text=String(value).trim();if(!/^(0|[1-9]\d{0,23})(\.\d{1,6})?$/.test(text))throw Error('金额和工时须为非负精确十进制，最多6位小数；未知保留空白');return text}
export const revisionEnvelope=(form,body,key,deviceIds)=>({resourceId:form.resourceId,expectedVersion:form.expectedVersion||0,deviceIds:[...new Set(deviceIds||form.deviceIds||[])].sort(),idempotencyKey:key,body})
export function evidencePayload(rows,devices){return(rows||[]).map(row=>{if(!evidenceKinds[row.kind]||!devices.includes(row.deviceId)||(row.kind==='HUMAN_CONFIRMATION'?!String(row.description||'').trim():!row.sourceId))throw Error('资料须引用当前设备范围内的具体记录，并有人工核实依据');return{kind:row.kind,sourceId:row.kind==='HUMAN_CONFIRMATION'?'':row.sourceId,deviceId:row.deviceId,description:String(row.description||'').trim()}})}
export function assetDraft(row){const b=row?.body||{};return{resourceId:row?.resourceId||'',expectedVersion:row?.version||0,name:b.name||'',deviceId:b.deviceId||'',componentId:b.componentId||'',physicalId:b.physicalId||'',manufacturedAt:b.manufacturedAt??null,installedAt:b.installedAt??null,commissionedAt:b.commissionedAt??null,retiredAt:b.retiredAt??null,effectiveStart:b.effectiveStart??null,effectiveEnd:b.effectiveEnd??null,boundaryStatus:b.boundaryStatus||'UNKNOWN',importance:b.importance??null,evidence:(b.evidence||[]).map(row=>({...row}))}}
export function assetPayload(form,key){if(!form.name.trim()||!form.physicalId.trim()||!form.deviceId||!(form.effectiveStart>0)||!Number.isInteger(form.importance)||form.importance<0||form.importance>9)throw Error('请明确实物名称、稳定标识、设备、有效起点与人工重要性');if(form.effectiveEnd!=null&&form.effectiveEnd<=form.effectiveStart)throw Error('实物有效区间须为起点小于终点');const body={name:form.name.trim(),deviceId:form.deviceId,componentId:form.componentId,physicalId:form.physicalId.trim(),effectiveStart:form.effectiveStart,boundaryStatus:form.boundaryStatus,importance:form.importance,evidence:evidencePayload(form.evidence,[form.deviceId])};for(const key of ['manufacturedAt','installedAt','commissionedAt','retiredAt','effectiveEnd'])if(form[key]!=null)body[key]=form[key];if(form.boundaryStatus==='CONFIRMED'&&!body.evidence.length)throw Error('确认实物边界须关联实际依据');return revisionEnvelope(form,body,key,[form.deviceId])}
export function observationPayload(form,work,assets,key){if(work?.body?.status!=='COMPLETED')throw Error('观察需要已结束的维修记录');const before=assets.find(row=>row.id===form.beforeAssetRevisionId),after=assets.find(row=>row.id===form.afterAssetRevisionId);if(!before||!after||before.body.deviceId!==after.body.deviceId||before.body.componentId!==after.body.componentId)throw Error('前后须绑定同设备或同稳定部件槽的固定实物');if(!form.before?.[0]||!(form.before[1]>form.before[0])||!form.after?.[0]||!(form.after[1]>form.after[0])||form.before[1]>work.body.startedAt||form.after[0]<work.body.endedAt||form.before[1]>form.after[0])throw Error('前窗口须在实际维修前，后窗口在工作结束后，且不得重叠');if(form.comparisonType==='SAME_INSTANCE_REPAIR'&&before.resourceId!==after.resourceId)throw Error('同实例维修须绑定同一实物资源');if(form.comparisonType==='CROSS_INSTANCE_REPLACEMENT'&&(before.resourceId===after.resourceId||before.body.boundaryStatus!=='CONFIRMED'||after.body.boundaryStatus!=='CONFIRMED'||before.body.effectiveEnd!==form.switchAt||after.body.effectiveStart!==form.switchAt))throw Error('跨实例须确认旧实例结束、新实例起点与实际切换时间');return{expectedVersion:work.version,idempotencyKey:key,useFinance:!!form.useFinance,parameters:{comparisonType:form.comparisonType,beforeAssetRevisionId:before.id,afterAssetRevisionId:after.id,switchAt:form.switchAt||0,before:{start:form.before[0],end:form.before[1]},after:{start:form.after[0],end:form.after[1]},contextRevisionIds:[...(form.contextRevisionIds||[])],qualityRunIds:[...(form.qualityRunIds||[])],admissionRevisionId:form.admissionRevisionId||''}}}

export function workPayload(form,assets,key){const asset=assets.find(row=>row.id===form.assetRevisionId);if(!asset||!form.name.trim()||!form.reason.trim()||!['INSPECTION','REPAIR','REPLACEMENT','CALIBRATION','PREVENTIVE'].includes(form.type))throw Error('请选择固定实物，并填写工作名称、类型与原因');return revisionEnvelope(form,{name:form.name.trim(),assetRevisionId:asset.id,type:form.type,status:'DRAFT',reason:form.reason.trim(),actions:listLines(form.actions),people:listLines(form.people),parts:listLines(form.parts),faultCycleIds:form.faultCycleIds||[],correctiveActionId:form.correctiveActionId||''},key,asset.deviceIds)}
export function verificationPayload(form,work,key){const required=listLines(form.requiredItems),checked=form.checkedItems||[],evidence=evidencePayload(form.evidence,work.deviceIds);if(!required.length||!form.explanation.trim())throw Error('请填写规定验收项与实际依据');if(checked.some(item=>!required.includes(item)))throw Error('实际核验项须属于规定验收项');if(form.result==='PASSED'&&(!required.every(item=>checked.includes(item))||!evidence.length))throw Error('功能通过须逐项核验并有关联证据');return{expectedVersion:work.version,idempotencyKey:key,verification:{requiredItems:required,checkedItems:checked,result:form.result,explanation:form.explanation.trim(),evidence}}}
export function scenarioPayload(form,assets,key){if(!form.name.trim()||!form.planning?.[0]||!(form.planning[1]>form.planning[0])||!form.candidates?.length)throw Error('请明确方案名称、规划期与实际候选动作');const ids=new Set();const devices=[];const candidates=form.candidates.map(c=>{const asset=assets.find(row=>row.id===c.assetRevisionId);if(!asset||!c.id||ids.has(c.id)||!Number.isInteger(c.requiredTier)||c.requiredTier<1||c.requiredTier>9||!c.tierBasis.trim())throw Error('候选须有固定实物、唯一身份与人工必需分层依据');ids.add(c.id);devices.push(...asset.deviceIds);return{id:c.id,assetRevisionId:asset.id,action:c.action,requiredTier:c.requiredTier,tierBasis:c.tierBasis.trim(),observationRunId:c.observationRunId||'',defectBasisIds:c.defectBasisIds||[],quoteRevisionId:form.useFinance?c.quoteRevisionId||'':'',constraints:listLines(c.constraints)}});return revisionEnvelope(form,{name:form.name.trim(),status:'DRAFT',useFinance:!!form.useFinance,currency:form.currency,planningStart:form.planning[0],planningEnd:form.planning[1],budget:form.useFinance?decimal(form.budget):null,policyVersion:'required-tier-transparent-v1',candidates},key,devices)}
export function orderedAdjustment(order,candidates){if(order.length!==candidates.length||new Set(order).size!==order.length||candidates.some(c=>!order.includes(c.id)))throw Error('人工顺序须包含每个候选且仅一次');return [...order]}
export const metricCells=side=>[{label:'原窗口',value:hours(side.windowMs)},{label:'与实物期相交',value:hours(side.assetWindowMs)},{label:'排除并集',value:hours(side.excludedMs)},{label:'有效观察',value:hours(side.effectiveMs)},{label:'观测覆盖率',value:ratio(side.observationCoverage,side.assetWindowMs)},{label:'已确认同类故障周期',value:number(side.confirmedFaultCycles)},{label:'故障来源已知',value:hours(side.faultSourceKnownMs)},{label:'故障来源未知',value:hours(side.faultSourceUnknownMs)},{label:'故障来源覆盖',value:ratio(side.faultSourceCoverage,side.effectiveMs)},{label:'确认故障率（次/1000小时）',value:side.effectiveMs===0?'不适用':number(side.faultsPer1000Hours)},{label:'已确认在线',value:hours(side.onlineMs)},{label:'已确认离线',value:hours(side.offlineMs)},{label:'状态未知',value:hours(side.stateUnknownMs)},{label:'已知区间离线比例',value:ratio(side.knownOfflineRatio,side.onlineMs+side.offlineMs)},{label:'状态覆盖率',value:ratio(side.stateCoverage,side.effectiveMs)},{label:'完整窗口离线比例',value:side.stateUnknownMs>0?'未知':ratio(side.fullWindowOfflineRatio,side.effectiveMs)}]

Object.assign(labels,{ASSET_INSTANCE:'固定实物实例',MAINTENANCE_RECORD:'固定维修记录',OPERATING_CONTEXT:'固定工况',MAINTENANCE_ADMISSION:'固定准入参数',MAINTENANCE_COST:'固定费用记录',ASSET_BOUNDARY_UNKNOWN_OR_DISPUTED:'实物边界未知或有争议',COMMISSIONING_DATE_AND_AGE_UNKNOWN:'实际投运日期与年限未知',COMPARISON_ADMISSION_NOT_CONFIGURED:'未配置比较准入要求，仅展示描述性指标',CONNECTION_STATE_INTERVAL_UNKNOWN:'连接状态区间存在未知',DESCRIPTIVE_CHANGE_DOES_NOT_PROVE_CAUSALITY_OR_SAFETY:'描述性变化不证明因果关系或安全性',FAULT_CYCLE_IDENTITY_DISPUTED:'故障周期身份存在争议',FAULT_EVENT_CLOCK_UNKNOWN:'故障事件时钟未知',FAULT_RATE_ADMISSION_OR_SOURCE_INSUFFICIENT:'故障率准入要求或来源覆盖不足',FAULT_SOURCE_INTERVAL_UNKNOWN:'故障事件来源存在未知区间',FUNCTIONAL_VERIFICATION_NOT_PASSED:'独立功能验收尚未通过',OPERATING_CONTEXT_UNKNOWN_OR_INCOMPARABLE:'运行工况未知或不可比较',POST_MAINTENANCE_WAIT_INSUFFICIENT:'维修后实际等待期不足',WINDOW_OUTSIDE_PHYSICAL_ASSET:'观察窗口不在已确认实物有效期内',OPERATING_INTENSITY_CHANGED:'前后运行强度发生变化',PLANNED_AFTER_WINDOW_STILL_OPEN:'计划后窗口尚未结束，统计只截至已发生时点',SOURCE_OR_CONFIGURATION_HISTORY_INSUFFICIENT:'来源或配置历史不足',AFTER_OBSERVATION_NOT_STARTED:'后窗口观察尚未开始',NO_COMPLETENESS_OR_ZERO_FAULT_INFERENCE:'当前资料不能推断完整覆盖或零故障风险',RUN_TIME_BUDGET_EXHAUSTED:'计算时限已到，保留实际完成部分',TIME_BUDGET_EXHAUSTED_BEFORE_INPUT_FREEZE:'固定输入前计算时限已到',UNIT_CONFIRMED_TIER_BASIS:'依据单位人工确认的必需分层',UNRESOLVED_VERIFIED_FUNCTIONAL_DEFECT:'存在已核实且未解除的功能缺陷',CONFIRMED_FAULT_RATE_SAME_BASIS:'使用同口径确认故障率',KNOWN_OFFLINE_DURATION:'使用已确认离线时长',MISSING_OR_INCOMPARABLE_METRICS_NOT_LOW_RISK:'指标缺失或不可比较，不视为低风险',EXPLICIT_HUMAN_ORDER_WITH_RECORDED_REASON:'使用有依据且已保存的完整人工顺序',DESCRIPTIVE_PRIORITY_AND_BUDGET_TRIAL_NOT_OPTIMAL_PROCUREMENT:'描述性排序与预算试算，不代表最优采购组合',KNOWN_QUOTES_ARE_NOT_COMPLETE_BUDGET_COST:'已知报价不能代替完整预算费用',NO_ROI_OR_CAUSAL_BENEFIT_INFERRED:'不推断投入收益率或维修因果收益'})

export function eligibleObservations(runs,asset,assets){if(!asset)return[];return(runs||[]).filter(run=>{const after=assets.find(a=>a.id===run.parameters?.observation?.afterAssetRevisionId);return after&&after.resourceId===asset.resourceId&&after.body.deviceId===asset.body.deviceId&&['SUCCEEDED','PARTIAL'].includes(run.status)})}

export const verificationLabel=value=>({PENDING:'待功能验收',PASSED:'功能验收通过',FAILED:'功能验收失败',UNKNOWN:'功能未知或未确认'})[value]||stateLabel(value)
