<script setup>
import { useDeviceLabels } from '../../useDeviceCatalog.js'
import { onBeforeUnmount,ref,watch } from 'vue'
import { Paperclip,Plus } from '@lucide/vue'
import { can } from '../../permissions.js'
import { createClientId } from '../../clientId.js'
import { maintenanceAttachment,maintenanceUpload } from '../../maintenance/api.js'
import { evidenceKinds,maintenanceTime } from '../../maintenance/helpers.js'
const props=defineProps({modelValue:{type:Array,default:()=>[]},devices:{type:Array,default:()=>[]},disabled:Boolean,readonly:Boolean})
useDeviceLabels(() => props.devices.map(row => row.id))
const emit=defineEmits(['update:modelValue','navigate'])
const input=ref(null),error=ref(''),uploading=ref(false),pending=ref(null)
let key='',generation=0,disposed=false
function add(){emit('update:modelValue',[...props.modelValue,{kind:'HUMAN_CONFIRMATION',deviceId:props.devices[0]?.id||'',sourceId:'',description:''}])}
function remove(index){emit('update:modelValue',props.modelValue.filter((_,i)=>i!==index))}
async function upload(event){const file=event?.target?.files?.[0]||pending.value;if(!file||uploading.value)return;const token=generation;if(pending.value!==file){pending.value=file;key=createClientId()}uploading.value=true;error.value='';try{if(file.size>16*1024*1024||!props.devices.length)throw Error('请选择明确设备范围，附件最大16MiB');const value=await maintenanceUpload(file,props.devices.map(row=>row.id),key);if(token!==generation||disposed)return;emit('update:modelValue',[...props.modelValue,{kind:'ATTACHMENT',deviceId:props.devices[0].id,sourceId:value.id,description:value.body.name}]);pending.value=null;key='';input.value.value=''}catch(cause){if(token===generation&&!disposed)error.value=cause.message}finally{if(token===generation)uploading.value=false}}
async function download(row){try{await maintenanceAttachment(row.sourceId,row.description)}catch(cause){error.value=cause.message}}
watch(()=>props.devices.map(d=>d.id).sort().join(','),()=>{generation++;pending.value=null;key='';uploading.value=false;error.value='';if(input.value)input.value.value=''})
onBeforeUnmount(()=>{disposed=true;generation++})
</script>
<template><div class="maintenance-stack"><div v-if="!readonly" class="maintenance-toolbar"><strong>实际依据资料</strong><div class="maintenance-actions"><ui-button size="small" :disabled="disabled||!devices.length" @click="add"><Plus/>增加实际依据</ui-button><ui-button v-if="can('POST /api/v1/maintenance-attachments')" size="small" :disabled="disabled||!devices.length" :loading="uploading" @click="input.click()"><Paperclip/>上传维护附件</ui-button><input ref="input" type="file" style="display:none" @change="upload"></div></div><ui-alert v-if="error" :title="error" type="error" :closable="false"/><ui-button v-if="pending&&!uploading" size="small" :disabled="disabled" @click="upload()">重试上传 {{pending.name}}</ui-button><article v-for="(row,index) in modelValue" :key="row.id||index" class="maintenance-card"><template v-if="readonly"><strong>{{evidenceKinds[row.kind]||row.kind}}</strong><p>{{row.description}}</p><p class="maintenance-meta">{{maintenanceTime(row.recordedAt)}} · {{row.deviceId}}</p></template><template v-else><div class="maintenance-grid"><ui-form-item label="实际依据类型"><ui-select v-model="row.kind" :disabled="disabled||row.kind==='ATTACHMENT'" @change="row.sourceId='' "><ui-option v-for="[value,label] in Object.entries(evidenceKinds)" :key="value" :value="value" :label="label"/></ui-select></ui-form-item><ui-form-item label="依据设备"><ui-select v-model="row.deviceId" :disabled="disabled"><ui-option v-for="d in devices" :key="d.id" :value="d.id" :label="d.name||d.id"/></ui-select></ui-form-item></div><ui-form-item v-if="row.kind!=='HUMAN_CONFIRMATION'" label="单次具体来源 ID"><ui-input v-model="row.sourceId" :disabled="disabled||row.kind==='ATTACHMENT'" placeholder="服务器按实际资料校验租户、设备和来源"/></ui-form-item><ui-form-item label="实际核实内容或资料说明" required><ui-input v-model="row.description" type="textarea" :rows="2" :disabled="disabled"/></ui-form-item></template><div class="maintenance-actions"><ui-button v-if="row.kind==='ATTACHMENT'&&can('GET /api/v1/maintenance-attachments/:id')" text size="small" @click="download(row)">受权下载原件</ui-button><ui-button v-if="!readonly" text size="small" :disabled="disabled" @click="remove(index)">移除关联</ui-button><ui-button v-if="readonly&&row.kind==='RAW_MESSAGE'&&can('menu:raw')" text size="small" @click="emit('navigate','raw',{deviceId:row.deviceId,messageId:row.sourceId})">读取具体原文</ui-button></div></article><p v-if="!modelValue.length" class="maintenance-hint">尚未关联实际依据；未知日期、边界和费用继续保留未知。</p></div></template>
