<script setup>
import { deviceChoices } from '../../deviceCatalog.js'
import DeviceSelect from '../DeviceSelect.vue'
import { computed,onBeforeUnmount,reactive,ref } from 'vue'
import { Plus } from '@lucide/vue'
import { apiAll } from '../../api.js'
import { can } from '../../permissions.js'
import { createClientId } from '../../clientId.js'
import { maintenanceWrite } from '../../maintenance/api.js'
import { assetDraft,assetPayload,maintenanceTime,stateLabel } from '../../maintenance/helpers.js'
import MaintenanceEvidence from './MaintenanceEvidence.vue'
const props=defineProps({items:{type:Array,default:()=>[]},devices:{type:Array,default:()=>[]},deviceId:String,assetId:String})
const emit=defineEmits(['refresh','select','navigate'])
const dialog=ref(false),saving=ref(false),error=ref(''),key=ref(''),form=reactive(assetDraft()),alarms=ref([]),componentLoading=ref(false),sourceAlarm=ref('')
let generation=0,componentGeneration=0,disposed=false
const rows=computed(()=>props.items.filter(row=>!props.deviceId||row.deviceIds.includes(props.deviceId))),selectedDevices=computed(()=>deviceChoices([form.deviceId],props.devices)),components=computed(()=>[...new Map(alarms.value.filter(row=>row.componentId).map(row=>[row.componentId,row])).values()])
const deviceName=id=>props.devices.find(row=>row.id===id)?.name||id
function edit(row){Object.assign(form,assetDraft(row));if(!row){form.resourceId=createClientId();form.deviceId=props.deviceId||''}error.value='';key.value=createClientId();sourceAlarm.value='';dialog.value=true;loadComponents()}
async function loadComponents(){const token=++componentGeneration;alarms.value=[];if(!form.deviceId||!can('menu:alarms'))return;componentLoading.value=true;try{const value=await apiAll('/api/v1/alarms?'+new URLSearchParams({deviceId:form.deviceId}));if(token===componentGeneration&&!disposed)alarms.value=value.items||[]}catch(cause){if(token===componentGeneration&&!disposed)error.value=cause.message}finally{if(token===componentGeneration)componentLoading.value=false}}
function selectComponent(){const alarm=alarms.value.find(row=>row.componentId===form.componentId);if(alarm&&!form.evidence.some(ev=>ev.kind==='ALARM'&&ev.sourceId===alarm.id))form.evidence.push({kind:'ALARM',sourceId:alarm.id,deviceId:form.deviceId,description:'同设备生产周期中的稳定部件关联：'+(alarm.content||alarm.alarmType)})}
async function save(){if(saving.value)return;const token=generation;saving.value=true;error.value='';try{const value=await maintenanceWrite('assets','','',assetPayload(form,key.value));if(token!==generation||disposed)return;dialog.value=false;emit('refresh');emit('select',value)}catch(cause){if(token===generation&&!disposed)error.value=cause.status===409?'实物版本或同设备实物区间已变化，请重新核对后保存。':cause.message}finally{if(token===generation)saving.value=false}}
onBeforeUnmount(()=>{disposed=true;generation++;componentGeneration++})
</script>
<template><section class="maintenance-stack"><div class="maintenance-toolbar"><p class="maintenance-hint">实物身份与平台注册日期分开。沿用设备 ID 替换实物时，先结束旧实例，再建立新实例。</p><ui-button v-if="can('POST /api/v1/assets')" size="small" type="primary" @click="edit()"><Plus/>登记实物资产</ui-button></div><div class="maintenance-table-scroll"><ui-table :data="rows" empty-text="当前范围暂无实物资料。"><ui-table-column label="实物 / 设备" min-width="230"><template #default="{row}">{{row.body.name}}<p class="maintenance-meta">{{deviceName(row.body.deviceId)}} · {{row.body.physicalId}}<br>{{row.body.componentId?'稳定部件实例':'设备级实物'}}</p></template></ui-table-column><ui-table-column label="投运 / 有效区间" min-width="260"><template #default="{row}">实际投运 {{maintenanceTime(row.body.commissionedAt)}}<p class="maintenance-meta">{{maintenanceTime(row.body.effectiveStart)}} 至 {{row.body.effectiveEnd?maintenanceTime(row.body.effectiveEnd):'尚未明确结束'}}</p></template></ui-table-column><ui-table-column label="边界 / 人工重要性" min-width="190"><template #default="{row}">{{stateLabel(row.body.boundaryStatus)}} · 人工等级 {{row.body.importance}}<p class="maintenance-meta">固定版本 {{row.version}}</p></template></ui-table-column><ui-table-column label="操作" width="180"><template #default="{row}"><ui-button :data-maintenance-asset="row.resourceId" text size="small" @click="emit('select',row)">维修与观察</ui-button><ui-button v-if="can('POST /api/v1/assets')" text size="small" @click="edit(row)">补充新版本</ui-button></template></ui-table-column></ui-table></div></section>
<ui-dialog v-model="dialog" title="登记有依据的实物版本" width="min(930px,94vw)" :close-on-click-modal="false"><div class="maintenance-dialog-body maintenance-stack"><ui-alert v-if="error" :title="error" type="error" :closable="false"/><ui-form label-position="top" :disabled="saving"><div class="maintenance-grid"><ui-form-item label="实物名称" required><ui-input v-model="form.name" maxlength="300"/></ui-form-item><ui-form-item label="稳定实物标识" required><ui-input v-model="form.physicalId" :disabled="!!form.expectedVersion" placeholder="有依据的出厂号、铭牌或实物标识"/></ui-form-item><ui-form-item label="平台设备" required><DeviceSelect v-model="form.deviceId" :disabled="!!form.expectedVersion||!!deviceId" @change="form.componentId='';form.evidence=[];loadComponents()"/></ui-form-item><ui-form-item label="稳定部件（选填）"><ui-select v-model="form.componentId" clearable :disabled="!!form.expectedVersion" :loading="componentLoading" placeholder="无生产部件依据时保留设备级实物" @change="selectComponent"><ui-option v-for="alarm in components" :key="alarm.componentId" :value="alarm.componentId" :label="`${alarm.componentName||alarm.componentId} · ${alarm.content||alarm.alarmType}`"/></ui-select></ui-form-item><ui-form-item label="制造日期（有依据时填写）"><ui-date-time v-model="form.manufacturedAt" disable-future/></ui-form-item><ui-form-item label="实际安装日期"><ui-date-time v-model="form.installedAt" disable-future/></ui-form-item><ui-form-item label="实际投运日期"><ui-date-time v-model="form.commissionedAt" disable-future/></ui-form-item><ui-form-item label="实际退役日期"><ui-date-time v-model="form.retiredAt" disable-future/></ui-form-item><ui-form-item label="实物有效起点" required><ui-date-time v-model="form.effectiveStart"/></ui-form-item><ui-form-item label="实物有效终点（选填）"><ui-date-time v-model="form.effectiveEnd"/></ui-form-item><ui-form-item label="实物边界核实状态" required><ui-select v-model="form.boundaryStatus"><ui-option value="UNKNOWN" label="未知或未确认"/><ui-option value="CONFIRMED" label="有证据，人工已确认"/><ui-option value="DISPUTED" label="存在争议"/></ui-select></ui-form-item><ui-form-item label="人工重要性等级（0—9）" required><ui-input-number v-model="form.importance" :min="0" :max="9" :precision="0"/></ui-form-item></div><p class="maintenance-hint">未填写的制造、安装和投运日期保持未知。稳定部件只取实际生产记录的 componentId；自由文本位置不形成实物实例。</p><MaintenanceEvidence v-model="form.evidence" :devices="selectedDevices" :disabled="saving"/></ui-form></div><template #footer><ui-button :disabled="saving" @click="dialog=false">取消</ui-button><ui-button type="primary" :loading="saving" @click="save">保存实物版本</ui-button></template></ui-dialog>
</template>
