// Actual source API and browser regression in an explicitly isolated fixture.
// Configuration/analysis records and temporary scoped users are the only writes.
// Source telemetry and connection/dependency histories are preseeded by the host.
import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import WebSocket from 'ws'
import { startBrowser, delay } from '../helpers/browser.mjs'

if (process.env.IOT_TEST_MAINTENANCE_FIXTURE !== '1') throw Error('请指定隔离处置复盘验收环境：IOT_TEST_MAINTENANCE_FIXTURE=1')
if (!process.env.IOT_TEST_MAINTENANCE_INFO) throw Error('请指定 IOT_TEST_MAINTENANCE_INFO 固定来源 JSON 文件')
const info = JSON.parse(await readFile(process.env.IOT_TEST_MAINTENANCE_INFO, 'utf8')), fixture = info.response
if (!fixture?.expected?.synthetic || !fixture.deviceId || !fixture.alarmId) throw Error('fixture 须明确隔离设备、真实告警与受控来源')
const base = process.env.IOT_TEST_BASE_URL || 'http://127.0.0.1:5182', tenant = info.tenantId
const username = process.env.IOT_TEST_ADMIN_USER || 'admin', password = process.env.IOT_TEST_ADMIN_PASSWORD
if (!password) throw Error('验收登录密码未配置')
const out = resolve(process.env.IOT_TEST_OUTPUT || '.e2e/maintenance-browser'), stamp = Date.now()
await mkdir(out, { recursive: true })
let auth = null, browser = null, permissionStage = false
const failedRequests = [], coverage = [], users = []
const path = id => `/api/v1/maintenance-observations/${encodeURIComponent(id)}`
async function response(url, method = 'GET', body, token = auth?.accessToken) {
 const result = await fetch(base + url, { method, headers: { ...(token ? { Authorization: 'Bearer ' + token } : {}), ...(body ? { 'Content-Type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined })
 return { status: result.status, data: await result.json().catch(() => ({})) }
}
async function request(url, method = 'GET', body, token = auth?.accessToken) {
 const result = await response(url, method, body, token)
 if (result.status >= 400) throw Error(`${method} ${url}: ${result.status} ${result.data.detail || result.data.message || ''}`)
 return result.data
}
const login = (user, secret) => request('/api/v1/auth/login', 'POST', { tenantId: tenant, username: user, password: secret }, '')
const all = async (url, token = auth.accessToken) => {
 const rows = []
 for (let offset = 0; ; offset += 100) {
  const page = await request(url + (url.includes('?') ? '&' : '?') + `limit=100&offset=${offset}`, 'GET', undefined, token)
  rows.push(...(page.items || []))
  if (!page.items?.length || rows.length >= page.total || page.items.length < 100) return rows
 }
}
try {
 auth=await login(username,password)
 const d1=fixture.deviceId,device=(await request('/api/v1/device-registry/'+d1+'/connection')).device,name=device.name||d1
 const alarmsBefore=await request('/api/v1/alarms'),rulesBefore=await request('/api/v1/rules')
 browser=await startBrowser({webSocketImplementation:WebSocket,timeout:30000,interval:150,onEvent:event=>{if(event.method==='Network.responseReceived'){const url=new URL(event.params.response.url);if(!permissionStage&&/\/api\/v1\/(assets|maintenance-|investment-)/.test(url.pathname)&&event.params.response.status>=400)failedRequests.push({path:url.pathname,status:event.params.response.status})}}})
 const { call, evaluate, until } = browser
 await call('Page.enable'); await call('Runtime.enable'); await call('Network.enable')
 await call('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: out })
 const viewport = (width = 1440, height = 1050) => call('Emulation.setDeviceMetricsOverride', { width, height, deviceScaleFactor: 1, mobile: width < 640 })
 await viewport(); await call('Page.navigate', { url: base }); await until(() => evaluate('!!document.querySelector(".login-form")'))
 const setSession = async (identity, user) => {
  await evaluate(`(()=>{const values=${JSON.stringify({ iot_token: identity.accessToken, iot_tenant: tenant, iot_user: user, iot_role: identity.role || 'operator', iot_permissions: JSON.stringify(identity.permissions || []), iot_access_version: identity.accessVersion || '' })};for(const [key,value] of Object.entries(values))localStorage.setItem(key,value)})()`)
  await call('Page.reload')
 }
 const click = text => until(() => evaluate(`(()=>{const node=[...document.querySelectorAll('button')].find(row=>row.getClientRects().length&&!row.disabled&&row.textContent.trim()===${JSON.stringify(text)});node?.click();return !!node})()`), 'button ' + text)
 const clickSelector = selector => until(() => evaluate(`(()=>{const node=document.querySelector(${JSON.stringify(selector)});if(!node?.getClientRects().length)return false;node.click();return true})()`), selector)
 const tab = async text => { await until(() => evaluate(`(()=>{const node=[...document.querySelectorAll('.n-tabs-tab')].find(row=>row.getClientRects().length&&row.textContent.trim()===${JSON.stringify(text)});node?.click();return !!node})()`), 'tab ' + text); await delay(150) }
 const fill = async (label, value, index = 0, itemIndex = 0) => evaluate(`(()=>{const dialog=[...document.querySelectorAll('.ui-dialog')].filter(node=>node.getClientRects().length).at(-1);const item=[...dialog.querySelectorAll('.ui-form-item')].filter(node=>node.querySelector('label')?.textContent.trim().startsWith(${JSON.stringify(label)}))[${itemIndex}];const field=item?.querySelectorAll('input,textarea')[${index}];if(!field)throw Error('字段不存在：'+${JSON.stringify(label)});field.focus();field.value=${JSON.stringify(String(value))};field.dispatchEvent(new Event('input',{bubbles:true}));field.dispatchEvent(new Event('change',{bubbles:true}));field.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true}));field.blur()})()`)
 const date = async (label, at, index = 0) => fill(label, await evaluate(`(()=>{const d=new Date(${at}),p=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())+' '+p(d.getHours())+':'+p(d.getMinutes())+':'+p(d.getSeconds())})()`), index)
 const range = async (label,start,end) => {for(const [index,at] of [start,end].entries()){const value=await evaluate(`(()=>{const d=new Date(${at}),p=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())+' '+p(d.getHours())+':'+p(d.getMinutes())+':'+p(d.getSeconds())})()`);await evaluate(`(()=>{const dialog=[...document.querySelectorAll('.ui-dialog')].filter(n=>n.getClientRects().length).at(-1),item=[...dialog.querySelectorAll('.ui-form-item')].find(n=>n.querySelector('label')?.textContent.trim().startsWith(${JSON.stringify(label)})),field=item.querySelectorAll('input')[${index}];field.value=${JSON.stringify(value)};field.dispatchEvent(new Event('input',{bubbles:true}))})()`);await delay(100)}}
 const select = async (label, text, extra = '', itemIndex = 0) => {
  await evaluate(`(()=>{const dialog=[...document.querySelectorAll('.ui-dialog')].filter(n=>n.getClientRects().length).at(-1),item=[...dialog.querySelectorAll('.ui-form-item')].filter(n=>n.querySelector('label')?.textContent.trim().startsWith(${JSON.stringify(label)}))[${itemIndex}],control=item?.querySelector('.n-base-selection');if(!control)throw Error('选择器不存在：'+${JSON.stringify(label)});control.scrollIntoView({block:'center'});control.click()})()`)
  await delay(300)
  await until(()=>evaluate(`(()=>{const option=[...document.querySelectorAll('.n-base-select-option')].find(node=>{const r=node.getBoundingClientRect(),hit=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return node.checkVisibility({checkOpacity:true,checkVisibilityCSS:true})&&node.textContent.includes(${JSON.stringify(text)})&&node.textContent.includes(${JSON.stringify(extra)})&&(hit===node||node.contains(hit))});option?.click();return !!option})()`),'option '+text)
  await delay(300)
  await evaluate(`(()=>{const header=[...document.querySelectorAll('.ui-dialog')].filter(n=>n.getClientRects().length).at(-1).querySelector('.n-card-header');header.dispatchEvent(new MouseEvent('mousedown',{bubbles:true}));header.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));header.click()})()`)
  await delay(250);await until(()=>evaluate(`(()=>{const dialog=[...document.querySelectorAll('.ui-dialog')].filter(n=>n.getClientRects().length).at(-1),item=[...dialog.querySelectorAll('.ui-form-item')].filter(n=>n.querySelector('label')?.textContent.trim().startsWith(${JSON.stringify(label)}))[${itemIndex}];return item.querySelector('.n-base-selection').textContent.includes(${JSON.stringify(text)})})()`),'selected actual value '+label)
 }
 const closed = () => until(() => evaluate(`![...document.querySelectorAll('.ui-dialog')].some(node=>node.getClientRects().length)`), 'dialog closed')
 const visibleDialogText = () => evaluate(`([...document.querySelectorAll('.ui-dialog')].filter(node=>node.getClientRects().length).at(-1)?.innerText || '')`)
 const screenshot = async file => writeFile(`${out}/${file}.png`, Buffer.from((await call('Page.captureScreenshot', { format: 'png' })).data, 'base64'))
 const openPage=async()=>{await clickSelector('.nav-item[aria-label="设备维护"]');await until(()=>evaluate('!!document.querySelector(".maintenance-page")&&!document.querySelector(".maintenance-page>.ui-skeleton")'));await delay(200)}
 const check=async(text,value=true)=>evaluate(`(()=>{const dialog=[...document.querySelectorAll('.ui-dialog')].filter(n=>n.getClientRects().length).at(-1),row=[...dialog.querySelectorAll('.n-checkbox')].find(n=>n.textContent.includes(${JSON.stringify(text)}));if(!row)throw Error('checkbox missing');if(row.classList.contains('n-checkbox--checked')!==${value})row.click()})()`)
 const textarea=async(label,value)=>fill(label,value)
 const addEvidence=async(description)=>{await click('增加实际依据');await fill('实际核实内容或资料说明',description)}
 const terminal=(resource,id)=>until(async()=>{const v=await request(`/api/v1/${resource}/${id}`);return ['SUCCEEDED','PARTIAL','FAILED','CANCELLED'].includes(v.status)?v:false},'real persistent computation',60000)
 const text=()=>evaluate('document.querySelector(".maintenance-page")?.innerText||""')
 const fillOutside=async(label,value)=>evaluate(`(()=>{const item=[...document.querySelectorAll('.maintenance-page .ui-form-item')].find(n=>n.querySelector('label')?.textContent.trim().startsWith(${JSON.stringify(label)})),field=item?.querySelector('textarea,input');if(!field)throw Error('outside field missing');field.value=${JSON.stringify(String(value))};field.dispatchEvent(new Event('input',{bubbles:true}));field.dispatchEvent(new Event('change',{bubbles:true}))})()`)
 const sourceStart=info.start,sourceEnd=info.end,repairStart=sourceStart+15000,repairEnd=sourceStart+20000,newAssetName='有依据的隔离实物 '+stamp,workName='实际维修验收 '+stamp,scenarioName='透明投入试算 '+stamp
 let asset=(await all('/api/v1/assets')).find(a=>a.body.name.startsWith('有依据的隔离实物 ')&&a.body.effectiveStart===sourceStart-5000),assetName=asset?.body.name||newAssetName
 await setSession(auth,username);await openPage();console.log('维护验收：实物实际日期、固定维修记录及独立功能验收')
 if(!asset){await click('登记实物资产');await fill('实物名称',assetName);await fill('稳定实物标识','plate-'+stamp);await select('平台设备',name);await date('实物有效起点',sourceStart-5000);await select('实物边界核实状态','有证据');await fill('人工重要性等级',5);await addEvidence('隔离实物铭牌现场核对 '+stamp);await click('保存实物版本');await closed()}else await clickSelector(`[data-maintenance-asset="${asset.resourceId}"]`)
 asset=await until(async()=>(await all('/api/v1/assets')).find(a=>a.body.name===assetName),'actual physical instance saved');assert.equal(asset.body.boundaryStatus,'CONFIRMED');assert.ok(!asset.body.commissionedAt);assert.ok(!asset.body.manufacturedAt);assert.equal(asset.body.importance,5);assert.ok(asset.body.evidence[0].recordedAt>0);assert.ok(!asset.body.evidence[0].sourceId.includes('spoof'))
 await click('建立维修记录');await fill('工作名称',workName);await select('固定实物版本',assetName);await fill('实际原因','现场核对端子松动，隔离验收');await fill('已采取或计划动作','现场检查\n紧固端子');await fill('实际参与人员','外部维修人员张某');await fill('实际配件','端子1个');await click('保存实际记录');await closed();let work=await until(async()=>(await all('/api/v1/maintenance-records')).find(w=>w.body.name===workName),'work draft saved');assert.equal(work.body.status,'DRAFT');assert.deepEqual(work.body.people,['外部维修人员张某']);await click('编辑草稿');await fill('实际原因','现场端子松动已核对 '+stamp);await click('保存实际记录');await closed();work=await request('/api/v1/maintenance-records/'+work.resourceId);assert.ok(work.body.reason.includes(String(stamp)))
 await click('开始工作');await date('实际操作时间',repairStart);await fill('操作依据','实际维修开始补登记');await click('保存实际记录');await closed();await click('结束工作');await date('实际操作时间',repairEnd);await fill('操作依据','实际维修工作结束，功能另验收');await click('保存实际记录');await closed();work=await request('/api/v1/maintenance-records/'+work.resourceId);assert.equal(work.body.status,'COMPLETED');assert.equal(work.body.startedAt,repairStart);assert.equal(work.body.endedAt,repairEnd);assert.equal(work.body.history[0].occurredAt,repairStart);assert.ok(work.body.history[0].recordedAt>repairEnd);assert.equal(work.body.verifications?.length||0,0)
 await click('登记功能验收');await fill('规定功能验收项','端子回访\n恢复输入');await select('功能验收结果','功能验收失败');await fill('实际核验结论与依据','恢复输入未通过，需要进一步维修');await addEvidence('回访测试未通过记录 '+stamp);const attachmentFile=resolve(out,'maintenance-fixture.txt');await writeFile(attachmentFile,'隔离维护资料 '+stamp);const document=await call('DOM.getDocument'),input=await call('DOM.querySelector',{nodeId:document.root.nodeId,selector:'.ui-dialog input[type="file"]'});await call('DOM.setFileInputFiles',{nodeId:input.nodeId,files:[attachmentFile]});await until(()=>evaluate(`[...document.querySelectorAll('.ui-dialog textarea,input')].some(n=>n.getClientRects().length&&n.value.includes('maintenance-fixture.txt'))`),'actual maintenance attachment');await click('登记独立验收');await closed();work=await request('/api/v1/maintenance-records/'+work.resourceId);assert.equal(work.body.status,'COMPLETED');assert.equal(work.body.verifications.at(-1).result,'FAILED');assert.equal(work.body.verifications.at(-1).verifier,username);const attachmentId=work.body.verifications.at(-1).evidence.find(e=>e.kind==='ATTACHMENT').sourceId;assert.equal((await response('/api/v1/maintenance-attachments/'+attachmentId)).status,200)
 coverage.push('实际实物日期未知，结构化草稿编辑与双时钟工作操作、独立失败验收及真实附件，COMPLETED不代替功能验收')
 console.log('维护验收：重叠工况排除并集、固定观察及手算分母')
 await tab('工况与准入')
 const addContext=async(kind,start,end,reason)=>{await click('登记工况记录');await select('明确设备范围',name);await select('工况类型',kind);await range('实际工况区间',start,end);if(kind==='运行强度')await fill('实际运行强度与口径','受控恒定工况');await fill('工况依据',reason);await check('根据关联证据确认',true);await addEvidence('实际工况现场记录 '+stamp);await click('保存有依据版本');await closed();return(await all('/api/v1/maintenance-contexts')).find(c=>c.body.reason===reason)}
 const stop=await addContext('有依据的计划停运',sourceStart+2000,sourceStart+5000,'隔离停运 '+stamp),testContext=await addContext('已确认测试',sourceStart+4000,sourceStart+6000,'隔离测试 '+stamp),intensity=await addContext('运行强度',sourceStart,sourceEnd,'同口径强度 '+stamp)
 await tab('维修与验收');await clickSelector(`[data-maintenance-record="${work.resourceId}"]`);await click('建立变化观察');await until(async()=>(await visibleDialogText()).includes('维修前观察窗口'),'async observation dialog');await range('维修前观察窗口',sourceStart,repairStart);await range('维修后观察窗口',repairEnd,sourceEnd);await select('固定工况版本',stop.body.reason);await select('固定工况版本',testContext.body.reason);await select('固定工况版本','受控恒定工况');await click('开始固定变化计算');await closed();let observation=await until(async()=>(await all(`/api/v1/maintenance-records/${work.resourceId}/observations`))[0],'observation persisted');observation=await terminal('maintenance-observations',observation.id);assert.ok(['SUCCEEDED','PARTIAL'].includes(observation.status),observation.error);await until(()=>evaluate('!!document.querySelector("[data-maintenance-side=before]")'),'observation rendered')
 const snapshot=await request(path(observation.id)+'/snapshot'),metrics=snapshot.statistics;assert.equal(metrics.before.windowMs,15000);assert.equal(metrics.before.excludedMs,4000);assert.equal(metrics.before.effectiveMs,11000);assert.equal(metrics.after.effectiveMs,20000);assert.equal(metrics.verification,'FAILED');assert.ok(['INSUFFICIENT','CONFOUNDED'].includes(metrics.status));assert.ok((await text()).includes('未知，不使用平台注册日期'));assert.ok((await text()).includes('未知或口径不同')||(await text()).includes('有同口径依据'));assert.ok((await text()).includes('排除并集'));assert.equal(metrics.parameters.beforeAssetRevisionId,asset.id);assert.equal(metrics.parameters.afterAssetRevisionId,asset.id);assert.ok(!metrics.parameters.admission)
 await fillOutside('人工核实依据','已核对重叠排除并集及未知故障来源，继续观察 '+stamp);await click('保存独立人工核实');await until(async()=>(await all(path(observation.id)+'/reviews')).length>0);assert.deepEqual((await request(path(observation.id)+'/snapshot')).statistics,metrics)
 await click('开始解读');let jobs=await until(async()=>(await all(path(observation.id)+'/ai-jobs')).length>0,'explicit AI starts');jobs=await until(async()=>{const j=await all(path(observation.id)+'/ai-jobs');return j[0]&&['SUCCEEDED','FAILED','CANCELLED'].includes(j[0].status)?j:false},'AI terminal factual business retained',120000);assert.ok(['SUCCEEDED','FAILED'].includes(jobs[0].status));assert.ok((await text()).includes('固定前后变化观察'));await click('下载固定报告');await until(async()=>{try{return JSON.parse(await readFile(resolve(out,`维护与投入_${observation.id}.json`),'utf8'))}catch{return false}},'real fixed download');await call('Page.reload');await openPage();await until(()=>evaluate('!!document.querySelector("[data-maintenance-side=before]")'));assert.ok((await text()).includes(snapshot.factsHash));coverage.push('重叠排除手算15秒减并集4秒=11秒、后20秒，固定实物/人工核实不改指标、显式AI与下载、刷新精确恢复')
 console.log('维护验收：精确费用、缺失报价、透明顺序与人工决定')
 await tab('工况与准入');await evaluate(`(()=>{const control=document.querySelector('.maintenance-page .maintenance-toolbar .n-base-selection');control.click()})()`);await until(()=>evaluate(`(()=>{const o=[...document.querySelectorAll('.n-base-select-option')].find(n=>n.checkVisibility()&&n.textContent.includes('支出与未来报价'));o?.click();return !!o})()`));await click('登记支出与未来报价');await select('具体来源',assetName);await fill('材料金额','0.100001');await fill('人工金额','0.200002');await date('发生或报价日期',sourceEnd);await range('同口径规划范围',sourceEnd,sourceEnd+3600000);await fill('费用依据','真实隔离报价未知外部服务 '+stamp);await click('保存有依据版本');await closed();let quote=(await all('/api/v1/maintenance-costs')).find(c=>c.body.basis.includes(String(stamp)));assert.equal(quote.body.material,'0.100001');assert.equal(quote.body.labor,'0.200002');assert.ok(!('externalService'in quote.body));assert.equal(quote.body.type,'ESTIMATE')
 await tab('投入方案');await click('建立投入方案');await fill('方案名称',scenarioName);await range('同口径规划期',sourceEnd,sourceEnd+3600000);await check('此方案与全部派生结果',true);await fill('实际预算','0.250000');await select('固定实物版本',assetName);await fill('人工必需层',1);await fill('人工必需分层依据','单位确认当前必要检查');await select('固定变化观察来源','固定变化观察');await select('已核实功能缺陷来源',workName);await select('同币种同规划期未来报价','真实隔离报价未知外部服务');await fill('实际执行条件与约束','外部服务报价未知，不按零费用');await click('保存方案版本');await closed();let scenario=(await all('/api/v1/investment-scenarios')).find(s=>s.body.name===scenarioName);assert.equal(scenario.body.useFinance,true);assert.equal(scenario.body.budget,'0.250000');assert.equal(scenario.body.candidates[0].unresolvedVerifiedDefect,true);await clickSelector(`[data-maintenance-scenario="${scenario.resourceId}"]`);await click('计算固定排序');let investment=await until(async()=>(await all(`/api/v1/investment-scenarios/${scenario.resourceId}/evaluations`))[0],'investment task');investment=await terminal('investment-evaluations',investment.id);assert.ok(['SUCCEEDED','PARTIAL'].includes(investment.status),investment.error);await until(()=>evaluate('document.querySelector(".maintenance-page")?.innerText.includes("分层优先理由与预算试算")'));const priorities=await all(`/api/v1/investment-evaluations/${investment.id}/investment-priorities`);assert.equal(priorities[0].body.budgetStatus,'QUOTE_MISSING_OR_INCOMPARABLE');assert.equal(priorities[0].body.status,'AWAITING_INFORMATION');assert.ok((await text()).includes('未知'))
 await click('开始解读');const investmentAIPath=`/api/v1/investment-scenarios/${scenario.resourceId}/ai-jobs?runId=${investment.id}`;await until(async()=>(await all(investmentAIPath)).length>0,'explicit fixed investment AI');const investmentJobs=await until(async()=>{const j=await all(investmentAIPath);return j[0]&&['SUCCEEDED','FAILED','CANCELLED'].includes(j[0].status)?j:false},'investment AI terminal',120000);assert.ok(['SUCCEEDED','FAILED'].includes(investmentJobs[0].status));if(process.env.IOT_TEST_EXPECT_AI_FAILURE==='1'){assert.equal(jobs[0].status,'FAILED');assert.equal(investmentJobs[0].status,'FAILED')}
 await click('保存人工完整顺序');await fill('人工操作依据','已核对唯一必要项优先，缺失报价继续保留未知');await click('保存方案版本');await closed();scenario=await request('/api/v1/investment-scenarios/'+scenario.resourceId);assert.equal(scenario.body.adjustments.length,1);await click('计算固定排序');investment=await until(async()=>(await all(`/api/v1/investment-scenarios/${scenario.resourceId}/evaluations`)).find(r=>r.parameters.scenarioRevisionId===scenario.id),'adjusted fixed task');investment=await terminal('investment-evaluations',investment.id);await until(()=>evaluate('document.querySelector(".maintenance-page")?.innerText.includes("分层优先理由与预算试算")'));await click('依据此固定排序记录决定');await check(assetName,true);await fill('人工操作依据','先安排检查，外部报价未确认不执行采购 '+stamp);await click('保存人工决定');await closed();scenario=await request('/api/v1/investment-scenarios/'+scenario.resourceId);assert.equal(scenario.body.status,'DECIDED');assert.equal(scenario.body.decisions[0].evaluationRunId,investment.id);assert.ok(scenario.body.decisions[0].factsHash);assert.deepEqual(await request('/api/v1/alarms'),alarmsBefore);assert.deepEqual(await request('/api/v1/rules'),rulesBefore);coverage.push('精确费用未知不填零，资金方案缺失报价和同层待补区、完整人工顺序重算、绑定固定事实决定不采购')
 console.log('维护验收：功能通过仍保留原失败事实，实际值班跟进独立')
 await tab('维修与验收');await clickSelector(`[data-maintenance-record="${work.resourceId}"]`);await click('登记功能验收');await fill('规定功能验收项','端子回访\n恢复输入');await check('端子回访',true);await check('恢复输入',true);await select('功能验收结果','功能验收通过');await fill('实际核验结论与依据','逐项现场复核通过，原观察仍保留失败事实');await addEvidence('独立通过验收现场记录 '+stamp);await click('登记独立验收');await closed();work=await request('/api/v1/maintenance-records/'+work.resourceId);assert.equal(work.body.verifications.length,2);assert.equal(work.body.status,'COMPLETED');assert.equal(work.body.verifications.at(-1).result,'PASSED');assert.equal((await request(path(observation.id)+'/snapshot')).statistics.verification,'FAILED');await click('关联值班事项');await until(async()=>(await visibleDialogText()).includes('实际进行中值班'));await select('实际进行中值班','管理员');await select('当班负责人','管理员');await fill('下一步与验收要求','本班核对验收，事项由有权限人员独立确认');await click('保存实际记录');await closed();assert.ok((await all(`/api/v1/maintenance-records/${work.resourceId}/duty-links`)).length>0);assert.equal((await request('/api/v1/maintenance-records/'+work.resourceId)).body.status,'COMPLETED');coverage.push('功能由FAILED到逐项PASSED独立登记，旧观察仍保留FAILED；真实ACTIVE值班事项关联不由维修自动完成')
 console.log('维护验收：资金权限撤销、设备范围及联合窄屏导航')
 permissionStage=true;const scopedUser='maintenance-scope-'+stamp,secret=randomUUID()+'Aa1!',basePermissions=['menu:devices','menu:maintenance'];await request('/api/v1/access/users','POST',{username:scopedUser,displayName:'维护受限账号',password:secret,enabled:true,roleIds:[],permissions:[...basePermissions,'GET /api/v1/maintenance-costs'],deviceScope:'selected',deviceIds:[d1]});users.push(scopedUser);let identity=await login(scopedUser,secret);assert.equal((await response('/api/v1/investment-evaluations/'+investment.id,'GET',undefined,identity.accessToken)).status,200);await request('/api/v1/access/users/'+scopedUser,'PUT',{displayName:'资金撤权账号',enabled:true,roleIds:[],permissions:basePermissions,deviceScope:'selected',deviceIds:[d1]});identity=await login(scopedUser,secret);for(const p of ['/api/v1/investment-scenarios/'+scenario.resourceId,'/api/v1/investment-evaluations/'+investment.id,'/api/v1/investment-evaluations/'+investment.id+'/snapshot'])assert.equal((await response(p,'GET',undefined,identity.accessToken)).status,403,p);assert.equal((await response(path(observation.id),'GET',undefined,identity.accessToken)).status,200);await setSession(identity,scopedUser);await openPage();assert.ok(!(await text()).includes(scenarioName));assert.ok(!await evaluate(`[...document.querySelectorAll('.maintenance-page button')].some(n=>n.textContent==='建立投入方案')`));assert.equal((await response('/api/v1/assets','POST',{},identity.accessToken)).status,403);await request('/api/v1/access/users/'+scopedUser,'PUT',{displayName:'范围撤权账号',enabled:true,roleIds:[],permissions:basePermissions,deviceScope:'none',deviceIds:[]});identity=await login(scopedUser,secret);assert.equal((await response(path(observation.id),'GET',undefined,identity.accessToken)).status,403);assert.equal((await response('/api/v1/maintenance-attachments/'+attachmentId,'GET',undefined,identity.accessToken)).status,403);await setSession(identity,scopedUser);await openPage();assert.ok(!await evaluate('!!document.querySelector("[data-maintenance-side=before]")'));coverage.push('资金撤权整件历史方案/任务/快照403，非资金事实可读，无操作权限403；设备撤权旧观察附件403且前端清除')
 await setSession(auth,username);await openPage();await viewport(390,844);for(const label of ['实物资产','维修与验收','变化观察','投入方案','工况与准入']){await tab(label);await delay(200);assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth+2'),label+' 390 no page overflow');await screenshot(label+'-390')}await tab('实物资产');await click('登记实物资产');await delay(250);assert.ok(await evaluate(`(()=>{const dialog=[...document.querySelectorAll('.ui-dialog')].filter(n=>n.getClientRects().length).at(-1),body=dialog.querySelector('.maintenance-dialog-body');body.scrollTop=body.scrollHeight;return dialog.getBoundingClientRect().right<=innerWidth+2&&body.scrollTop>0})()`),'independently scrolling long asset dialog');await screenshot('asset-dialog-390');await click('取消');await closed();await viewport();coverage.push('390px五页表格独立横向滚动、完整实物弹窗独立滚动')
 await viewport(390,844);for(const [label,selector] of [['上报数据检查','.data-quality-page'],['上报中断分析','.monitoring-gaps-page'],['告警规则','.rule-lab-page'],['演练与复盘','.response-review-page'],['设备维护','.maintenance-page']]){await clickSelector('button[aria-label="打开菜单"]');await delay(180);await clickSelector(`.nav-item[aria-label="${label}"]`);await delay(250);if(label==='告警规则')await tab('告警规则对比');await until(()=>evaluate(`!!document.querySelector(${JSON.stringify(selector)})`),'joint actual page '+label);await click('刷新');await delay(180);assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth+2'));await screenshot('joint-'+label)}coverage.push('390px五个实际应用入口展开菜单导航、具体页面与刷新，无运行时错误')
 assert.equal(browser.errors.length,0,'no runtime errors');await writeFile(resolve(out,'report.json'),JSON.stringify({passed:true,coverage,assetId:asset.resourceId,workId:work.resourceId,observationId:observation.id,scenarioId:scenario.resourceId,investmentId:investment.id,screenshots:out},null,2));console.log(JSON.stringify({passed:true,coverage,screenshots:out}))
}catch(error){if(browser)try{console.error(await browser.evaluate('document.body.innerText.slice(-10000)'));console.error(JSON.stringify(failedRequests));await Promise.race([writeFile(resolve(out,'failure.png'),Buffer.from((await browser.call('Page.captureScreenshot',{format:'png'})).data,'base64')),delay(5000)])}catch(diagnostic){console.error(diagnostic.message)}throw error}finally{await browser?.close();for(const user of users)try{await request('/api/v1/access/users/'+encodeURIComponent(user),'DELETE')}catch(error){console.error('临时账号清理失败 '+user+' '+error.message)}}
