// Real Chromium + built Vue assets + isolated Go API. No browser packages needed.
import { spawn } from 'node:child_process'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import assert from 'node:assert/strict'
const profile = await mkdtemp(join(tmpdir(), 'iot-onboard-browser-'))
const child = spawn(process.env.IOT_TEST_BROWSER, ['--headless=new','--no-first-run','--no-default-browser-check','--disable-gpu','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'], { windowsHide:true, stdio:'ignore' })
let socket
const delay = ms => new Promise(resolve=>setTimeout(resolve,ms))
async function until(fn){for(let i=0;i<100;i++){const value=await fn();if(value)return value;await delay(100)}throw new Error('Browser condition timed out')}
try {
  const port = await until(async()=>{try{return (await readFile(join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0]}catch{return null}})
  const pages=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json()
  socket=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl)
  await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject})
  let id=0;const pending=new Map()
  socket.onmessage=event=>{const value=JSON.parse(event.data);if(value.id){const entry=pending.get(value.id);pending.delete(value.id);value.error?entry.reject(new Error(value.error.message)):entry.resolve(value.result)}}
  const call=(method,params={})=>new Promise((resolve,reject)=>{const next=++id;pending.set(next,{resolve,reject});socket.send(JSON.stringify({id:next,method,params}))})
  const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text+' '+JSON.stringify(r.exceptionDetails.exception));return r.result.value}
  await call('Page.enable')
  await call('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.setItem('iot_token',${JSON.stringify(process.env.IOT_TEST_TOKEN)});localStorage.setItem('iot_tenant','tenant');localStorage.setItem('iot_role','admin');localStorage.setItem('iot_user','browser-test');`})
  await call('Page.navigate',{url:process.env.IOT_TEST_ORIGIN})
  const click=async text=>until(()=>evaluate(`(()=>{const e=[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===${JSON.stringify(text)}&&e.getClientRects().length&&!e.disabled);if(!e)return false;e.click();return true})()`))
  const fill=async(label,value)=>evaluate(`(()=>{const item=[...document.querySelectorAll('.el-form-item')].find(e=>e.querySelector('label')?.textContent.trim()===${JSON.stringify(label)});const input=item?.querySelector('input');if(!input)throw new Error('missing input '+${JSON.stringify(label)});input.value=${JSON.stringify(value)};input.dispatchEvent(new Event('input',{bubbles:true}))})()`)
  await click('设备管理')
  await click('添加设备')
  await until(()=>evaluate(`(()=>{const e=document.querySelector('.el-dialog .el-switch');if(!e)return false;e.click();return true})()`))
  await fill('新产品名称','浏览器测试产品')
  await click('下一步')
  await evaluate(`([...document.querySelectorAll('.el-radio')].find(e=>e.textContent.includes('TCP 设备'))).click()`)
  await click('下一步')
  await evaluate(`document.querySelector('.el-dialog .el-switch').click()`)
  await click('管理节点')
  await fill('节点标识','browser-edge');await fill('名称','浏览器现场节点')
  await click('保存登记')
  await until(()=>evaluate(`([...document.querySelectorAll('.el-dialog')].find(e=>e.textContent.includes('Edge 节点登记')))?.querySelector('.el-table')?.textContent.includes('browser-edge')`))
  await evaluate(`([...document.querySelectorAll('.el-dialog')].find(e=>e.textContent.includes('Edge 节点登记'))).querySelector('.el-dialog__headerbtn').click()`)
  await click('上一步')
  await evaluate(`([...document.querySelectorAll('.el-radio')].find(e=>e.textContent.includes('HTTP 标准上报'))).click()`)
  await click('下一步')
  await fill('设备名称','浏览器传感器');await fill('设备标识','browser-device')
  await evaluate(`([...document.querySelectorAll('.el-form-item')].find(e=>e.querySelector('label')?.textContent.trim()==='上报类型')).querySelector('.el-select__wrapper').click()`)
  await until(()=>evaluate(`(()=>{const e=[...document.querySelectorAll('.el-select-dropdown__item')].find(e=>e.textContent.trim()==='状态'&&e.getClientRects().length);if(!e)return false;e.click();return true})()`))
  await click('上一步')
  await evaluate(`([...document.querySelectorAll('.el-radio')].find(e=>e.textContent.includes('MQTT 标准设备'))).click()`)
  await click('下一步')
  assert.ok(await evaluate(`document.querySelector('.el-dialog textarea').value.includes('CONNECTED')`))
  await click('上一步')
  await evaluate(`([...document.querySelectorAll('.el-radio')].find(e=>e.textContent.includes('HTTP 标准上报'))).click()`)
  await click('下一步')
  await click('下一步');await click('运行接入测试')
  await until(()=>evaluate(`document.querySelector('.el-dialog')?.textContent.includes('SUCCESS')`))
  await click('下一步')
  assert.ok(await evaluate(`document.querySelector('.el-dialog').textContent.includes('iot_standard_parser')`))
  await click('完成并启用')
  await until(()=>evaluate(`document.querySelector('.el-dialog')?.textContent.includes('设备已创建并启用')`))
  assert.ok(await evaluate(`document.querySelector('.el-dialog').textContent.includes('/iot/up/tenant/')`))
  await click('关闭');await click('连接详情')
  await until(()=>evaluate(`document.querySelector('.el-drawer')?.textContent.includes('iot-standard')`))
  assert.ok(await evaluate(`document.querySelector('.el-drawer').textContent.includes('连接与状态历史')`))
  assert.ok(await evaluate(`document.querySelector('.el-drawer').textContent.includes('最近事件')`))
  assert.ok(await evaluate(`document.querySelector('.el-drawer').textContent.includes('最近告警')`))
  await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true})
  await evaluate('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))')
  await until(()=>evaluate(`document.querySelector('.el-drawer').getBoundingClientRect().width<=391`))
  console.log('PASS: real browser onboarding, Edge node registration, new product, test, preview, enable, connection history, mobile drawer')
} finally {
  if(socket)socket.close()
  child.kill()
  await new Promise(resolve=>{if(child.exitCode!==null)resolve();else child.once('exit',resolve)})
  await rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100})
}
