// Real Chromium + built Vue assets + isolated Go API. No browser packages needed.
import { spawn } from 'node:child_process'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import assert from 'node:assert/strict'
const profile = await mkdtemp(join(tmpdir(), 'iot-onboard-browser-'))
const child = spawn(process.env.IOT_TEST_BROWSER, ['--headless=new','--no-first-run','--no-default-browser-check','--disable-gpu','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'], { windowsHide:true, stdio:'ignore' })
let socket
const delay = ms => new Promise(resolve=>setTimeout(resolve,ms))
async function until(fn){for(let i=0;i<100;i++){const value=await fn();if(value)return value;await delay(100)}throw new Error('Browser condition timed out')}
try {
  const port = await until(async()=>{try{return (await readFile(join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0]}catch{return null}})
  const pages=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json()
  socket=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl)
  await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject})
  let id=0;const pending=new Map()
  let blockDeviceToken = false, blockedTokenRequests = 0
  socket.onmessage=event=>{const value=JSON.parse(event.data);if(value.id){const entry=pending.get(value.id);pending.delete(value.id);value.error?entry.reject(new Error(value.error.message)):entry.resolve(value.result)}else if(value.method==='Fetch.requestPaused'){
    if(blockDeviceToken){blockedTokenRequests++;call('Fetch.failRequest',{requestId:value.params.requestId,errorReason:'InternetDisconnected'}).catch(()=>{})}
    else call('Fetch.continueRequest',{requestId:value.params.requestId}).catch(()=>{})
  }}
  const call=(method,params={})=>new Promise((resolve,reject)=>{const next=++id;pending.set(next,{resolve,reject});socket.send(JSON.stringify({id:next,method,params}))})
  const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text+' '+JSON.stringify(r.exceptionDetails.exception));return r.result.value}
  await call('Page.enable')
  await call('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.setItem('iot_token',${JSON.stringify(process.env.IOT_TEST_TOKEN)});localStorage.setItem('iot_tenant','tenant');localStorage.setItem('iot_role','admin');localStorage.setItem('iot_user','browser-test');`})
  await call('Page.navigate',{url:process.env.IOT_TEST_ORIGIN})
  const click=async text=>until(()=>evaluate(`(()=>{const e=[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===${JSON.stringify(text)}&&e.getClientRects().length&&!e.disabled);if(!e)return false;e.click();return true})()`))
  const fill=async(label,value)=>evaluate(`(()=>{const item=[...document.querySelectorAll('.el-form-item')].find(e=>e.querySelector('label')?.textContent.trim()===${JSON.stringify(label)});const input=item?.querySelector('input');if(!input)throw new Error('missing input '+${JSON.stringify(label)});input.value=${JSON.stringify(value)};input.dispatchEvent(new Event('input',{bubbles:true}))})()`)
  await click('设备管理')
  await click('添加设备')
  await until(()=>evaluate(`(()=>{const e=document.querySelector('.el-dialog .el-switch');if(!e)return false;e.click();return true})()`))
  await fill('新产品名称','浏览器测试产品')
  await click('下一步')
  await evaluate(`([...document.querySelectorAll('.el-radio')].find(e=>e.textContent.trim()==='Modbus TCP')).click()`)
  await click('下一步')
  assert.ok(await evaluate(`[...document.querySelectorAll('.el-dialog button')].find(e=>e.textContent.trim()==='下一步').disabled`))
  await fill('设备名称','Modbus 预览');await fill('设备标识','browser-modbus-preview')
  await fill('设备地址 / 主机名','127.0.0.1')
  await fill('端口',process.env.IOT_TEST_MODBUS_PORT)
  // Input-number commits on change/blur, matching a real field edit.
  await evaluate(`document.querySelectorAll('.el-input-number input').forEach(e=>{e.dispatchEvent(new Event('change',{bubbles:true}));e.blur()})`)
  await fill('单位','温度,"摄氏"')
  await click('下一步');await click('运行接入测试')
  await until(()=>evaluate(`document.querySelector('.el-dialog')?.textContent.includes('SUCCESS')`))
  await click('下一步')
  assert.ok(await evaluate(`document.querySelector('.el-dialog').textContent.includes('目标设备/模拟器读取') && document.querySelector('.el-dialog').textContent.includes('42')`))
  // Simulate a lost response after a real successful save, then recover the
  // persisted Modbus device using the same onboarding request.
  await evaluate(`(()=>{const original=window.fetch;window.fetch=async(url,options)=>{if(String(url).endsWith('/api/v1/onboarding')&&options?.method==='POST'){window.fetch=original;const response=await original(url,options);window.__nativeOnboarding=await response.clone().json();if(response.ok)throw new TypeError('测试注入：保存响应丢失');return response}return original(url,options)}})()`)
  await click('完成并启用')
  await until(()=>evaluate(`document.body.textContent.includes('测试注入：保存响应丢失')`))
  await click('完成并启用')
  await until(()=>evaluate(`document.querySelector('.el-dialog')?.textContent.includes('已恢复上次保存的接入配置')`))
  const nativeSaved = await evaluate('window.__nativeOnboarding')
  assert.equal('credential' in nativeSaved,false)
  assert.equal('accessKey' in nativeSaved.device,false)
  assert.equal('clientId' in nativeSaved,false)
  assert.equal(await evaluate(`/凭据|密钥|客户端标识/.test(document.querySelector('.el-dialog').textContent)`),false)
  assert.ok(await evaluate(`document.querySelector('.el-dialog .el-descriptions').textContent.includes('127.0.0.1') && document.querySelector('.el-dialog .el-descriptions').textContent.includes('站号')`))
  await click('进入设备详情')
  await until(()=>evaluate(`document.querySelector('.el-drawer')?.textContent.includes('Modbus TCP')`))
  assert.equal(await evaluate(`/凭据|密钥/.test(document.querySelector('.el-drawer').textContent)`),false)
  await evaluate(`document.querySelector('.el-drawer__close-btn').click()`)
  assert.equal(await evaluate(`document.querySelector('.el-table__header-wrapper')?.textContent.includes('接入密钥')`),false)
  await until(()=>evaluate(`(()=>{const row=[...document.querySelectorAll('.el-table__row')].find(e=>e.textContent.includes('browser-modbus-preview'));const button=row?.querySelector('[aria-label="更多设备操作"]');if(!button)return false;button.click();return true})()`))
  await until(()=>evaluate(`!![...document.querySelectorAll('.el-dropdown-menu')].find(e=>e.getClientRects().length)`))
  assert.equal(await evaluate(`[...document.querySelectorAll('.el-dropdown-menu')].filter(e=>e.getClientRects().length).some(e=>e.textContent.includes('轮换凭证'))`),false)
  await evaluate(`document.body.click()`)
  await click('接入指南')
  const nativeGuideButton = text => `(()=>{const row=[...document.querySelectorAll('.el-table__row')].find(e=>e.textContent.includes('browser-modbus-preview'));const button=[...(row?.querySelectorAll('button')||[])].find(e=>e.textContent.trim()===${JSON.stringify(text)});if(!button)return false;button.click();return true})()`
  await until(()=>evaluate(nativeGuideButton('连接指南')))
  await until(()=>evaluate(`document.querySelector('.el-drawer')?.textContent.includes('Modbus TCP')`))
  assert.equal(await evaluate(`/凭据|密钥/.test(document.querySelector('.el-drawer').textContent)`),false)
  await evaluate(`document.querySelector('.el-drawer__close-btn').click()`)
  await until(()=>evaluate(nativeGuideButton('数据联调')))
  await until(()=>evaluate(`document.querySelector('.el-dialog')?.textContent.includes('这里用于验证协议包')`))
  assert.equal(await evaluate(`!![...document.querySelectorAll('.el-drawer')].find(e=>e.getClientRects().length)`),false)
  await evaluate(`document.querySelector('.el-dialog__headerbtn').click()`)
  await click('设备管理')
  await click('添加设备')
  await until(()=>evaluate(`(()=>{const e=document.querySelector('.el-dialog .el-switch');if(!e)return false;e.click();return true})()`))
  await fill('新产品名称','浏览器标准产品')
  await click('下一步')
  await evaluate(`([...document.querySelectorAll('.el-radio')].find(e=>e.textContent.trim()==='TCP')).click()`)
  await click('下一步')
  await evaluate(`document.querySelector('.el-dialog .el-switch').click()`)
  assert.equal(await evaluate(`document.querySelector('.el-dialog').textContent.includes('管理节点') || document.querySelector('.el-dialog').textContent.includes('现场边缘节点')`), false)
  await click('上一步')
  await evaluate(`([...document.querySelectorAll('.el-radio')].find(e=>e.textContent.includes('HTTP'))).click()`)
  await click('下一步')
  await fill('设备名称','浏览器传感器');await fill('设备标识','browser-device')
  await evaluate(`([...document.querySelectorAll('.el-form-item')].find(e=>e.querySelector('label')?.textContent.trim()==='上报类型')).querySelector('.el-select__wrapper').click()`)
  await until(()=>evaluate(`(()=>{const e=[...document.querySelectorAll('.el-select-dropdown__item')].find(e=>e.textContent.trim()==='状态'&&e.getClientRects().length);if(!e)return false;e.click();return true})()`))
  await click('上一步')
  await evaluate(`([...document.querySelectorAll('.el-radio')].find(e=>e.textContent.includes('MQTT'))).click()`)
  await click('下一步')
  assert.ok(await evaluate(`document.querySelector('.el-dialog textarea').value.includes('CONNECTED')`))
  await click('上一步')
  await evaluate(`([...document.querySelectorAll('.el-radio')].find(e=>e.textContent.includes('HTTP'))).click()`)
  await click('下一步')
  await click('下一步');await click('运行接入测试')
  await until(()=>evaluate(`document.querySelector('.el-dialog')?.textContent.includes('SUCCESS')`))
  await click('上一步')
  await fill('设备名称','浏览器传感器修订')
  await click('下一步')
  assert.ok(await evaluate(`[...document.querySelectorAll('.el-dialog button')].find(e=>e.textContent.trim()==='下一步').disabled`))
  assert.ok(await evaluate(`!document.querySelector('.el-dialog').textContent.includes('SUCCESS')`))
  await click('运行接入测试')
  await until(()=>evaluate(`document.querySelector('.el-dialog')?.textContent.includes('SUCCESS')`))
  await click('下一步')
  assert.ok(await evaluate(`document.querySelector('.el-dialog').textContent.includes('iot_standard_parser')`))
  // A controlled failed save verifies the UI retry without mutating existing data.
  await evaluate(`(()=>{const original=window.fetch;window.fetch=(url,options)=>{if(String(url).endsWith('/api/v1/onboarding')&&options?.method==='POST'){window.fetch=original;return Promise.resolve(new Response(JSON.stringify({detail:'测试注入：保存失败，请重试'}),{status:503,headers:{'Content-Type':'application/json'}}))}return original(url,options)}})()`)
  await click('完成并启用')
  await until(()=>evaluate(`document.body.textContent.includes('测试注入：保存失败，请重试')`))
  assert.ok(await evaluate(`!document.querySelector('.el-dialog').textContent.includes('接入配置已保存，设备已启用')`))
  await click('完成并启用')
  await until(()=>evaluate(`document.querySelector('.el-dialog')?.textContent.includes('接入配置已保存，设备已启用')`))
  assert.ok(await evaluate(`document.querySelector('.el-dialog').textContent.includes('/iot/up/tenant/')`))
  const deviceCredential = await evaluate(`Array.from(document.querySelectorAll('.el-dialog .el-descriptions__content')).map(e=>e.textContent.trim())`)
  assert.ok(await evaluate(`document.querySelector('.el-dialog').textContent.includes('等待设备首条上报')`))
  await click('进入设备详情')
  await until(()=>evaluate(`document.querySelector('.el-drawer')?.textContent.includes('iot-standard')`))
  assert.ok(await evaluate(`document.querySelector('.el-drawer').textContent.includes('连接与状态历史')`))
  assert.ok(await evaluate(`document.querySelector('.el-drawer').textContent.includes('最近事件')`))
  assert.ok(await evaluate(`document.querySelector('.el-drawer').textContent.includes('最近告警')`))
  assert.equal(await evaluate(`document.querySelector('.el-drawer').textContent.includes('设备影子') || document.querySelector('.el-drawer').textContent.includes('设备孪生与拓扑')`),false)
  await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true})
  await evaluate('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))')
  await until(()=>evaluate(`document.querySelector('.el-drawer').getBoundingClientRect().width<=391`))
  await evaluate(`document.querySelector('.el-drawer__close-btn').click()`)
  await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false})
  await until(()=>evaluate(`(()=>{const row=[...document.querySelectorAll('.el-table__row')].find(e=>e.textContent.includes('历史设备'));const button=[...(row?.querySelectorAll('button')||[])].find(e=>e.textContent.trim()==='连接详情');if(!button)return false;button.click();return true})()`))
  await until(()=>evaluate(`document.querySelector('.el-drawer')?.textContent.includes('检测到多个关联实例')`))
  assert.ok(await evaluate(`![...document.querySelectorAll('.el-drawer button')].some(e=>e.textContent.trim()==='发送命令')`))
  await evaluate(`document.querySelector('.el-drawer .el-select__wrapper').click()`)
  await until(()=>evaluate(`(()=>{const option=[...document.querySelectorAll('.el-select-dropdown__item')].find(e=>e.textContent.trim()==='listener-a'&&e.getClientRects().length);if(!option)return false;option.click();return true})()`))
  await until(()=>evaluate(`document.querySelector('.el-drawer .el-descriptions')?.textContent.includes('TCP')`))
  assert.ok(await evaluate(`document.querySelector('.el-drawer .el-table').textContent.includes('listener-a') && !document.querySelector('.el-drawer .el-table').textContent.includes('listener-b')`))
  await evaluate(`document.querySelector('.el-drawer__close-btn').click()`)
  await click('设备接入')
  await until(()=>evaluate(`(()=>{const tab=[...document.querySelectorAll('[role=tab]')].find(e=>e.textContent.trim()==='接入实例');if(!tab)return false;tab.click();return true})()`))
  await until(()=>evaluate(`(()=>{const row=[...document.querySelectorAll('.el-table__row')].find(e=>e.textContent.includes('listener-a')&&e.getClientRects().length);const expand=row?.querySelector('.el-table__expand-icon');if(!expand)return false;expand.click();return true})()`))
  await until(()=>evaluate(`document.querySelector('.instance-details')?.textContent.includes('127.0.0.1:1234')`))
  assert.ok(await evaluate(`document.querySelector('.instance-details').textContent.includes('历史设备')`))
  await click('测试设备')
  await until(()=>evaluate(`!!document.querySelector('.standard-commissioning')`))
  await fill('标准设备标识','browser-device');await fill('接入密钥',deviceCredential[2]);await fill('设备密钥','invalid-secret')
  await click('发送新消息')
  await until(()=>evaluate(`document.querySelector('.standard-commissioning .el-alert')?.textContent.includes('AUTH_FAILED')`))
  await fill('设备密钥',deviceCredential[3]);await click('发送新消息')
  await until(()=>evaluate(`document.querySelector('.standard-commissioning .el-table')?.textContent.includes('已解析')`))
  await click('重发同一条消息')
  await until(()=>evaluate(`document.querySelector('.standard-commissioning .el-table')?.textContent.includes('平台已去重')`))
  assert.ok(await evaluate(`document.querySelector('.standard-commissioning pre').textContent.includes('temperature')`))
  if(process.env.IOT_TEST_MQTT_WEBSOCKET) {
    await evaluate(`([...document.querySelectorAll('.standard-commissioning .el-radio')].find(e=>e.textContent.trim()==='MQTT')).click()`)
    await fill('设备密钥','invalid-mqtt-secret')
    await click('连接 / 重新认证')
    await until(()=>evaluate(`document.querySelector('.standard-commissioning')?.textContent.includes('认证拒绝，请检查或重新生成凭据')`))
    assert.ok(await evaluate(`!!localStorage.getItem('iot_token')`))
    await fill('设备密钥',deviceCredential[3])
    await click('连接 / 重新认证')
    await until(()=>evaluate(`([...document.querySelectorAll('.standard-commissioning p')].some(e=>e.textContent.trim()==='已连接'))`)).catch(async e=>{console.log(await evaluate(`Array.from(document.querySelectorAll('.standard-commissioning p, .standard-commissioning .el-alert')).map(e=>e.textContent.trim()).filter(x=>!x.includes('密钥'))`));throw e})
    await click('发送新消息')
    await until(()=>evaluate(`document.querySelector('.standard-commissioning .el-table')?.textContent.includes('已解析')`))
    const outageSeconds = Number(process.env.IOT_TEST_BROWSER_OUTAGE_SECONDS || 0)
    if(outageSeconds) {
      blockDeviceToken = true
      await call('Fetch.enable',{patterns:[{urlPattern:'*/api/v1/device-mqtt/token',requestStage:'Request'}]})
    }
    await click('模拟断链并重连')
    if(outageSeconds) {
      await until(()=>evaluate(`document.querySelector('.standard-commissioning')?.textContent.includes('等待重连')`))
      const outageStarted = Date.now()
      let nextProgress = 30000
      while(Date.now()-outageStarted < outageSeconds*1000) {
        await delay(Math.min(1000, outageSeconds*1000-(Date.now()-outageStarted)))
        if(Date.now()-outageStarted>=nextProgress){console.log(`OUTAGE: ${Math.floor((Date.now()-outageStarted)/1000)}/${outageSeconds}s, ${blockedTokenRequests} failed token requests`);nextProgress+=30000}
        assert.ok(await evaluate(`Number(document.querySelector('[data-testid=mqtt-connect-count]')?.textContent)===1`))
        assert.ok(await evaluate(`Array.from(document.querySelectorAll('.standard-commissioning button')).find(e=>e.textContent.trim()==='发送新消息').disabled`))
      }
      assert.ok(blockedTokenRequests>=1)
      blockDeviceToken = false
      await call('Fetch.disable')
      // Automatic backoff is capped at 30 seconds. Do not click reconnect.
      for(let attempt=0;attempt<40;attempt++) {
        if(await evaluate(`Number(document.querySelector('[data-testid=mqtt-connect-count]')?.textContent)>=2`))break
        await delay(1000)
      }
      assert.ok(await evaluate(`Number(document.querySelector('[data-testid=mqtt-connect-count]')?.textContent)>=2`))
      console.log(`PASS: ${outageSeconds}s real elapsed device-token network outage, ${blockedTokenRequests} failed requests, automatic recovery`)
    }
    await until(()=>evaluate(`Number(document.querySelector('[data-testid=mqtt-connect-count]')?.textContent)>=2`))
    await until(()=>evaluate(`([...document.querySelectorAll('.standard-commissioning p')].some(e=>e.textContent.trim()==='已连接'))`)).catch(async e=>{console.log(await evaluate(`Array.from(document.querySelectorAll('.standard-commissioning p, .standard-commissioning .el-alert')).map(e=>e.textContent.trim()).filter(x=>!x.includes('密钥'))`));throw e})
    await click('重发同一条消息')
    await until(()=>evaluate(`([...document.querySelectorAll('.standard-commissioning .el-table__row')].filter(e=>e.textContent.includes('已解析')).length===2)`))
    console.log('PASS: live Broker WebSocket credential rejection without operator logout, authentication, Raw parsing, injected transport loss, automatic reconnect and retransmission')
  }
  await evaluate(`(()=>{const original=URL.createObjectURL;URL.createObjectURL=function(blob){window.__commissioningReport=blob.text();return original.call(URL,blob)}})()`)
  await click('导出验收记录')
  const exported = await evaluate('window.__commissioningReport')
  assert.ok(JSON.parse(exported).records.length>=2)
  assert.equal(exported.includes(deviceCredential[3]), false)
  await click('设备管理');await click('测试设备')
  await until(()=>evaluate(`!!document.querySelector('.standard-commissioning input[type=password]')`))
  assert.equal(await evaluate(`document.querySelector('.standard-commissioning input[type=password]').value`), '')
  await click('摄像头映射')
  await click('新增摄像头')
  assert.equal(await evaluate(`document.body.textContent.includes('国标视频目录') || document.querySelector('.el-dialog').textContent.includes('ONVIF')`), false)
  await fill('摄像头标识','browser-camera');await fill('摄像头名称','直接登记摄像头')
  await click('保存')
  await until(()=>evaluate(`document.querySelector('.el-table')?.textContent.includes('直接登记摄像头')`))
  await click('模型管理')
  await until(()=>evaluate(`!!document.querySelector('.provider-select .el-select__wrapper')`))
  await evaluate(`document.querySelector('.provider-select .el-select__wrapper').click()`)
  await until(()=>evaluate(`([...document.querySelectorAll('.el-select-dropdown__item')].filter(e=>e.getClientRects().length).length>=3)`))
  const providerNames = await evaluate(`[...document.querySelectorAll('.el-select-dropdown__item')].filter(e=>e.getClientRects().length).map(e=>e.textContent.trim())`)
  assert.deepEqual(providerNames, ['Ollama','DeepSeek','OpenAI 兼容 API'])
  console.log('PASS: technical provider names are visible; no model test or configuration apply was performed')
  console.log('PASS: real browser onboarding, removed node controls, new product, test, preview, enable, connection history, mobile drawer, legacy profile selection, listener sessions and recent devices, HTTP credential rejection and deduplication, report export without secrets, credential cleanup')
} finally {
  if(socket)socket.close()
  const exited = new Promise(resolve=>{if(child.exitCode!==null||child.signalCode!==null)resolve();else child.once('exit',resolve)})
  child.kill()
  const forceStop=setTimeout(()=>child.kill('SIGKILL'),3000)
  forceStop.unref()
  await exited
  clearTimeout(forceStop)
  await rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100})
}
